// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT
//
// This file carries both the declarations and their implementation. Include it wherever the parser is used, and in
// exactly one translation unit define CALCULATOR_PARSER_IMPLEMENTATION before including it, which is what emits the
// tables and the function bodies:
//
//     #define CALCULATOR_PARSER_IMPLEMENTATION
//     #include "parser.h"
//
// Without that definition in one place the link fails with the parser functions undefined. The scanner is a separate
// file with a definition of its own, so a translation unit which brings in both defines both.

/* The scanner is included in front of the guard below, so that including this file a second time to bring in the
   implementation reaches the scanner header again. */
#include "scanner.h"

#ifndef CALCULATOR_PARSER_H
#define CALCULATOR_PARSER_H

#include <stdbool.h>
#include <stddef.h>

/// Every nonterminal symbol of the grammar.
typedef enum CalculatorNonterminal {
    /// The start symbol the generator adds around the one the grammar declares. Reaching it accepts the input.
    CALCULATOR_ACCEPT_NONTERMINAL,

    CALCULATOR_NONTERMINAL_EXPRESSION,
} CalculatorNonterminal;

/// Returns the name of the nonterminal, as the grammar spells it.
const char *calculator_nonterminal_to_string(CalculatorNonterminal nonterminal);

/// Every production of the grammar. Has no enumerator for production 0 ($accept), which is never reduced.
typedef enum CalculatorProduction {
    /// The production a terminal node carries, since no production reduces to it.
    CALCULATOR_NO_PRODUCTION = 0,
    CALCULATOR_PRODUCTION_EXPRESSION1 = 1,
    CALCULATOR_PRODUCTION_EXPRESSION2 = 2,
    CALCULATOR_PRODUCTION_EXPRESSION3 = 3,
    CALCULATOR_PRODUCTION_EXPRESSION4 = 4,
    CALCULATOR_PRODUCTION_EXPRESSION5 = 5,
    CALCULATOR_PRODUCTION_EXPRESSION6 = 6,
    CALCULATOR_PRODUCTION_EXPRESSION7 = 7,
} CalculatorProduction;

/// Returns the name of the production.
const char *calculator_production_to_string(CalculatorProduction production);

/// Whether a symbol of the parse tree is a terminal or a nonterminal.
typedef enum CalculatorSymbolKind {
    /// The symbol is a token the scanner delivered.
    CALCULATOR_SYMBOL_KIND_TERMINAL,

    /// The symbol is a nonterminal the parser reduced to.
    CALCULATOR_SYMBOL_KIND_NONTERMINAL
} CalculatorSymbolKind;

/// A terminal or a nonterminal. The kind says which of the two the value holds.
typedef struct CalculatorParseSymbol {
    /// Which of the two this symbol is.
    CalculatorSymbolKind kind;

    /// The symbol itself.
    union {
        /// Valid when the kind is a terminal.
        CalculatorToken terminal;

        /// Valid when the kind is a nonterminal.
        CalculatorNonterminal nonterminal;
    } value;
} CalculatorParseSymbol;

/// Reads the symbol as a terminal. Returns false and writes nothing when it is a nonterminal.
bool calculator_parse_symbol_terminal(const CalculatorParseSymbol *symbol, CalculatorToken *terminal);

/// Reads the symbol as a nonterminal. Returns false and writes nothing when it is a terminal.
bool calculator_parse_symbol_nonterminal(const CalculatorParseSymbol *symbol, CalculatorNonterminal *nonterminal);

/// Writes what the symbol is and the name the grammar spells it with into the given buffer and terminates it with a
/// zero. Returns the number of bytes the whole text needs, not counting that zero, so a return of at least the buffer
/// size means it was cut short. Writes nothing when the buffer size is zero.
size_t calculator_parse_symbol_to_string(const CalculatorParseSymbol *symbol, char *buffer, size_t buffer_size);

/// A single node of the parse tree. It carries the span of the source it covers, which calculator_scanner_text turns
/// back into bytes and calculator_scanner_position into a file path, a line and a column. It is owned by the result
/// it came with rather than by itself.
///
/// A terminal covers its lexeme and a nonterminal covers its children. The error symbol covers what the error recovery
/// threw away, up to the point it resumed at. A production with an empty right hand side has zero length at the end of
/// the symbol to its left.
typedef struct CalculatorParseNode CalculatorParseNode;
struct CalculatorParseNode {
    /// The terminal or nonterminal this node stands for.
    CalculatorParseSymbol symbol;

    /// The start of the source this node covers, in bytes from the start of the source.
    size_t byte_offset;

    /// The number of bytes of the source this node covers.
    size_t byte_length;

    /// The nodes of the right hand side of the production which was reduced to this node. Null for a terminal.
    CalculatorParseNode *children;

    /// The number of children. Zero for a terminal.
    size_t child_count;

    /// The production which was reduced to this node. CALCULATOR_NO_PRODUCTION for a terminal, which no
    /// production reduces to.
    CalculatorProduction production;
};

/// How many bytes a parse error keeps its reason in, the terminating zero included. A reason which does not fit is cut
/// short rather than allocated for.
#define CALCULATOR_PARSE_ERROR_REASON_SIZE 256

/// How many bytes a trace line is built in, the terminating zero included. A line which does not fit is cut short
/// rather than grown for; no real grammar produces one that long.
#define CALCULATOR_TRACE_LINE_SIZE 1024

/// What a parse error is about.
typedef enum CalculatorErrorKind {
    /// An error in the input.
    CALCULATOR_ERROR_KIND_SYNTAX,

    /// A defect of the parser itself, which ends the parse.
    CALCULATOR_ERROR_KIND_INTERNAL,

    /// An allocation failed, which ends the parse. The tree is then missing and the errors before this one are what
    /// the parser had found so far.
    CALCULATOR_ERROR_KIND_OUT_OF_MEMORY
} CalculatorErrorKind;

/// A single parse error. Parse errors are returned by the parse rather than raised, so reporting many of them costs
/// nothing.
typedef struct CalculatorParseError {
    /// What is wrong, without the position in front of it. Cut short when it does not fit, which is what the fixed
    /// size buys: an error costs no allocation of its own.
    char reason[CALCULATOR_PARSE_ERROR_REASON_SIZE];

    /// What the error is about.
    CalculatorErrorKind kind;

    /// The token the parse stopped on.
    CalculatorToken token;

    /// Start of that token in bytes from the start of the source.
    size_t byte_offset;

    /// Line that token starts on, counted from one.
    size_t line;

    /// Column that token starts on, counted from one.
    size_t column;

    /// The bytes of that token, as a range of the source.
    CalculatorStringView lexeme;

    /// The file path the scanner was given.
    const char *file_path;
} CalculatorParseError;

/// Writes the error in the file:line:column: reason form editors and build tools recognize into the given buffer and
/// terminates it with a zero. Returns the number of bytes the whole text needs, not counting that zero, so a return of
/// at least the buffer size means it was cut short. Writes nothing when the buffer size is zero.
size_t calculator_parse_error_message(const CalculatorParseError *error, char *buffer, size_t buffer_size);

/// Holds the nodes of a parse tree. Internal to the parser; a result releases it.
struct CalculatorArena;

/// What a parse returns. Everything in it is owned by the result and stays valid until it is released.
typedef struct CalculatorParseResult {
    /// The root of the parse tree, or null when the parse could not be finished.
    CalculatorParseNode *tree;

    /// Every error the parse reported, in the order they were found. Null when there were none.
    CalculatorParseError *errors;

    /// The number of errors.
    size_t error_count;

    /// Owns the nodes of the tree. Internal.
    struct CalculatorArena *arena;
} CalculatorParseResult;

/// Releases everything the result owns and leaves it empty. Safe to call more than once, and on a result of a parse
/// which failed.
void calculator_parse_result_free(CalculatorParseResult *result);

/// Receives one line per parser action. A debug aid; the line format carries no stability guarantee.
typedef void (*CalculatorTraceFunc)(void *context, const char *line);

/// Parses the tokens of a scanner into a parse tree. One parser serves one source after another, reusing the memory it
/// already has. Every field but trace and trace_context is internal.
typedef struct CalculatorParser {
    /// The hook called with one line for every action the parser takes, or null for no tracing. Set it, together with
    /// trace_context, after calculator_parser_init.
    CalculatorTraceFunc trace;

    /// The pointer handed to trace on every call.
    void *trace_context;

    size_t *state_stack;
    size_t state_count;
    size_t state_capacity;

    CalculatorParseNode *node_stack;
    size_t node_count;
    size_t node_capacity;

    CalculatorParseError *errors;
    size_t error_count;
    size_t error_capacity;

    struct CalculatorArena *arena;

    size_t error_recovery_shifts_remaining;
    bool out_of_memory;

    /// Whether an exploratory parse found the current lookahead to be shifted eventually, so the reductions leading
    /// there need no further check. Cleared on every shift and on every token discarded.
    bool exploratory_parse_passed;

    /// The states an exploratory parse pushes. The states below them are the ones of state_stack below
    /// exploratory_stack_base, which the exploratory parse reads but never writes.
    size_t *exploratory_stack;
    size_t exploratory_count;
    size_t exploratory_capacity;
    size_t exploratory_stack_base;

    /// Reused scratch for the assembled trace line and, while it is built, its payload.
    char trace_line[CALCULATOR_TRACE_LINE_SIZE];
    char trace_payload[CALCULATOR_TRACE_LINE_SIZE];
} CalculatorParser;

/// Prepares a parser which has nothing allocated yet.
void calculator_parser_init(CalculatorParser *parser);

/// Releases what the parser holds between parses. The results it produced are not affected and are released on their
/// own.
void calculator_parser_free(CalculatorParser *parser);

/// Parses the tokens the source delivers. Can be called more than once, with a different source each time.
///
/// When the grammar marks places to resume at with the error symbol, a syntax error does not end the parse: the result
/// then holds both the tree parsed so far, with a node for the error symbol at every place resumed at, and every error
/// found. The tree is null when the parse could not be carried to its end.
///
/// The result owns its tree and its errors, so it has to be released with the free function above. A result with no
/// tree and no errors at all means not even the first allocation of the parse succeeded.
CalculatorParseResult calculator_parser_parse(CalculatorParser *parser, const CalculatorTokenSource *scanner);

#endif  /* CALCULATOR_PARSER_H */

#ifdef CALCULATOR_PARSER_IMPLEMENTATION
#ifndef CALCULATOR_PARSER_IMPLEMENTATION_ONCE
#define CALCULATOR_PARSER_IMPLEMENTATION_ONCE

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/// How many tokens have to be shifted after a syntax error before errors are reported again. Suppressing the errors in
/// between keeps one mistake in the input from producing an avalanche of messages which all follow from it.
#define CALCULATOR_ERROR_RECOVERY_SHIFTS 3

/// The largest number of expected tokens a syntax error lists. With more of them, the list is left out, because it
/// would not help the reader any more.
#define CALCULATOR_EXPECTED_TOKENS_MAX 4

/// How many nodes a block of the arena holds. A reduction takes as many nodes as the production is long, so a block
/// serves many of them.
#define CALCULATOR_ARENA_BLOCK_NODES 256

/// How many entries the stacks start with room for. They grow as a deeper parse needs them to.
#define CALCULATOR_INITIAL_STACK_CAPACITY 64

/// How many errors the error list starts with room for. It grows as a parse finds more of them.
#define CALCULATOR_INITIAL_ERROR_CAPACITY 8

// The parse table is held in lookup tables. A token is translated into the column of the action table which holds the
// decisions for it, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao. The
// gotos are held the same way, with the nonterminal as the column.
//
// The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the action
// table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the tables.
//
// The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
// range check of its own.

/// Number of low bits of an action which hold what it does. The value it carries sits above them.
#define CALCULATOR_ACTION_KIND_BITS 2

/// Selects out of an action what it does.
#define CALCULATOR_ACTION_KIND_MASK 3

/// Shifts the terminal and continues in the state the action carries.
#define CALCULATOR_ACTION_KIND_SHIFT 0

/// Reduces by the production the action carries.
#define CALCULATOR_ACTION_KIND_REDUCE 1

/// Ends the parse successfully, the input having been reduced to the start symbol.
#define CALCULATOR_ACTION_KIND_ACCEPT 2

/// Rejects the terminal as a syntax error.
#define CALCULATOR_ACTION_KIND_ERROR 3

/// The column a token gets which is no terminal of this grammar. No state has an entry in it, so a lookup falls
/// through to the default action of the state.
#define CALCULATOR_NO_TERMINAL_COLUMN 0

/// The column holding the shifts of the error symbol, where the recovery reads the state to resume in.
#define CALCULATOR_ERROR_TERMINAL_COLUMN 0

/// Translates a column of the action table back into the token of its terminal. The
/// CALCULATOR_NO_TERMINAL_COLUMN stands for no token.
static const CalculatorToken CALCULATOR_TOKEN_BY_TERMINAL_COLUMN[11] = {
    [1] = CALCULATOR_TOKEN_END_TOKEN,
    [2] = CALCULATOR_TOKEN_WHITESPACE,
    [3] = CALCULATOR_TOKEN_INTEGER,
    [4] = CALCULATOR_TOKEN_PLUS,
    [5] = CALCULATOR_TOKEN_MINUS,
    [6] = CALCULATOR_TOKEN_MULTIPLY,
    [7] = CALCULATOR_TOKEN_DIVIDE,
    [8] = CALCULATOR_TOKEN_LPAREN,
    [9] = CALCULATOR_TOKEN_RPAREN,
    [10] = CALCULATOR_TOKEN_UMINUS,
};

/// Maps a state to the displacement of its row within CALCULATOR_ACTION_NEXT.
static const uint8_t CALCULATOR_ACTION_BASE[] = {
    9, 1, 9, 9, 0, 1, 4, 1, 9, 9, 9, 9, 1, 12, 12, 1,
    1,
};

/// Holds the action of every entry. The action a state has for a column lives at CALCULATOR_ACTION_BASE[state] +
/// column, but only if CALCULATOR_ACTION_CHECK confirms the cell belongs to that column.
static const uint8_t CALCULATOR_ACTION_NEXT[] = {
    0, 28, 0, 0, 32, 36, 40, 44, 32, 36, 40, 44, 4, 48, 8, 0,
    0, 12, 40, 44, 0, 0, 0,
};

/// Holds the column every cell of CALCULATOR_ACTION_NEXT belongs to. A cell no state occupies holds
/// 11, which is one past the highest column in use and can never be asked for.
static const uint8_t CALCULATOR_ACTION_CHECK[] = {
    11, 1, 11, 11, 4, 5, 6, 7, 4, 5, 6, 7, 3, 9, 5, 11,
    11, 8, 6, 7, 11, 11, 11,
};

/// Holds the action a state takes for every column it has no entry of its own for. A state which has none carries the
/// error action.
static const uint8_t CALCULATOR_DEFAULT_ACTION_BY_STATE[] = {
    3, 5, 3, 3, 3, 25, 3, 2, 3, 3, 3, 3, 29, 9, 13, 17,
    21,
};

/// Holds 1 for a state which reduces by the same production whatever the lookahead is, and 0 otherwise. A consistent
/// state needs no lookahead, so it never starts an exploratory parse.
static const uint8_t CALCULATOR_CONSISTENT_BY_STATE[] = {
    0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
    1,
};

/// Maps a state to the displacement of its row within CALCULATOR_GOTO_NEXT.
static const uint8_t CALCULATOR_GOTO_BASE[] = {
    6, 6, 0, 1, 6, 6, 6, 6, 2, 3, 4, 5, 6, 6, 6, 6,
    6,
};

/// Holds the state a goto leads to. The goto a state has for a nonterminal lives at CALCULATOR_GOTO_BASE[state] +
/// nonterminal, but only if CALCULATOR_GOTO_CHECK confirms the cell belongs to that nonterminal.
static const uint8_t CALCULATOR_GOTO_NEXT[] = {
    0, 5, 6, 13, 14, 15, 16, 0,
};

/// Holds the nonterminal every cell of CALCULATOR_GOTO_NEXT belongs to. A cell no state occupies holds
/// 2, which is one past the highest nonterminal and can never be asked for.
static const uint8_t CALCULATOR_GOTO_CHECK[] = {
    2, 1, 1, 1, 1, 1, 1, 2,
};

/// Holds the state a goto on a nonterminal leads to for every state CALCULATOR_GOTO_NEXT has no entry for.
static const uint8_t CALCULATOR_DEFAULT_GOTO_BY_NONTERMINAL[] = {
    0, 4,
};

/// Holds how many symbols a reduction takes off the stacks, which is the length of the right hand side.
static const uint8_t CALCULATOR_POP_COUNT_BY_PRODUCTION[] = {
    2, 1, 3, 3, 3, 3, 2, 3,
};

/// Holds the nonterminal on the left hand side of a production.
static const uint8_t CALCULATOR_NONTERMINAL_BY_PRODUCTION[] = {
    0, 1, 1, 1, 1, 1, 1, 1,
};

const char *calculator_nonterminal_to_string(CalculatorNonterminal nonterminal) {
    switch (nonterminal) {
    case CALCULATOR_ACCEPT_NONTERMINAL:
        return "$accept";
    case CALCULATOR_NONTERMINAL_EXPRESSION:
        return "expression";
    }
    return "unknown";
}

const char *calculator_production_to_string(CalculatorProduction production) {
    switch (production) {
    case CALCULATOR_NO_PRODUCTION:
        return "none";
    case CALCULATOR_PRODUCTION_EXPRESSION1:
        return "expression_1";
    case CALCULATOR_PRODUCTION_EXPRESSION2:
        return "expression_2";
    case CALCULATOR_PRODUCTION_EXPRESSION3:
        return "expression_3";
    case CALCULATOR_PRODUCTION_EXPRESSION4:
        return "expression_4";
    case CALCULATOR_PRODUCTION_EXPRESSION5:
        return "expression_5";
    case CALCULATOR_PRODUCTION_EXPRESSION6:
        return "expression_6";
    case CALCULATOR_PRODUCTION_EXPRESSION7:
        return "expression_7";
    }
    return "unknown";
}

bool calculator_parse_symbol_terminal(const CalculatorParseSymbol *symbol, CalculatorToken *terminal) {
    if (symbol->kind != CALCULATOR_SYMBOL_KIND_TERMINAL) {
        return false;
    }
    *terminal = symbol->value.terminal;
    return true;
}

bool calculator_parse_symbol_nonterminal(const CalculatorParseSymbol *symbol, CalculatorNonterminal *nonterminal) {
    if (symbol->kind != CALCULATOR_SYMBOL_KIND_NONTERMINAL) {
        return false;
    }
    *nonterminal = symbol->value.nonterminal;
    return true;
}

size_t calculator_parse_symbol_to_string(const CalculatorParseSymbol *symbol, char *buffer, size_t buffer_size) {
    int written;
    if (symbol->kind == CALCULATOR_SYMBOL_KIND_TERMINAL) {
        written = snprintf(buffer, buffer_size, "terminal %s", calculator_token_to_string(symbol->value.terminal));
    } else {
        written = snprintf(
            buffer, buffer_size, "nonterminal %s", calculator_nonterminal_to_string(symbol->value.nonterminal));
    }
    return written < 0 ? 0 : (size_t)written;
}

size_t calculator_parse_error_message(const CalculatorParseError *error, char *buffer, size_t buffer_size) {
    int written = snprintf(
        buffer, buffer_size, "%s:%zu:%zu: %s", error->file_path, error->line, error->column, error->reason);
    return written < 0 ? 0 : (size_t)written;
}

/// One block of the arena. The blocks form a list, so releasing the whole tree is walking that list rather than the
/// tree itself, which a tree deep enough would not survive.
struct CalculatorArena {
    struct CalculatorArena *next;
    CalculatorParseNode *nodes;
    size_t used;
    size_t capacity;
};

/// Returns room for the given number of nodes, taken from the newest block or from a fresh one. Returns null when the
/// allocation failed.
static CalculatorParseNode *calculator_arena_allocate(struct CalculatorArena **arena, size_t count) {
    struct CalculatorArena *block = *arena;
    CalculatorParseNode *nodes;
    size_t capacity;

    if (block != NULL && count <= block->capacity - block->used) {
        nodes = block->nodes + block->used;
        block->used += count;
        return nodes;
    }

    capacity = count > CALCULATOR_ARENA_BLOCK_NODES ? count : (size_t)CALCULATOR_ARENA_BLOCK_NODES;
    block = (struct CalculatorArena *)malloc(sizeof(struct CalculatorArena));
    if (block == NULL) {
        return NULL;
    }
    block->nodes = (CalculatorParseNode *)malloc(capacity * sizeof(CalculatorParseNode));
    if (block->nodes == NULL) {
        free(block);
        return NULL;
    }
    block->capacity = capacity;
    block->used = count;
    block->next = *arena;
    *arena = block;
    return block->nodes;
}

/// Releases every block of the arena.
static void calculator_arena_free(struct CalculatorArena *arena) {
    while (arena != NULL) {
        struct CalculatorArena *next = arena->next;
        free(arena->nodes);
        free(arena);
        arena = next;
    }
}

/// Grows the state stack to hold at least the given number of entries. Returns false when the allocation failed.
static bool calculator_parser_reserve_states(CalculatorParser *parser, size_t count) {
    size_t capacity;
    size_t *states;

    if (count <= parser->state_capacity) {
        return true;
    }
    capacity = parser->state_capacity == 0 ? CALCULATOR_INITIAL_STACK_CAPACITY : parser->state_capacity * 2;
    while (capacity < count) {
        capacity *= 2;
    }
    states = (size_t *)realloc(parser->state_stack, capacity * sizeof(size_t));
    if (states == NULL) {
        parser->out_of_memory = true;
        return false;
    }
    parser->state_stack = states;
    parser->state_capacity = capacity;
    return true;
}

/// Grows the stack of the exploratory parse to hold at least the given number of entries. Returns false when the
/// allocation failed.
static bool calculator_parser_reserve_exploratory_states(CalculatorParser *parser, size_t count) {
    size_t capacity;
    size_t *states;

    if (count <= parser->exploratory_capacity) {
        return true;
    }
    capacity = parser->exploratory_capacity == 0 ? CALCULATOR_INITIAL_STACK_CAPACITY : parser->exploratory_capacity * 2;
    while (capacity < count) {
        capacity *= 2;
    }
    states = (size_t *)realloc(parser->exploratory_stack, capacity * sizeof(size_t));
    if (states == NULL) {
        parser->out_of_memory = true;
        return false;
    }
    parser->exploratory_stack = states;
    parser->exploratory_capacity = capacity;
    return true;
}

/// Grows the node stack to hold at least the given number of entries. Returns false when the allocation failed.
static bool calculator_parser_reserve_nodes(CalculatorParser *parser, size_t count) {
    size_t capacity;
    CalculatorParseNode *nodes;

    if (count <= parser->node_capacity) {
        return true;
    }
    capacity = parser->node_capacity == 0 ? CALCULATOR_INITIAL_STACK_CAPACITY : parser->node_capacity * 2;
    while (capacity < count) {
        capacity *= 2;
    }
    nodes = (CalculatorParseNode *)realloc(parser->node_stack, capacity * sizeof(CalculatorParseNode));
    if (nodes == NULL) {
        parser->out_of_memory = true;
        return false;
    }
    parser->node_stack = nodes;
    parser->node_capacity = capacity;
    return true;
}

/// Grows the error list to hold at least the given number of entries. Returns false when the allocation failed.
static bool calculator_parser_reserve_errors(CalculatorParser *parser, size_t count) {
    size_t capacity;
    CalculatorParseError *errors;

    if (count <= parser->error_capacity) {
        return true;
    }
    capacity = parser->error_capacity == 0 ? CALCULATOR_INITIAL_ERROR_CAPACITY : parser->error_capacity * 2;
    while (capacity < count) {
        capacity *= 2;
    }
    errors = (CalculatorParseError *)realloc(parser->errors, capacity * sizeof(CalculatorParseError));
    if (errors == NULL) {
        parser->out_of_memory = true;
        return false;
    }
    parser->errors = errors;
    parser->error_capacity = capacity;
    return true;
}

/// Returns an error with the given reason at the position the given scanner is at. A reason longer than the field is
/// cut short.
static CalculatorParseError calculator_parse_error_at(const char *reason, CalculatorErrorKind kind, const CalculatorTokenSource *scanner) {
    CalculatorParseError error;
    CalculatorPosition position = scanner->position(scanner->context, scanner->byte_offset(scanner->context));
    size_t length = strlen(reason);

    if (length >= sizeof(error.reason)) {
        length = sizeof(error.reason) - 1;
    }
    memcpy(error.reason, reason, length);
    error.reason[length] = '\0';

    error.kind = kind;
    error.token = scanner->token(scanner->context);
    error.byte_offset = position.byte_offset;
    error.line = position.line;
    error.column = position.column;
    error.lexeme = scanner->lexeme(scanner->context);
    error.file_path = position.file_path;
    return error;
}

/// Appends an error, keeping one slot in reserve so that running out of memory can always be reported.
static bool calculator_parser_append_error(CalculatorParser *parser, const CalculatorParseError *error) {
    if (!calculator_parser_reserve_errors(parser, parser->error_count + 2)) {
        return false;
    }
    parser->errors[parser->error_count] = *error;
    parser->error_count++;
    return true;
}

/// Records that an allocation failed, using the slot the appending above keeps in reserve.
static void calculator_parser_report_out_of_memory(CalculatorParser *parser, const CalculatorTokenSource *scanner) {
    if (parser->error_count < parser->error_capacity) {
        parser->errors[parser->error_count] = calculator_parse_error_at("out of memory", CALCULATOR_ERROR_KIND_OUT_OF_MEMORY, scanner);
        parser->error_count++;
    }
}

/// Returns the state on top of the stack, which is the one the parse is in.
static size_t calculator_parser_current_state(const CalculatorParser *parser) {
    return parser->state_stack[parser->state_count - 1];
}

/// Puts a state on the stack. Returns false when the allocation failed.
static bool calculator_parser_push_state(CalculatorParser *parser, size_t state) {
    if (!calculator_parser_reserve_states(parser, parser->state_count + 1)) {
        return false;
    }
    parser->state_stack[parser->state_count] = state;
    parser->state_count++;
    return true;
}

/// Puts a node on the stack. Returns false when the allocation failed.
static bool calculator_parser_push_node(CalculatorParser *parser, const CalculatorParseNode *node) {
    if (!calculator_parser_reserve_nodes(parser, parser->node_count + 1)) {
        return false;
    }
    parser->node_stack[parser->node_count] = *node;
    parser->node_count++;
    return true;
}

/// Returns the column of the action table which holds the decisions for the given token. A token the grammar does not
/// have gets the column no state occupies.
static size_t calculator_terminal_column(CalculatorToken token) {
    switch (token) {
    case CALCULATOR_TOKEN_END_TOKEN:
        return 1;
    case CALCULATOR_TOKEN_WHITESPACE:
        return 2;
    case CALCULATOR_TOKEN_INTEGER:
        return 3;
    case CALCULATOR_TOKEN_PLUS:
        return 4;
    case CALCULATOR_TOKEN_MINUS:
        return 5;
    case CALCULATOR_TOKEN_MULTIPLY:
        return 6;
    case CALCULATOR_TOKEN_DIVIDE:
        return 7;
    case CALCULATOR_TOKEN_LPAREN:
        return 8;
    case CALCULATOR_TOKEN_RPAREN:
        return 9;
    case CALCULATOR_TOKEN_UMINUS:
        return 10;
    default:
        return CALCULATOR_NO_TERMINAL_COLUMN;
    }
}

/// Returns the action the given state takes for the terminal of the given column.
static size_t calculator_action(size_t state, size_t column) {
    size_t cell_idx = CALCULATOR_ACTION_BASE[state] + column;
    if (CALCULATOR_ACTION_CHECK[cell_idx] == column) {
        /* An entry the state has of its own beats its default action, which is what keeps a token the grammar rejects
           on purpose an error even in a state which reduces on everything else. */
        return CALCULATOR_ACTION_NEXT[cell_idx];
    }
    return CALCULATOR_DEFAULT_ACTION_BY_STATE[state];
}

/// Returns the state the parse continues in when it reduced to the given nonterminal and uncovered the given state.
static size_t calculator_goto_state(size_t state, size_t nonterminal) {
    size_t cell_idx = CALCULATOR_GOTO_BASE[state] + nonterminal;
    if (CALCULATOR_GOTO_CHECK[cell_idx] == nonterminal) {
        return CALCULATOR_GOTO_NEXT[cell_idx];
    }
    /* A state without a goto of its own on the nonterminal goes where most states go with it. A state which a
       reduction uncovers always has one, so there is no case for a nonterminal missing from both. */
    return CALCULATOR_DEFAULT_GOTO_BY_NONTERMINAL[nonterminal];
}

/// Returns the state to continue in when the error symbol is shifted in the given state, and whether the state can
/// shift it at all. The states which can are the places the grammar marked to resume at after a syntax error.
///
/// The default action of the state is deliberately not consulted, because only an entry the state has of its own is a
/// place to resume at.
static bool calculator_error_shift_state(size_t state, size_t *next_state) {
    size_t cell_idx = CALCULATOR_ACTION_BASE[state] + CALCULATOR_ERROR_TERMINAL_COLUMN;
    size_t cell_column = CALCULATOR_ACTION_CHECK[cell_idx];
    size_t action;

    if (cell_column != CALCULATOR_ERROR_TERMINAL_COLUMN) {
        return false;
    }

    action = CALCULATOR_ACTION_NEXT[cell_idx];
    if ((action & CALCULATOR_ACTION_KIND_MASK) != CALCULATOR_ACTION_KIND_SHIFT) {
        return false;
    }
    *next_state = action >> CALCULATOR_ACTION_KIND_BITS;
    return true;
}

/// Names a terminal by the alias the grammar gives it, or by its name if it has none.
static const char *calculator_terminal_name(CalculatorToken token) {
    switch (token) {
    case CALCULATOR_TOKEN_END_TOKEN:
        return "end of input";
    case CALCULATOR_TOKEN_INVALID_TOKEN:
        return "invalid input";
    case CALCULATOR_TOKEN_PLUS:
        return "\"+\"";
    case CALCULATOR_TOKEN_MINUS:
        return "\"-\"";
    case CALCULATOR_TOKEN_MULTIPLY:
        return "\"*\"";
    case CALCULATOR_TOKEN_DIVIDE:
        return "\"/\"";
    case CALCULATOR_TOKEN_LPAREN:
        return "\"(\"";
    case CALCULATOR_TOKEN_RPAREN:
        return "\")\"";
    default:
        return calculator_token_to_string(token);
    }
}

/// Names a terminal for a trace line, giving the three tokens the grammar cannot spell a dollar name.
static const char *calculator_terminal_trace_name(CalculatorToken token) {
    switch (token) {
    case CALCULATOR_TOKEN_END_TOKEN:
        return "$end";
    case CALCULATOR_TOKEN_ERROR_TOKEN:
        return "$error";
    case CALCULATOR_TOKEN_INVALID_TOKEN:
        return "$invalid";
    default:
        return calculator_token_to_string(token);
    }
}

/// The bare grammar name of a symbol, without the prefix calculator_parse_symbol_to_string adds.
static const char *calculator_symbol_trace_name(const CalculatorParseSymbol *symbol) {
    if (symbol->kind == CALCULATOR_SYMBOL_KIND_TERMINAL) {
        return calculator_terminal_trace_name(symbol->value.terminal);
    }
    return calculator_nonterminal_to_string(symbol->value.nonterminal);
}

/// Builds "<name> \"<escaped lexeme>\"" into parser->trace_payload for a SHIFT or DISCARD line, escaping the lexeme
/// byte by byte and cutting the whole thing short when it does not fit.
static void calculator_parser_trace_lexeme_payload(CalculatorParser *parser, const char *name, CalculatorStringView lexeme) {
    static const char hex_digits[] = "0123456789abcdef";
    int written = snprintf(parser->trace_payload, sizeof(parser->trace_payload), "%s \"", name);
    size_t length = written < 0 ? 0 : (size_t)written;
    size_t idx;

    if (length >= sizeof(parser->trace_payload)) {
        length = sizeof(parser->trace_payload) - 1;
    }
    /* Leaves room for the widest escape, the closing quote and the terminating zero. */
    for (idx = 0; idx < lexeme.length && length + 5 < sizeof(parser->trace_payload); idx++) {
        unsigned char value = (unsigned char)lexeme.data[idx];
        switch (value) {
        case '\\':
            parser->trace_payload[length++] = '\\';
            parser->trace_payload[length++] = '\\';
            break;
        case '"':
            parser->trace_payload[length++] = '\\';
            parser->trace_payload[length++] = '"';
            break;
        case '\n':
            parser->trace_payload[length++] = '\\';
            parser->trace_payload[length++] = 'n';
            break;
        case '\r':
            parser->trace_payload[length++] = '\\';
            parser->trace_payload[length++] = 'r';
            break;
        case '\t':
            parser->trace_payload[length++] = '\\';
            parser->trace_payload[length++] = 't';
            break;
        default:
            if (0x20 <= value && value <= 0x7e) {
                parser->trace_payload[length++] = (char)value;
            } else {
                parser->trace_payload[length++] = '\\';
                parser->trace_payload[length++] = 'x';
                parser->trace_payload[length++] = hex_digits[(size_t)(value >> 4)];
                parser->trace_payload[length++] = hex_digits[(size_t)(value & 0x0f)];
            }
            break;
        }
    }

    parser->trace_payload[length++] = '"';
    parser->trace_payload[length] = '\0';
}

/// Builds "<lhs> => <rhs>..." into parser->trace_payload for a REDUCE line, or "<lhs> => ε" for an empty right hand
/// side, cutting it short when it does not fit. The right hand side is the top nodes of the node stack, which are still
/// there when this runs.
static void calculator_parser_trace_reduce_payload(CalculatorParser *parser, CalculatorNonterminal lhs, size_t rhs_count) {
    int written = snprintf(parser->trace_payload, sizeof(parser->trace_payload), "%s =>", calculator_nonterminal_to_string(lhs));
    size_t length = written < 0 ? 0 : (size_t)written;
    size_t idx;

    if (length >= sizeof(parser->trace_payload)) {
        return;
    }
    if (rhs_count == 0) {
        snprintf(parser->trace_payload + length, sizeof(parser->trace_payload) - length, " ε");
        return;
    }
    for (idx = 0; idx < rhs_count; idx++) {
        const char *name = calculator_symbol_trace_name(&parser->node_stack[parser->node_count - rhs_count + idx].symbol);
        int piece = snprintf(parser->trace_payload + length, sizeof(parser->trace_payload) - length, " %s", name);
        if (piece < 0) {
            return;
        }
        length += (size_t)piece;
        if (length >= sizeof(parser->trace_payload)) {
            return;
        }
    }
}

/// Hands one trace line to parser->trace: the position of the current lookahead left justified to seven, the keyword
/// left justified to seven when a payload follows, and the payload. A null payload leaves it off. A line which does not
/// fit parser->trace_line is cut short. The caller has checked that parser->trace is set.
static void calculator_parser_emit_trace(CalculatorParser *parser, const CalculatorTokenSource *scanner, const char *keyword, const char *payload) {
    CalculatorPosition position = scanner->position(scanner->context, scanner->byte_offset(scanner->context));
    char location[48];

    snprintf(location, sizeof(location), "%zu:%zu", position.line, position.column);
    if (payload != NULL) {
        snprintf(parser->trace_line, sizeof(parser->trace_line), "%-7s %-7s %s", location, keyword, payload);
    } else {
        snprintf(parser->trace_line, sizeof(parser->trace_line), "%-7s %s", location, keyword);
    }
    parser->trace(parser->trace_context, parser->trace_line);
}

/// Emits an ERROR line, marked suppressed while error recovery is not reporting to the caller.
static void calculator_parser_emit_error_trace(CalculatorParser *parser, const CalculatorTokenSource *scanner, const char *detail) {
    char full_detail[CALCULATOR_PARSE_ERROR_REASON_SIZE + 16];

    if (parser->error_recovery_shifts_remaining != 0) {
        snprintf(full_detail, sizeof(full_detail), "(suppressed) %s", detail);
        calculator_parser_emit_trace(parser, scanner, "ERROR", full_detail);
        return;
    }
    calculator_parser_emit_trace(parser, scanner, "ERROR", detail);
}

/// Replaces the right hand side of the production on the stacks with the nonterminal on its left hand side, and
/// continues in the state the goto of the uncovered state leads to. Returns false when an allocation failed.
static bool calculator_parser_reduce(CalculatorParser *parser, const CalculatorTokenSource *scanner, size_t production_idx) {
    size_t pop_count = CALCULATOR_POP_COUNT_BY_PRODUCTION[production_idx];
    size_t nonterminal = CALCULATOR_NONTERMINAL_BY_PRODUCTION[production_idx];
    CalculatorParseNode *children = NULL;
    const CalculatorParseNode *right_hand_side = NULL;
    const CalculatorParseNode *last_child;
    const CalculatorParseNode *left;
    CalculatorParseNode node;
    size_t byte_offset = 0;
    size_t byte_length = 0;

    if (parser->trace != NULL) {
        /* The right hand side is still on the node stack here, before it is cut back below. */
        calculator_parser_trace_reduce_payload(parser, (CalculatorNonterminal)nonterminal, pop_count);
        calculator_parser_emit_trace(parser, scanner, "REDUCE", parser->trace_payload);
    }

    parser->state_count -= pop_count;

    if (!calculator_parser_push_state(parser, calculator_goto_state(calculator_parser_current_state(parser), nonterminal))) {
        return false;
    }

    /* The node starts where its first child starts and ends where its last child ends. */
    if (pop_count != 0) {
        right_hand_side = parser->node_stack + parser->node_count - pop_count;
        last_child = &right_hand_side[pop_count - 1];
        byte_offset = right_hand_side[0].byte_offset;
        byte_length = last_child->byte_offset + last_child->byte_length - byte_offset;
    } else if (parser->node_count != 0) {
        /* A production with an empty right hand side goes at the end of the symbol to its left, so that it lies inside
           the node it becomes a child of instead of at the lookahead beyond it. */
        left = &parser->node_stack[parser->node_count - 1];
        byte_offset = left->byte_offset + left->byte_length;
    } else {
        /* Nothing has been parsed yet, so there is no symbol to the left of it. */
        byte_offset = scanner->byte_offset(scanner->context);
    }

    /* The right hand side comes off the node stack and is handed over as the children. */
    if (pop_count > 0) {
        children = calculator_arena_allocate(&parser->arena, pop_count);
        if (children == NULL) {
            parser->out_of_memory = true;
            return false;
        }
        parser->node_count -= pop_count;
        memcpy(children, right_hand_side, pop_count * sizeof(CalculatorParseNode));
    }

    node.symbol.kind = CALCULATOR_SYMBOL_KIND_NONTERMINAL;
    node.symbol.value.nonterminal = (CalculatorNonterminal)nonterminal;
    node.byte_offset = byte_offset;
    node.byte_length = byte_length;
    node.children = children;
    node.child_count = pop_count;
    node.production = (CalculatorProduction)production_idx;
    return calculator_parser_push_node(parser, &node);
}

/// Returns the state on top of the stack of the exploratory parse.
static size_t calculator_parser_exploratory_top(const CalculatorParser *parser) {
    if (parser->exploratory_count != 0) {
        return parser->exploratory_stack[parser->exploratory_count - 1];
    }
    return parser->state_stack[parser->exploratory_stack_base - 1];
}

/// Takes the given number of states off the stack of the exploratory parse. The states it pushed itself go first.
/// Below them, it lowers the base index into state_stack instead of popping, so the stack of the parse is never written
/// and needs no copy.
static void calculator_parser_exploratory_pop(CalculatorParser *parser, size_t count) {
    size_t pushed_count = count < parser->exploratory_count ? count : parser->exploratory_count;
    parser->exploratory_count -= pushed_count;
    parser->exploratory_stack_base -= count - pushed_count;
}

/// Puts the given state on top of the stack of the exploratory parse. Returns false when the allocation failed.
static bool calculator_parser_exploratory_push(CalculatorParser *parser, size_t state) {
    if (!calculator_parser_reserve_exploratory_states(parser, parser->exploratory_count + 1)) {
        return false;
    }
    parser->exploratory_stack[parser->exploratory_count] = state;
    parser->exploratory_count++;
    return true;
}

/// Reports whether the parse from the current stack shifts the terminal of the given column eventually, instead of
/// running into an error. It performs the reductions the terminal leads to on the states alone and without building
/// nodes, so the stacks of the parse are still intact when the terminal turns out to be an error. Reports false as well
/// when an allocation failed, which the parse then reports.
///
/// This is the lookahead correction of section 3.5.2 "Parser" of "PSLR(1): Pseudo-Scannerless Minimal LR(1) for the
/// Deterministic Parsing of Composite Languages" by Joel E. Denny. It deviates from the paper in two ways. The paper
/// runs an exploratory parse as soon as a lookahead arrives, the step runs it only before the first reduction the
/// lookahead decides in a state which is not consistent, because a shift or an error action needs no exploring. And
/// the paper explores on a copy of the stack, while this reads the stack in place, see
/// calculator_parser_exploratory_pop.
static bool calculator_parser_exploratory_parse(CalculatorParser *parser, size_t column) {
    size_t action;
    size_t production_idx;

    parser->exploratory_count = 0;
    parser->exploratory_stack_base = parser->state_count;
    for (;;) {
        action = calculator_action(calculator_parser_exploratory_top(parser), column);
        switch (action & CALCULATOR_ACTION_KIND_MASK) {
        case CALCULATOR_ACTION_KIND_REDUCE:
            production_idx = action >> CALCULATOR_ACTION_KIND_BITS;
            calculator_parser_exploratory_pop(parser, CALCULATOR_POP_COUNT_BY_PRODUCTION[production_idx]);
            if (!calculator_parser_exploratory_push(parser, calculator_goto_state(calculator_parser_exploratory_top(parser), CALCULATOR_NONTERMINAL_BY_PRODUCTION[production_idx]))) {
                return false;
            }
            break;
        case CALCULATOR_ACTION_KIND_SHIFT:
        case CALCULATOR_ACTION_KIND_ACCEPT:
            return true;
        default:
            return false;
        }
    }
}

/// Writes the tokens which the parse from the current stack would shift eventually into the given array, in the order
/// of their columns, and returns their number. It runs an exploratory parse per terminal of the grammar and leaves out
/// the error symbol, which no scanner delivers. More than CALCULATOR_EXPECTED_TOKENS_MAX of them are not returned at
/// all.
static size_t calculator_parser_expected_tokens(CalculatorParser *parser, CalculatorToken expected[CALCULATOR_EXPECTED_TOKENS_MAX]) {
    size_t count = 0;
    size_t column;

    for (column = 0; column < sizeof(CALCULATOR_TOKEN_BY_TERMINAL_COLUMN) / sizeof(CALCULATOR_TOKEN_BY_TERMINAL_COLUMN[0]); column++) {
        if (column == CALCULATOR_NO_TERMINAL_COLUMN || column == CALCULATOR_ERROR_TERMINAL_COLUMN || !calculator_parser_exploratory_parse(parser, column)) {
            continue;
        }
        if (count == CALCULATOR_EXPECTED_TOKENS_MAX) {
            return 0;
        }
        expected[count] = CALCULATOR_TOKEN_BY_TERMINAL_COLUMN[column];
        count++;
    }
    return count;
}

/// Writes into the given buffer a description of the given token as unexpected in place of the expected ones, naming
/// each token by its alias, and cuts it short when it does not fit.
static void calculator_unexpected_token_message(CalculatorToken terminal, const CalculatorToken *expected, size_t expected_count, char *buffer, size_t buffer_size) {
    int written = snprintf(buffer, buffer_size, "unexpected %s", calculator_terminal_name(terminal));
    size_t length = written < 0 ? 0 : (size_t)written;
    size_t idx;

    for (idx = 0; idx < expected_count && length < buffer_size; idx++) {
        const char *separator = idx == 0 ? ", expecting " : " or ";
        written = snprintf(buffer + length, buffer_size - length, "%s%s", separator, calculator_terminal_name(expected[idx]));
        if (written < 0) {
            return;
        }
        length += (size_t)written;
    }
}

/// Raises the error for the given token being unexpected on the current stack, listing the tokens which would have
/// been expected instead.
static void calculator_parser_raise_syntax_error(CalculatorParser *parser, const CalculatorTokenSource *scanner, CalculatorToken terminal, CalculatorParseError *error) {
    CalculatorToken expected[CALCULATOR_EXPECTED_TOKENS_MAX];
    size_t expected_count = calculator_parser_expected_tokens(parser, expected);
    char message[CALCULATOR_PARSE_ERROR_REASON_SIZE];

    calculator_unexpected_token_message(terminal, expected, expected_count, message, sizeof(message));
    if (parser->trace != NULL) {
        calculator_parser_emit_error_trace(parser, scanner, message);
    }
    *error = calculator_parse_error_at(message, CALCULATOR_ERROR_KIND_SYNTAX, scanner);
}

/// What one step of a parse ended with.
typedef enum CalculatorStepResult {
    /// The step performed an action and the parse goes on.
    CALCULATOR_STEP_CONTINUE,

    /// The input was reduced to the start symbol.
    CALCULATOR_STEP_ACCEPT,

    /// The step could not go on, and the error says why.
    CALCULATOR_STEP_FAILED
} CalculatorStepResult;

/// Performs the one action the state on top of the stack takes for the current token.
static CalculatorStepResult calculator_parser_step(CalculatorParser *parser, const CalculatorTokenSource *scanner, CalculatorParseError *error) {
    CalculatorToken terminal = scanner->token(scanner->context);

    /* A token which is no terminal of this grammar takes the default action of the state. */
    size_t column = calculator_terminal_column(terminal);

    size_t state = calculator_parser_current_state(parser);
    size_t action = calculator_action(state, column);
    CalculatorParseNode node;
    char reason[CALCULATOR_PARSE_ERROR_REASON_SIZE];

    switch (action & CALCULATOR_ACTION_KIND_MASK) {
    case CALCULATOR_ACTION_KIND_SHIFT:
        if (parser->trace != NULL) {
            calculator_parser_trace_lexeme_payload(parser, calculator_terminal_trace_name(terminal),
                                                  scanner->lexeme(scanner->context));
            calculator_parser_emit_trace(parser, scanner, "SHIFT", parser->trace_payload);
        }
        if (!calculator_parser_push_state(parser, action >> CALCULATOR_ACTION_KIND_BITS)) {
            return CALCULATOR_STEP_FAILED;
        }
        node.symbol.kind = CALCULATOR_SYMBOL_KIND_TERMINAL;
        node.symbol.value.terminal = terminal;
        node.byte_offset = scanner->byte_offset(scanner->context);
        node.byte_length = scanner->byte_length(scanner->context);
        node.children = NULL;
        node.child_count = 0;
        node.production = CALCULATOR_NO_PRODUCTION;
        if (!calculator_parser_push_node(parser, &node)) {
            return CALCULATOR_STEP_FAILED;
        }
        scanner->next(scanner->context);
        parser->exploratory_parse_passed = false;
        if (parser->error_recovery_shifts_remaining > 0) {
            /* Getting tokens of the input shifted again is what makes the parser trust its position. */
            parser->error_recovery_shifts_remaining--;
        }
        return CALCULATOR_STEP_CONTINUE;
    case CALCULATOR_ACTION_KIND_REDUCE:
        if (!parser->exploratory_parse_passed && CALCULATOR_CONSISTENT_BY_STATE[state] == 0) {
            /* The state reduces because of the lookahead, which might be one it only accepts because states were
               merged or a default reduction was chosen. Reducing on it would leave the state the error belongs to. */
            if (!calculator_parser_exploratory_parse(parser, column)) {
                calculator_parser_raise_syntax_error(parser, scanner, terminal, error);
                return CALCULATOR_STEP_FAILED;
            }
            parser->exploratory_parse_passed = true;
        }
        if (!calculator_parser_reduce(parser, scanner, action >> CALCULATOR_ACTION_KIND_BITS)) {
            return CALCULATOR_STEP_FAILED;
        }
        return CALCULATOR_STEP_CONTINUE;
    case CALCULATOR_ACTION_KIND_ACCEPT:
        if (parser->trace != NULL) {
            calculator_parser_emit_trace(parser, scanner, "ACCEPT", NULL);
        }
        return CALCULATOR_STEP_ACCEPT;
    case CALCULATOR_ACTION_KIND_ERROR:
        calculator_parser_raise_syntax_error(parser, scanner, terminal, error);
        return CALCULATOR_STEP_FAILED;
    default:
        /* Every value the mask selects has a case of its own, so this is never reached. It is here to make the switch
           complete. */
        snprintf(reason, sizeof(reason), "unexpected action %zu in state %zu", action, state);
        *error = calculator_parse_error_at(reason, CALCULATOR_ERROR_KIND_INTERNAL, scanner);
        if (parser->trace != NULL) {
            calculator_parser_emit_error_trace(parser, scanner, reason);
        }
        return CALCULATOR_STEP_FAILED;
    }
}

/// Puts the parser back where it can carry on with the remaining input after a syntax error. Once it reports false,
/// the parse is given up.
///
/// This is the panic mode recovery of section 9 "Error Recovery" of "LR Parsing" by Aho and Johnson, in the shape
/// which section 7 "Error Handling" of the yacc report describes: the parser pops its stack until it reaches a state
/// which can shift the error symbol - a place the grammar marked as one to resume at - and shifts the symbol there.
/// Everything the popped states had parsed is discarded with them.
///
/// The token which caused the error is kept for the resumed state to look at, because that state is usually waiting
/// for exactly it: in a production like "{" @error "}" it is the closing brace which ends the recovery. Only when the
/// parse fails on that very same token again is the token discarded, which is what an untouched countdown of tokens to
/// shift tells us. Popping and discarding in the same handler is what guarantees progress: every round of recovery
/// either gets the parse going again or consumes one token of the input, so a parse cannot get stuck between the two.
static bool calculator_parser_recover_from_error(CalculatorParser *parser, const CalculatorTokenSource *scanner) {
    CalculatorParseNode node;
    const CalculatorParseNode *left;
    const CalculatorParseNode *dropped_node;
    size_t next_state;

    /* The error node this round ends with runs from the start of what the round throws away to the point where it
       resumes, so the span starts out empty at the token the parser stopped on and grows to the front with every node
       the round pops. */
    size_t dropped_offset = scanner->byte_offset(scanner->context);
    size_t dropped_length = 0;

    if (parser->error_recovery_shifts_remaining == CALCULATOR_ERROR_RECOVERY_SHIFTS) {
        /* Nothing was shifted since the last error, so the parser is failing on the token it already failed on. */
        if (scanner->token(scanner->context) == CALCULATOR_TOKEN_END_TOKEN) {
            /* The end of input is the one token which cannot be discarded. */
            if (parser->trace != NULL) {
                calculator_parser_emit_trace(parser, scanner, "FAIL", NULL);
            }
            return false;
        }
        if (parser->trace != NULL) {
            calculator_parser_trace_lexeme_payload(parser, calculator_terminal_trace_name(scanner->token(scanner->context)),
                                                  scanner->lexeme(scanner->context));
            calculator_parser_emit_trace(parser, scanner, "DISCARD", parser->trace_payload);
        }
        /* The discarded token is thrown away as well, so the span reaches to its end and not to its start. */
        dropped_length = scanner->byte_length(scanner->context);
        scanner->next(scanner->context);
        parser->exploratory_parse_passed = false;
    }
    parser->error_recovery_shifts_remaining = CALCULATOR_ERROR_RECOVERY_SHIFTS;

    for (;;) {
        if (calculator_error_shift_state(calculator_parser_current_state(parser), &next_state)) {
            if (parser->trace != NULL) {
                calculator_parser_emit_trace(parser, scanner, "RESYNC", NULL);
            }
            if (dropped_length == 0 && parser->node_count != 0) {
                /* The round threw no bytes away, so its node goes at the end of the symbol to its left, where a
                   production with an empty right hand side goes, and not at the lookahead beyond it. */
                left = &parser->node_stack[parser->node_count - 1];
                dropped_offset = left->byte_offset + left->byte_length;
            }
            /* Shift the error symbol. Its node covers what this round dropped. */
            if (!calculator_parser_push_state(parser, next_state)) {
                return false;
            }
            parser->exploratory_parse_passed = false;
            node.symbol.kind = CALCULATOR_SYMBOL_KIND_TERMINAL;
            node.symbol.value.terminal = CALCULATOR_TOKEN_ERROR_TOKEN;
            node.byte_offset = dropped_offset;
            node.byte_length = dropped_length;
            node.children = NULL;
            node.child_count = 0;
            node.production = CALCULATOR_NO_PRODUCTION;
            return calculator_parser_push_node(parser, &node);
        }
        if (parser->state_count == 1) {
            /* Only the state the parse started in is left and it cannot shift the error symbol either. */
            if (parser->trace != NULL) {
                calculator_parser_emit_trace(parser, scanner, "FAIL", NULL);
            }
            return false;
        }
        if (parser->trace != NULL) {
            calculator_parser_emit_trace(parser, scanner, "POP",
                                         calculator_symbol_trace_name(&parser->node_stack[parser->node_count - 1].symbol));
        }
        /* The state cannot resume here, so it is dropped together with what it had parsed. One state carries one node,
           so dropping one drops one. */
        dropped_node = &parser->node_stack[parser->node_count - 1];
        dropped_length = dropped_offset + dropped_length - dropped_node->byte_offset;
        dropped_offset = dropped_node->byte_offset;
        parser->state_count--;
        parser->node_count--;
    }
}

void calculator_parser_init(CalculatorParser *parser) {
    parser->trace = NULL;
    parser->trace_context = NULL;
    parser->state_stack = NULL;
    parser->state_count = 0;
    parser->state_capacity = 0;
    parser->node_stack = NULL;
    parser->node_count = 0;
    parser->node_capacity = 0;
    parser->errors = NULL;
    parser->error_count = 0;
    parser->error_capacity = 0;
    parser->arena = NULL;
    parser->error_recovery_shifts_remaining = 0;
    parser->out_of_memory = false;
    parser->exploratory_parse_passed = false;
    parser->exploratory_stack = NULL;
    parser->exploratory_count = 0;
    parser->exploratory_capacity = 0;
    parser->exploratory_stack_base = 0;
}

void calculator_parser_free(CalculatorParser *parser) {
    free(parser->state_stack);
    free(parser->node_stack);
    free(parser->exploratory_stack);
    calculator_parser_init(parser);
}

void calculator_parse_result_free(CalculatorParseResult *result) {
    calculator_arena_free(result->arena);
    free(result->errors);
    result->tree = NULL;
    result->errors = NULL;
    result->error_count = 0;
    result->arena = NULL;
}

CalculatorParseResult calculator_parser_parse(CalculatorParser *parser, const CalculatorTokenSource *scanner) {
    CalculatorParseResult result;
    CalculatorParseError failure;
    CalculatorStepResult step_result;

    result.tree = NULL;
    result.errors = NULL;
    result.error_count = 0;
    result.arena = NULL;

    parser->state_count = 0;
    parser->node_count = 0;
    parser->errors = NULL;
    parser->error_count = 0;
    parser->error_capacity = 0;
    parser->arena = NULL;
    parser->error_recovery_shifts_remaining = 0;
    parser->out_of_memory = false;
    parser->exploratory_parse_passed = false;

    /* One error slot up front, so that running out of memory later can always be reported. */
    if (!calculator_parser_reserve_errors(parser, 1) || !calculator_parser_push_state(parser, 0)) {
        free(parser->errors);
        parser->errors = NULL;
        parser->error_capacity = 0;
        return result;
    }

    /* A scanner with no tokens at all reports false right away. That is not an error: the token is the end of input
       either way, and whether a parse of nothing but that is legal is for the table to decide. */
    scanner->next(scanner->context);

    for (;;) {
        step_result = calculator_parser_step(parser, scanner, &failure);

        if (parser->out_of_memory) {
            calculator_parser_report_out_of_memory(parser, scanner);
            break;
        }
        if (step_result == CALCULATOR_STEP_CONTINUE) {
            continue;
        }
        if (step_result == CALCULATOR_STEP_ACCEPT) {
            /* What is left on the node stack is the start symbol, which is the root of the tree. */
            if (parser->node_count > 0) {
                CalculatorParseNode *root = calculator_arena_allocate(&parser->arena, 1);
                if (root == NULL) {
                    parser->out_of_memory = true;
                    calculator_parser_report_out_of_memory(parser, scanner);
                    break;
                }
                *root = parser->node_stack[0];
                result.tree = root;
            }
            break;
        }

        /* The step neither went on nor accepted, so it failed and carries the error. */
        if (failure.kind != CALCULATOR_ERROR_KIND_SYNTAX) {
            /* Only an error in the input can be recovered from. */
            if (!calculator_parser_append_error(parser, &failure)) {
                calculator_parser_report_out_of_memory(parser, scanner);
            }
            break;
        }
        if (parser->error_recovery_shifts_remaining == 0) {
            /* While recovering, the parser is not in sync with the input, so the errors it runs into there follow from
               the one already reported. */
            if (!calculator_parser_append_error(parser, &failure)) {
                calculator_parser_report_out_of_memory(parser, scanner);
                break;
            }
        }
        if (!calculator_parser_recover_from_error(parser, scanner)) {
            if (parser->out_of_memory) {
                calculator_parser_report_out_of_memory(parser, scanner);
            }
            break;
        }
    }

    result.errors = parser->errors;
    result.error_count = parser->error_count;
    result.arena = parser->arena;

    if (result.tree == NULL) {
        /* Nothing references the nodes the parse had built, so they go now rather than with the result. */
        calculator_arena_free(result.arena);
        result.arena = NULL;
    }

    parser->errors = NULL;
    parser->error_count = 0;
    parser->error_capacity = 0;
    parser->arena = NULL;
    return result;
}

#endif  /* CALCULATOR_PARSER_IMPLEMENTATION_ONCE */
#endif  /* CALCULATOR_PARSER_IMPLEMENTATION */
