// <auto-generated/>
// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

// The nullable context is stated here rather than taken from the project, so that the annotations below mean the same
// thing whatever the project enables.
#nullable enable

using System;
using System.Collections.Generic;

namespace Calculator.Parser;

/// <summary>Every nonterminal symbol of the grammar.</summary>
public enum Nonterminal
{
    /// <summary>
    /// The start symbol the generator adds around the one the grammar declares. Reaching it accepts the input.
    /// </summary>
    AcceptNonterminal = 0,

    NonterminalExpression = 1,
}

/// <summary>Extends <see cref="Nonterminal"/> with the name the grammar spells it with.</summary>
public static class NonterminalExtensions
{
    /// <summary>Returns the name of the nonterminal, as the grammar spells it.</summary>
    /// <param name="nonterminal">The nonterminal to name.</param>
    public static string ToDisplayString(this Nonterminal nonterminal) => nonterminal switch
    {
        Nonterminal.AcceptNonterminal => "$accept",
        Nonterminal.NonterminalExpression => "expression",
        _ => "unknown",
    };
}

/// <summary>
/// A terminal or a nonterminal. The most significant bit of the low 16 is set when the symbol holds a nonterminal,
/// which limits either index to 32767.
/// </summary>
public readonly struct ParseSymbol : IEquatable<ParseSymbol>
{
    /// <summary>The bit which is set when the symbol holds a nonterminal.</summary>
    private const int NonterminalBit = 1 << 15;

    /// <summary>Selects the index out of the symbol.</summary>
    private const int SymbolMask = NonterminalBit - 1;

    /// <summary>The terminal or nonterminal index, with <see cref="NonterminalBit"/> telling the two apart.</summary>
    private readonly int _value;

    /// <param name="value">The packed index.</param>
    private ParseSymbol(int value) => _value = value;

    /// <summary>Returns the symbol for a terminal.</summary>
    /// <param name="terminal">The terminal to pack.</param>
    public static ParseSymbol NewTerminal(Token terminal) => new((int)terminal);

    /// <summary>Returns the symbol for a nonterminal.</summary>
    /// <param name="nonterminal">The nonterminal to pack.</param>
    public static ParseSymbol NewNonterminal(Nonterminal nonterminal) => new(NonterminalBit | (int)nonterminal);

    /// <summary>Reports whether the symbol holds a terminal, which it then writes to the parameter.</summary>
    /// <param name="terminal">The terminal the symbol holds, meaningless when it holds a nonterminal.</param>
    public bool TryGetTerminal(out Token terminal)
    {
        terminal = (Token)(_value & SymbolMask);
        return (_value & NonterminalBit) == 0;
    }

    /// <summary>Reports whether the symbol holds a nonterminal, which it then writes to the parameter.</summary>
    /// <param name="nonterminal">The nonterminal the symbol holds, meaningless when it holds a terminal.</param>
    public bool TryGetNonterminal(out Nonterminal nonterminal)
    {
        nonterminal = (Nonterminal)(_value & SymbolMask);
        return (_value & NonterminalBit) != 0;
    }

    /// <summary>Reports whether the other symbol stands for the same terminal or nonterminal.</summary>
    /// <param name="other">The symbol to compare with.</param>
    public bool Equals(ParseSymbol other) => _value == other._value;

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is ParseSymbol other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode() => _value;

    /// <summary>Reports whether the two symbols stand for the same terminal or nonterminal.</summary>
    /// <param name="left">The symbol on the left of the operator.</param>
    /// <param name="right">The symbol on the right of the operator.</param>
    public static bool operator ==(ParseSymbol left, ParseSymbol right) => left.Equals(right);

    /// <summary>Reports whether the two symbols stand for different terminals or nonterminals.</summary>
    /// <param name="left">The symbol on the left of the operator.</param>
    /// <param name="right">The symbol on the right of the operator.</param>
    public static bool operator !=(ParseSymbol left, ParseSymbol right) => !left.Equals(right);

    /// <summary>Returns the name of the symbol, as the grammar spells it.</summary>
    public override string ToString()
    {
        if (TryGetTerminal(out Token terminal))
        {
            return $"terminal {terminal.ToDisplayString()}";
        }

        TryGetNonterminal(out Nonterminal nonterminal);
        return $"nonterminal {nonterminal.ToDisplayString()}";
    }
}

/// <summary>A single node of the parse tree.</summary>
public sealed class ParseNode
{
    /// <summary>Creates a node for the given symbol.</summary>
    /// <param name="symbol">The terminal or nonterminal the node stands for.</param>
    /// <param name="lexeme">The bytes of the terminal, empty for a nonterminal.</param>
    /// <param name="children">The nodes of the right hand side of the production, empty for a terminal.</param>
    public ParseNode(ParseSymbol symbol, ReadOnlyMemory<byte> lexeme, IReadOnlyList<ParseNode> children)
    {
        Symbol = symbol;
        Lexeme = lexeme;
        Children = children;
    }

    /// <summary>
    /// The terminal or nonterminal this node stands for, see <see cref="ParseSymbol.TryGetTerminal"/> and
    /// <see cref="ParseSymbol.TryGetNonterminal"/>.
    /// </summary>
    public ParseSymbol Symbol { get; }

    /// <summary>
    /// The bytes of the terminal, as a view into the source rather than a copy of it. Empty for a nonterminal and for
    /// the error symbol, which no input produced.
    /// </summary>
    public ReadOnlyMemory<byte> Lexeme { get; }

    /// <summary>
    /// The nodes of the right hand side of the production which was reduced to this node. Empty for a terminal.
    /// </summary>
    public IReadOnlyList<ParseNode> Children { get; }
}

/// <summary>
/// A single parse error. Parse errors are returned by <see cref="Parser.Parse"/> rather than thrown, and this is no
/// Exception, so reporting many of them costs no stack traces. Throw one with
/// <c>new InvalidOperationException(parseError.Message)</c>.
/// </summary>
public sealed class ParseError
{
    /// <summary>Creates an error which stands at the position the given scanner is at.</summary>
    /// <param name="reason">What is wrong, without the position in front of it.</param>
    /// <param name="isSyntaxError">True for an error in the input, false for a defect of the parser itself.</param>
    /// <param name="scanner">The scanner the token and its position are taken from.</param>
    public ParseError(string reason, bool isSyntaxError, IScanner scanner)
    {
        Reason = reason;
        IsSyntaxError = isSyntaxError;

        Token = scanner.Token;
        ByteOffset = scanner.ByteOffset;
        Line = scanner.Line;
        Column = scanner.Column;
        Lexeme = scanner.Lexeme;
        FilePath = scanner.FilePath;
    }

    /// <summary>What is wrong, without the position in front of it.</summary>
    public string Reason { get; }

    /// <summary>
    /// True for an error in the input, false for a defect of the parser itself, which ends the parse.
    /// </summary>
    public bool IsSyntaxError { get; }

    /// <summary>The token the parse stopped on.</summary>
    public Token Token { get; }

    /// <summary>Start of that token in bytes from the start of the source.</summary>
    public int ByteOffset { get; }

    /// <summary>Line that token starts on, counted from one.</summary>
    public int Line { get; }

    /// <summary>Column that token starts on, counted from one.</summary>
    public int Column { get; }

    /// <summary>The bytes of that token.</summary>
    public ReadOnlyMemory<byte> Lexeme { get; }

    /// <summary>The file path the scanner was given.</summary>
    public string FilePath { get; }

    /// <summary>
    /// The error as one line of text, in the file:line:column: reason form editors and build tools recognize.
    /// </summary>
    public string Message => $"{FilePath}:{Line}:{Column}: {Reason}";

    /// <inheritdoc/>
    public override string ToString() => $"ParseError: {Message}";
}

/// <summary>What a parse returns.</summary>
public sealed class ParseResult
{
    /// <summary>Creates the result of a parse.</summary>
    /// <param name="tree">The parse tree, or null when the parse could not be finished.</param>
    /// <param name="errors">Every error the parse reported, in the order they were found.</param>
    public ParseResult(ParseNode? tree, IReadOnlyList<ParseError> errors)
    {
        Tree = tree;
        Errors = errors;
    }

    /// <summary>The parse tree, or null when the parse could not be finished.</summary>
    public ParseNode? Tree { get; }

    /// <summary>Every error the parse reported, in the order they were found.</summary>
    public IReadOnlyList<ParseError> Errors { get; }
}

/// <summary>Parses the tokens of a scanner into a parse tree.</summary>
public sealed class Parser
{
    /// <summary>What one step of a parse ended with.</summary>
    private enum StepOutcome
    {
        /// <summary>The parse goes on.</summary>
        Continue,

        /// <summary>The input was reduced to the start symbol.</summary>
        Accept,

        /// <summary>The parse cannot go on, and the step reported why.</summary>
        Failed,
    }

    /// <summary>
    /// How many tokens have to be shifted after a syntax error before errors are reported again. Suppressing the
    /// errors in between keeps one mistake in the input from producing an avalanche of messages which all follow from
    /// it.
    /// </summary>
    private const int ErrorRecoveryShifts = 3;

    /// <summary>What <see cref="ErrorShiftState"/> returns for a state which cannot shift the error symbol.</summary>
    private const int NoErrorShiftState = -1;

    // The parse table is held in lookup tables. A token is translated into the column of the action table which holds
    // the decisions for it, and the rows of that table are displaced into a single array so that the entries of one
    // row fall into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan
    // and Yao. The gotos are held the same way, with the nonterminal as the column.
    //
    // The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the
    // action table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the
    // tables.
    //
    // The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
    // range check of its own.

    /// <summary>
    /// Number of low bits of an action which hold what it does. The value it carries sits above them.
    /// </summary>
    private const int ActionKindBits = 2;

    /// <summary>Selects out of an action what it does.</summary>
    private const int ActionKindMask = 3;

    /// <summary>Shifts the terminal and continues in the state the action carries.</summary>
    private const int ActionKindShift = 0;

    /// <summary>Reduces by the production the action carries.</summary>
    private const int ActionKindReduce = 1;

    /// <summary>Ends the parse successfully, the input having been reduced to the start symbol.</summary>
    private const int ActionKindAccept = 2;

    /// <summary>Rejects the terminal as a syntax error.</summary>
    private const int ActionKindError = 3;

    /// <summary>
    /// The column a token gets which is no terminal of this grammar. No state has an entry in it, so a lookup falls
    /// through to the default action of the state.
    /// </summary>
    private const int NoTerminalColumn = 0;

    /// <summary>
    /// The column holding the shifts of the error symbol, which is where the recovery reads the state to resume in.
    /// </summary>
    private const int ErrorTerminalColumn = 0;

    /// <summary>
    /// Translates a token into the column of the action table which holds the decisions for it. A token the grammar
    /// does not have is not named in the entries and keeps the NoTerminalColumn every unnamed index holds.
    /// </summary>
    private static readonly byte[] TerminalColumnByToken = NewTerminalColumnByToken();

    /// <summary>Maps a state to the displacement of its row within <see cref="ActionNext"/>.</summary>
    private static readonly byte[] ActionBase =
    {
        9, 1, 9, 9, 0, 1, 4, 1, 9, 9, 9, 9, 1, 12, 12, 1,
        1,
    };

    /// <summary>
    /// Holds the action of every entry. The action a state has for a column lives at ActionBase[state] + column, but
    /// only if <see cref="ActionCheck"/> confirms the cell belongs to that column.
    /// </summary>
    private static readonly byte[] ActionNext =
    {
        0, 28, 0, 0, 32, 36, 40, 44, 32, 36, 40, 44, 4, 48, 8, 0,
        0, 12, 40, 44, 0, 0, 0,
    };

    /// <summary>
    /// Holds the column every cell of <see cref="ActionNext"/> belongs to. A cell no state occupies holds
    /// 11, which is one past the highest column in use and can never be asked for.
    /// </summary>
    private static readonly byte[] ActionCheck =
    {
        11, 1, 11, 11, 4, 5, 6, 7, 4, 5, 6, 7, 3, 9, 5, 11,
        11, 8, 6, 7, 11, 11, 11,
    };

    /// <summary>
    /// Holds the action a state takes for every column it has no entry of its own for. A state which has none carries
    /// the error action.
    /// </summary>
    private static readonly byte[] DefaultActionByState =
    {
        3, 5, 3, 3, 3, 25, 3, 2, 3, 3, 3, 3, 29, 9, 13, 17,
        21,
    };

    /// <summary>Maps a state to the displacement of its row within <see cref="GotoNext"/>.</summary>
    private static readonly byte[] GotoBase =
    {
        6, 6, 0, 1, 6, 6, 6, 6, 2, 3, 4, 5, 6, 6, 6, 6,
        6,
    };

    /// <summary>
    /// Holds the state a goto leads to. The goto a state has for a nonterminal lives at GotoBase[state] + nonterminal,
    /// but only if <see cref="GotoCheck"/> confirms the cell belongs to that nonterminal.
    /// </summary>
    private static readonly byte[] GotoNext =
    {
        0, 5, 6, 13, 14, 15, 16, 0,
    };

    /// <summary>
    /// Holds the nonterminal every cell of <see cref="GotoNext"/> belongs to. A cell no state occupies holds
    /// 2, which is one past the highest nonterminal and can never be asked for.
    /// </summary>
    private static readonly byte[] GotoCheck =
    {
        2, 1, 1, 1, 1, 1, 1, 2,
    };

    /// <summary>
    /// Holds the state a goto on a nonterminal leads to for every state <see cref="GotoNext"/> has no entry for.
    /// </summary>
    private static readonly byte[] DefaultGotoByNonterminal =
    {
        0, 4,
    };

    /// <summary>
    /// Holds how many symbols a reduction takes off the stacks, which is the length of the right hand side.
    /// </summary>
    private static readonly byte[] PopCountByProduction =
    {
        2, 1, 3, 3, 3, 3, 2, 3,
    };

    /// <summary>Holds the nonterminal on the left hand side of a production.</summary>
    private static readonly byte[] NonterminalByProduction =
    {
        0, 1, 1, 1, 1, 1, 1, 1,
    };

    /// <summary>The scanner of the running parse.</summary>
    private IScanner _scanner = null!;

    /// <summary>The states of the running parse, the current one on top.</summary>
    private readonly List<int> _stateStack = new();

    /// <summary>One node per symbol shifted or reduced so far.</summary>
    private readonly List<ParseNode> _nodeStack = new();

    /// <summary>The errors of the running parse, which <see cref="Parse"/> returns next to the tree.</summary>
    private readonly List<ParseError> _errors = new();

    /// <summary>
    /// Counts down the tokens which still have to be shifted before syntax errors are reported again. Zero while the
    /// parser is in sync with the input.
    /// </summary>
    private int _errorRecoveryShiftsRemaining;

    /// <summary>
    /// Parses the tokens the scanner delivers. Can be called more than once, with a different scanner each time.
    ///
    /// When the grammar marks places to resume at with the error symbol, a syntax error does not end the parse: the
    /// result then holds both the tree parsed so far, with a node for the error symbol at every place resumed at, and
    /// every error found. The tree is null when the parse could not be carried to its end.
    /// </summary>
    /// <param name="scanner">The scanner to take the tokens from.</param>
    public ParseResult Parse(IScanner scanner)
    {
        _scanner = scanner;

        // The stacks are emptied rather than replaced, so a parser hands out the room it already has to the parse
        // after it instead of allocating anew.
        _stateStack.Clear();
        _stateStack.Add(0);
        _nodeStack.Clear();
        _errors.Clear();
        _errorRecoveryShiftsRemaining = 0;

        // A source with no tokens at all reports false right away. That is not an error: the token is the end of input
        // either way, and whether a parse of nothing but that is legal is for the table to decide.
        _scanner.Next();

        while (true)
        {
            StepOutcome outcome = Step(out ParseError? error);
            if (outcome == StepOutcome.Accept)
            {
                // The errors are copied out, because the list they were collected in is handed to the parse after
                // this one.
                return new ParseResult(_nodeStack[0], _errors.ToArray());
            }
            if (outcome == StepOutcome.Continue)
            {
                continue;
            }

            // Only a failed step carries an error.
            ParseError failure = error!;
            if (!failure.IsSyntaxError)
            {
                // Only an error in the input can be recovered from.
                _errors.Add(failure);
                return new ParseResult(null, _errors.ToArray());
            }
            if (_errorRecoveryShiftsRemaining == 0)
            {
                // While recovering, the parser is not in sync with the input, so the errors it runs into there follow
                // from the one already reported.
                _errors.Add(failure);
            }
            if (!RecoverFromError())
            {
                return new ParseResult(null, _errors.ToArray());
            }
        }
    }

    /// <summary>
    /// Builds <see cref="TerminalColumnByToken"/> from pairs of token and column, sized to the highest token named in
    /// them.
    /// </summary>
    private static byte[] NewTerminalColumnByToken()
    {
        (Token Token, byte Column)[] entries =
        {
            (Token.EndToken, 1),
            (Token.TokenWhitespace, 2),
            (Token.TokenInteger, 3),
            (Token.TokenPlus, 4),
            (Token.TokenMinus, 5),
            (Token.TokenMultiply, 6),
            (Token.TokenDivide, 7),
            (Token.TokenLparen, 8),
            (Token.TokenRparen, 9),
            (Token.TokenUminus, 10),
        };

        int length = 0;
        foreach ((Token token, _) in entries)
        {
            length = Math.Max(length, (int)token + 1);
        }

        byte[] result = new byte[length];
        foreach ((Token token, byte column) in entries)
        {
            result[(int)token] = column;
        }
        return result;
    }

    /// <summary>
    /// Returns the column of the action table which holds the decisions for the given token. A token the grammar does
    /// not have, and one outside the range the scanner promises, both get <see cref="NoTerminalColumn"/>.
    /// </summary>
    /// <param name="terminal">The token to look up.</param>
    private static int TerminalColumn(Token terminal)
    {
        if (0 <= (int)terminal && (int)terminal < TerminalColumnByToken.Length)
        {
            return TerminalColumnByToken[(int)terminal];
        }
        return NoTerminalColumn;
    }

    /// <summary>
    /// Returns the state to continue in when the error symbol is shifted in the given state, or
    /// <see cref="NoErrorShiftState"/> when the state cannot shift it. The states which can are the places the grammar
    /// marked to resume at after a syntax error.
    ///
    /// The default action of the state is deliberately not consulted, because only an entry the state has of its own
    /// is a place to resume at.
    /// </summary>
    /// <param name="state">The state to look up.</param>
    private static int ErrorShiftState(int state)
    {
        int cellIdx = ActionBase[state] + ErrorTerminalColumn;
        if (ActionCheck[cellIdx] != ErrorTerminalColumn)
        {
            return NoErrorShiftState;
        }

        int action = ActionNext[cellIdx];
        if ((action & ActionKindMask) != ActionKindShift)
        {
            return NoErrorShiftState;
        }
        return action >> ActionKindBits;
    }

    /// <summary>
    /// Performs the one action the state on top of the stack takes for the current token. The error is set only when
    /// the parse cannot go on.
    /// </summary>
    /// <param name="error">Why the parse cannot go on, null while it goes on.</param>
    private StepOutcome Step(out ParseError? error)
    {
        error = null;
        Token terminal = _scanner.Token;

        // A token which is no terminal of this grammar takes the default action of the state.
        int column = TerminalColumn(terminal);

        int state = CurrentState();
        int cellIdx = ActionBase[state] + column;
        int action = DefaultActionByState[state];
        if (ActionCheck[cellIdx] == column)
        {
            // An entry the state has of its own beats its default action, which is what keeps a token the grammar
            // rejects on purpose an error even in a state which reduces on everything else.
            action = ActionNext[cellIdx];
        }

        switch (action & ActionKindMask)
        {
            case ActionKindShift:
                _stateStack.Add(action >> ActionKindBits);
                _nodeStack.Add(new ParseNode(
                    ParseSymbol.NewTerminal(terminal), _scanner.Lexeme, Array.Empty<ParseNode>()));
                _scanner.Next();
                if (_errorRecoveryShiftsRemaining > 0)
                {
                    // Getting tokens of the input shifted again is what makes the parser trust its position.
                    _errorRecoveryShiftsRemaining--;
                }
                return StepOutcome.Continue;
            case ActionKindReduce:
                Reduce(action >> ActionKindBits);
                return StepOutcome.Continue;
            case ActionKindAccept:
                return StepOutcome.Accept;
            case ActionKindError:
                error = new ParseError($"unexpected token {terminal.ToDisplayString()}", true, _scanner);
                return StepOutcome.Failed;
            default:
                error = new ParseError($"unexpected action {action} in state {state}", false, _scanner);
                return StepOutcome.Failed;
        }
    }

    /// <summary>
    /// Replaces the right hand side of the production on the stacks with the nonterminal on its left hand side, and
    /// continues in the state the goto of the uncovered state leads to.
    /// </summary>
    /// <param name="productionIdx">The production to reduce by.</param>
    private void Reduce(int productionIdx)
    {
        int popCount = PopCountByProduction[productionIdx];
        int nonterminal = NonterminalByProduction[productionIdx];

        _stateStack.RemoveRange(_stateStack.Count - popCount, popCount);

        int state = CurrentState();
        // A state without a goto of its own on the nonterminal goes where most states go with it. A state which a
        // reduction uncovers always has one, so there is no case for a nonterminal missing from both.
        int gotoState = DefaultGotoByNonterminal[nonterminal];
        int cellIdx = GotoBase[state] + nonterminal;
        if (GotoCheck[cellIdx] == nonterminal)
        {
            gotoState = GotoNext[cellIdx];
        }
        _stateStack.Add(gotoState);

        // The right hand side comes off the node stack and is handed over as the children. An empty right hand side
        // takes nothing and shares the one empty array instead of allocating one of its own.
        ParseNode[] children = popCount == 0 ? Array.Empty<ParseNode>() : new ParseNode[popCount];
        _nodeStack.CopyTo(_nodeStack.Count - popCount, children, 0, popCount);
        _nodeStack.RemoveRange(_nodeStack.Count - popCount, popCount);
        _nodeStack.Add(new ParseNode(
            ParseSymbol.NewNonterminal((Nonterminal)nonterminal), default, children));
    }

    /// <summary>
    /// Puts the parser back where it can carry on with the remaining input after a syntax error. Once it reports
    /// false, the parse is given up.
    ///
    /// This is panic mode recovery as described in section 7 "Error Handling" of the yacc report: the stack is popped
    /// until a state is reached which can shift the error symbol, and the symbol is shifted there. Everything the
    /// popped states had parsed is discarded with them. The token which caused the error is kept for the resumed state
    /// to look at, and only discarded when the parse fails on it a second time.
    /// </summary>
    private bool RecoverFromError()
    {
        if (_errorRecoveryShiftsRemaining == ErrorRecoveryShifts)
        {
            // Nothing was shifted since the last error, so the parser is failing on the token it already failed on.
            if (_scanner.Token == Token.EndToken)
            {
                // The end of input is the one token which cannot be discarded.
                return false;
            }
            _scanner.Next();
        }
        _errorRecoveryShiftsRemaining = ErrorRecoveryShifts;

        while (true)
        {
            int nextState = ErrorShiftState(CurrentState());
            if (nextState != NoErrorShiftState)
            {
                // Shift the error symbol. Its node stands for the dropped part of the input and has no lexeme.
                _stateStack.Add(nextState);
                _nodeStack.Add(new ParseNode(
                    ParseSymbol.NewTerminal(Token.ErrorToken), default, Array.Empty<ParseNode>()));
                return true;
            }
            if (_stateStack.Count == 1)
            {
                // Only the state the parse started in is left and it cannot shift the error symbol either.
                return false;
            }
            // The state cannot resume here, so it is dropped together with what it had parsed. One state carries one
            // node, so dropping one drops one.
            _stateStack.RemoveAt(_stateStack.Count - 1);
            _nodeStack.RemoveAt(_nodeStack.Count - 1);
        }
    }

    /// <summary>Returns the state on top of the stack, which is the one the parse is in.</summary>
    private int CurrentState() => _stateStack[^1];
}
