// <auto-generated/>
// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

// The nullable context is stated here rather than taken from the project, so that the annotations below mean the same
// thing whatever the project enables.
#nullable enable

using System;

namespace Calculator.Parser;

/// <summary>Every terminal symbol this scanner knows.</summary>
public enum Token
{
    /// <summary>No token was found.</summary>
    InvalidToken = 0,

    /// <summary>The end of the source was reached.</summary>
    EndToken = 1,

    /// <summary>The symbol a grammar marks its error recovery points with. No input ever produces it.</summary>
    ErrorToken = 2,

    TokenWhitespace = 3,
    TokenInteger = 4,
    TokenPlus = 5,
    TokenMinus = 6,
    TokenMultiply = 7,
    TokenDivide = 8,
    TokenLparen = 9,
    TokenRparen = 10,
    TokenUminus = 11,
}

/// <summary>Extends <see cref="Token"/> with the name the grammar spells it with.</summary>
public static class TokenExtensions
{
    /// <summary>Returns the name of the token, as the grammar spells it.</summary>
    /// <param name="token">The token to name.</param>
    public static string ToDisplayString(this Token token) => token switch
    {
        Token.InvalidToken => "invalid token",
        Token.EndToken => "end token",
        Token.ErrorToken => "error token",
        Token.TokenWhitespace => "WHITESPACE",
        Token.TokenInteger => "INTEGER",
        Token.TokenPlus => "PLUS",
        Token.TokenMinus => "MINUS",
        Token.TokenMultiply => "MULTIPLY",
        Token.TokenDivide => "DIVIDE",
        Token.TokenLparen => "LPAREN",
        Token.TokenRparen => "RPAREN",
        Token.TokenUminus => "UMINUS",
        _ => "unknown",
    };

    /// <summary>
    /// Reports whether the grammar marked the token for skipping, which is what the token skipper drops.
    /// </summary>
    /// <param name="token">The token to test.</param>
    public static bool IsSkipped(this Token token) => token switch
    {
        Token.TokenWhitespace => true,
        _ => false,
    };
}

/// <summary>What a scanner offers. Both <see cref="Scanner"/> and <see cref="TokenSkipper"/> implement it.</summary>
public interface ITokenSource
{
    /// <summary>The current token.</summary>
    Token Token { get; }

    /// <summary>
    /// The start of the token in bytes from the start of the source. After <see cref="Next"/> returned false it is the
    /// offset one past the last byte.
    /// </summary>
    int ByteOffset { get; }

    /// <summary>The line the token starts on, counted from one.</summary>
    int Line { get; }

    /// <summary>The column the token starts on, counted from one.</summary>
    int Column { get; }

    /// <summary>The bytes of the token, as a view into the source rather than a copy of it.</summary>
    ReadOnlyMemory<byte> Lexeme { get; }

    /// <summary>The file path the scanner was given.</summary>
    string FilePath { get; }

    /// <summary>
    /// Scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
    /// changed.
    /// </summary>
    /// <param name="source">The bytes to scan.</param>
    /// <param name="offset">The byte offset to start at.</param>
    void Reset(ReadOnlyMemory<byte> source, int offset);

    /// <summary>Advances to the next token. Returns false when the source holds no such token any more.</summary>
    bool Next();
}

/// <summary>
/// Wraps a scanner and skips the tokens marked for skipping, which are usually whitespace and comments. It offers the
/// same members as <see cref="Scanner"/>.
/// </summary>
public sealed class TokenSkipper : ITokenSource
{
    /// <summary>The wrapped scanner.</summary>
    private readonly ITokenSource _scanner;

    /// <summary>Creates a skipper which hands on the tokens of the given scanner.</summary>
    /// <param name="scanner">The scanner to take the tokens from.</param>
    public TokenSkipper(ITokenSource scanner) => _scanner = scanner;

    /// <inheritdoc/>
    public Token Token => _scanner.Token;

    /// <inheritdoc/>
    public int ByteOffset => _scanner.ByteOffset;

    /// <inheritdoc/>
    public int Line => _scanner.Line;

    /// <inheritdoc/>
    public int Column => _scanner.Column;

    /// <inheritdoc/>
    public ReadOnlyMemory<byte> Lexeme => _scanner.Lexeme;

    /// <inheritdoc/>
    public string FilePath => _scanner.FilePath;

    /// <inheritdoc/>
    public void Reset(ReadOnlyMemory<byte> source, int offset) => _scanner.Reset(source, offset);

    /// <summary>
    /// Advances to the next token which is not marked for skipping. Returns false when the source holds no such token
    /// any more.
    /// </summary>
    public bool Next()
    {
        while (_scanner.Next())
        {
            if (!_scanner.Token.IsSkipped())
            {
                return true;
            }
        }
        return false;
    }
}

/// <summary>Turns the bytes of a source into tokens.</summary>
public sealed class Scanner : ITokenSource
{
    // The automaton is held in lookup tables. An input byte is mapped to its byte class, which is the column of the
    // transition table, and the rows of that table are displaced into a single array so that the entries of one row
    // fall into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and
    // Yao.
    //
    // The displaced arrays are padded so that every state and byte class lands inside them, which is why a lookup
    // needs no range check of its own.

    /// <summary>Maps an input byte to its byte class. Bytes which every state treats alike share a class.</summary>
    private static readonly byte[] ByteClassByByte =
    {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 0, 6, 0, 7,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    };

    /// <summary>Maps a state to the displacement of its row within <see cref="TransitionNext"/>.</summary>
    private static readonly byte[] TransitionBase =
    {
        0, 8, 2, 1, 1, 1, 1, 1, 1,
    };

    /// <summary>
    /// Holds the target state of every transition. The transition a state has on a byte class lives at
    /// TransitionBase[state] + class, but only if <see cref="TransitionCheck"/> confirms the cell belongs to that
    /// class.
    /// </summary>
    private static readonly byte[] TransitionNext =
    {
        0, 1, 7, 8, 5, 3, 4, 6, 2, 1, 2, 0, 0, 0, 0, 0,
        0,
    };

    /// <summary>
    /// Holds the byte class every cell of <see cref="TransitionNext"/> belongs to. A cell no state occupies holds
    /// 9, which is one past the highest byte class in use and can never be asked for.
    /// </summary>
    private static readonly byte[] TransitionCheck =
    {
        9, 1, 2, 3, 4, 5, 6, 7, 8, 1, 8, 9, 9, 9, 9, 9,
        9,
    };

    /// <summary>Holds the token a state accepts, or InvalidToken for a state which does not accept.</summary>
    private static readonly Token[] AcceptTokenByState =
    {
        Token.InvalidToken,
        Token.TokenWhitespace,
        Token.TokenInteger,
        Token.TokenPlus,
        Token.TokenMinus,
        Token.TokenMultiply,
        Token.TokenDivide,
        Token.TokenLparen,
        Token.TokenRparen,
    };

    /// <summary>The bytes being scanned.</summary>
    private ReadOnlyMemory<byte> _source;

    /// <summary>Index of the first byte of the current token.</summary>
    private int _lexemeStartIdx;

    /// <summary>Index one past the last byte of the current token.</summary>
    private int _lexemeEndIdx;

    /// <summary>Creates a scanner which turns the given bytes into tokens, starting at the first of them.</summary>
    /// <param name="source">The bytes to scan.</param>
    /// <param name="filePath">Used in error messages. Any string will do when the source is not a file.</param>
    public Scanner(ReadOnlyMemory<byte> source, string filePath)
    {
        FilePath = filePath;
        Reset(source, 0);
    }

    /// <inheritdoc/>
    public Token Token { get; private set; }

    /// <inheritdoc/>
    public int ByteOffset => _lexemeStartIdx;

    /// <inheritdoc/>
    public int Line { get; private set; }

    /// <inheritdoc/>
    public int Column { get; private set; }

    /// <inheritdoc/>
    public ReadOnlyMemory<byte> Lexeme => _source[_lexemeStartIdx.._lexemeEndIdx];

    /// <inheritdoc/>
    public string FilePath { get; }

    /// <inheritdoc/>
    public void Reset(ReadOnlyMemory<byte> source, int offset)
    {
        _source = source;

        _lexemeStartIdx = 0;
        // An offset past the end of the source would walk the line and column counters over bytes which are not
        // there. Clamping it leaves the scanner at the end of the source, where it reports the end token.
        _lexemeEndIdx = Math.Min(offset, source.Length);

        Line = 1;
        Column = 1;

        Token = Token.InvalidToken;
    }

    /// <summary>
    /// Advances to the next token. Bytes which form no token become an InvalidToken. Returns false once the end of the
    /// source is reached, which sets the token to EndToken.
    /// </summary>
    public bool Next()
    {
        ReadOnlySpan<byte> source = _source.Span;

        UpdateLineAndColumn(_lexemeStartIdx, _lexemeEndIdx);
        _lexemeStartIdx = _lexemeEndIdx;

        int state = 0;
        int lexemePeekIdx = _lexemeEndIdx;
        while (true)
        {
            // Remember every accepting state passed through, so the longest match wins over the first one.
            if (AcceptTokenByState[state] != Token.InvalidToken)
            {
                Token = AcceptTokenByState[state];
                _lexemeEndIdx = lexemePeekIdx;
            }
            if (lexemePeekIdx == source.Length)
            {
                // The end of the source is reached, so the state it stopped in was the last one to test.
                break;
            }

            int byteClass = ByteClassByByte[source[lexemePeekIdx]];
            int cellIdx = TransitionBase[state] + byteClass;
            if (TransitionCheck[cellIdx] != byteClass)
            {
                // The state has no transition on this byte, so the token ends here.
                break;
            }
            state = TransitionNext[cellIdx];
            lexemePeekIdx++;
        }

        if (_lexemeStartIdx < _lexemeEndIdx)
        {
            // A token was found.
            return true;
        }

        if (source.Length <= _lexemeStartIdx)
        {
            // The end of the source was reached.
            Token = Token.EndToken;
            return false;
        }

        // The bytes here form no token. The invalid token ends where the automaton stopped, because the byte it could
        // not consume is where the next attempt starts. Only when the automaton consumed nothing does it cover that
        // byte, which is what keeps the scan moving forward.
        Token = Token.InvalidToken;
        _lexemeEndIdx = Math.Max(_lexemeStartIdx + 1, lexemePeekIdx);
        return true;
    }

    /// <summary>Advances the line and column counters over the bytes between the two indexes.</summary>
    /// <param name="startIdx">Index of the first byte to move over.</param>
    /// <param name="endIdx">Index one past the last byte to move over.</param>
    private void UpdateLineAndColumn(int startIdx, int endIdx)
    {
        foreach (byte currByte in _source.Span[startIdx..endIdx])
        {
            if (currByte == 0x0a)
            {
                Line++;
                Column = 1;
            }
            else
            {
                Column++;
            }
        }
    }
}
