// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Parses the tokens of a scanner into a parse tree. */
@SuppressWarnings("auxiliaryclass")
public final class Parser {
    /** Every nonterminal symbol of the grammar. */
    public enum Nonterminal {
        ACCEPT_NONTERMINAL("$accept"),
        NONTERMINAL_EXPRESSION("expression"),
        ;

        /** The name the grammar spells the nonterminal with. */
        private final String displayName;

        Nonterminal(String displayName) {
            this.displayName = displayName;
        }

        /** Returns the name of the nonterminal, as the grammar spells it. */
        @Override
        public String toString() {
            return displayName;
        }
    }

    /** A terminal or a nonterminal. */
    public sealed interface ParseSymbol {
    }

    /** @param token the terminal this symbol stands for */
    public record TerminalSymbol(Scanner.Token token) implements ParseSymbol {
        @Override
        public String toString() {
            return "terminal " + token;
        }
    }

    /** @param nonterminal the nonterminal this symbol stands for */
    public record NonterminalSymbol(Nonterminal nonterminal) implements ParseSymbol {
        @Override
        public String toString() {
            return "nonterminal " + nonterminal;
        }
    }

    /**
     * A single node of the parse tree.
     *
     * @param symbol the terminal or nonterminal this node stands for
     * @param lexeme the bytes of the terminal, as a view into the source rather than a copy of it. Empty for a
     *     nonterminal and for the error symbol, which no input produced
     * @param children the nodes of the right hand side of the production which was reduced to this node. Empty for a
     *     terminal
     */
    public record ParseNode(ParseSymbol symbol, ByteBuffer lexeme, List<ParseNode> children) {
        /**
         * Returns the bytes of the terminal. A buffer carries the position it is read from, so every call hands out a
         * view of its own, which keeps one reader from consuming the bytes for the next.
         */
        @Override
        public ByteBuffer lexeme() {
            return lexeme.duplicate();
        }
    }

    /**
     * A single parse error. Parse errors are returned by {@link Parser#parse} rather than thrown, and this is no
     * exception, so reporting many of them costs no stack traces. Throw one with
     * {@code new IllegalStateException(parseError.message())}.
     *
     * @param reason what is wrong, without the position in front of it
     * @param isSyntaxError true for an error in the input, false for a defect of the parser itself, which ends the
     *     parse
     * @param token the token the parse stopped on
     * @param byteOffset start of that token in bytes from the start of the source
     * @param line line that token starts on, counted from one
     * @param column column that token starts on, counted from one
     * @param lexeme the bytes of that token
     * @param filePath the file path the scanner was given
     */
    public record ParseError(
            String reason,
            boolean isSyntaxError,
            Scanner.Token token,
            int byteOffset,
            int line,
            int column,
            ByteBuffer lexeme,
            String filePath) {
        /**
         * @param reason what is wrong, without the position in front of it
         * @param isSyntaxError true for an error in the input, false for a defect of the parser itself
         * @param scanner the scanner the token and its position are taken from
         */
        ParseError(String reason, boolean isSyntaxError, TokenSkipperScanner scanner) {
            this(
                    reason,
                    isSyntaxError,
                    scanner.token(),
                    scanner.byteOffset(),
                    scanner.line(),
                    scanner.column(),
                    scanner.lexeme(),
                    scanner.filePath());
        }

        /**
         * Returns the bytes of the token. A buffer carries the position it is read from, so every call hands out a
         * view of its own, which keeps one reader from consuming the bytes for the next.
         */
        @Override
        public ByteBuffer lexeme() {
            return lexeme.duplicate();
        }

        /**
         * Returns the error as one line of text, in the file:line:column: reason form editors and build tools
         * recognize.
         */
        public String message() {
            return filePath + ":" + line + ":" + column + ": " + reason;
        }
    }

    /**
     * What a parse returns.
     *
     * @param tree the parse tree, or null when the parse could not be finished
     * @param errors every error the parse reported, in the order they were found
     */
    public record ParseResult(ParseNode tree, List<ParseError> errors) {
    }

    /** What one step of a parse ended with. */
    private sealed interface StepOutcome {
        /** The parse goes on. */
        record Continue() implements StepOutcome {
        }

        /** The input was reduced to the start symbol. */
        record Accept() implements StepOutcome {
        }

        /**
         * The parse cannot go on.
         *
         * @param error why it cannot go on
         */
        record Failed(ParseError error) implements StepOutcome {
        }
    }

    /**
     * How many tokens have to be shifted after a syntax error before errors are reported again. Suppressing the errors
     * in between keeps one mistake in the input from producing an avalanche of messages which all follow from it.
     */
    private static final int ERROR_RECOVERY_SHIFTS = 3;

    /** What {@link #errorShiftState} returns for a state which cannot shift the error symbol. */
    private static final int NO_ERROR_SHIFT_STATE = -1;

    /** How many states the stacks start with room for. They grow as a deeper parse needs them to. */
    private static final int INITIAL_STACK_CAPACITY = 64;

    /** The lexeme of a node which no input produced. */
    private static final ByteBuffer EMPTY_LEXEME = ByteBuffer.allocate(0).asReadOnlyBuffer();

    /** The nonterminals by their index, held here because values() hands out a copy on every call. */
    private static final Nonterminal[] NONTERMINALS = Nonterminal.values();

    /** The outcome of a step which goes on, held here because it carries nothing one step differs from another in. */
    private static final StepOutcome CONTINUE = new StepOutcome.Continue();

    /** The outcome of a step which accepts, held here because it carries nothing one step differs from another in. */
    private static final StepOutcome ACCEPT = new StepOutcome.Accept();

    // The parse table is held in lookup tables. A token is translated into the column of the action table which holds
    // the decisions for it, and the rows of that table are displaced into a single array so that the entries of one
    // row fall into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan
    // and Yao. The gotos are held the same way, with the nonterminal as the column.
    //
    // The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the
    // action table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the
    // tables.
    //
    // The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
    // range check of its own.
    //
    // Every table is joined from one method per chunk, because a method may hold only 64 KB of bytecode.

    /** Number of low bits of an action which hold what it does. The value it carries sits above them. */
    private static final int ACTION_KIND_BITS = 2;

    /** Selects out of an action what it does. */
    private static final int ACTION_KIND_MASK = 3;

    /** Shifts the terminal and continues in the state the action carries. */
    private static final int ACTION_KIND_SHIFT = 0;

    /** Reduces by the production the action carries. */
    private static final int ACTION_KIND_REDUCE = 1;

    /** Ends the parse successfully, the input having been reduced to the start symbol. */
    private static final int ACTION_KIND_ACCEPT = 2;

    /** Rejects the terminal as a syntax error. */
    private static final int ACTION_KIND_ERROR = 3;

    /**
     * The column a token gets which is no terminal of this grammar. No state has an entry in it, so a lookup falls
     * through to the default action of the state.
     */
    private static final int NO_TERMINAL_COLUMN = 0;

    /** The column holding the shifts of the error symbol, where the recovery reads the state to resume in. */
    private static final int ERROR_TERMINAL_COLUMN = 0;

    /**
     * Translates a token into the column of the action table which holds the decisions for it. A token the grammar
     * does not have is not named in the entries and keeps the NO_TERMINAL_COLUMN every unnamed index holds.
     */
    private static final byte[] TERMINAL_COLUMN_BY_TOKEN = newTerminalColumnByToken();

    /** Maps a state to the displacement of its row within {@link #ACTION_NEXT}. */
    private static final byte[] ACTION_BASE = concat(
            actionBase0());

    /**
     * Holds the action of every entry. The action a state has for a column lives at ACTION_BASE[state] + column, but
     * only if {@link #ACTION_CHECK} confirms the cell belongs to that column.
     */
    private static final byte[] ACTION_NEXT = concat(
            actionNext0());

    /**
     * Holds the column every cell of {@link #ACTION_NEXT} belongs to. A cell no state occupies holds
     * 11, which is one past the highest column in use and can never be asked for.
     */
    private static final byte[] ACTION_CHECK = concat(
            actionCheck0());

    /**
     * Holds the action a state takes for every column it has no entry of its own for. A state which has none carries
     * the error action.
     */
    private static final byte[] DEFAULT_ACTION_BY_STATE = concat(
            defaultActionByState0());

    /** Maps a state to the displacement of its row within {@link #GOTO_NEXT}. */
    private static final byte[] GOTO_BASE = concat(
            gotoBase0());

    /**
     * Holds the state a goto leads to. The goto a state has for a nonterminal lives at GOTO_BASE[state] + nonterminal,
     * but only if {@link #GOTO_CHECK} confirms the cell belongs to that nonterminal.
     */
    private static final byte[] GOTO_NEXT = concat(
            gotoNext0());

    /**
     * Holds the nonterminal every cell of {@link #GOTO_NEXT} belongs to. A cell no state occupies holds
     * 2, which is one past the highest nonterminal and can never be asked for.
     */
    private static final byte[] GOTO_CHECK = concat(
            gotoCheck0());

    /** Holds the state a goto on a nonterminal leads to for every state {@link #GOTO_NEXT} has no entry for. */
    private static final byte[] DEFAULT_GOTO_BY_NONTERMINAL = concat(
            defaultGotoByNonterminal0());

    /** Holds how many symbols a reduction takes off the stacks, which is the length of the right hand side. */
    private static final byte[] POP_COUNT_BY_PRODUCTION = concat(
            popCountByProduction0());

    /** Holds the nonterminal on the left hand side of a production. */
    private static final byte[] NONTERMINAL_BY_PRODUCTION = concat(
            nonterminalByProduction0());

    /** The scanner of the running parse. */
    private TokenSkipperScanner scanner;

    /** The states of the running parse, the current one on top. */
    private int[] stateStack = new int[INITIAL_STACK_CAPACITY];

    /** How many entries of {@link #stateStack} are in use. */
    private int stateStackSize;

    /** One node per symbol shifted or reduced so far. */
    private final List<ParseNode> nodeStack = new ArrayList<>(INITIAL_STACK_CAPACITY);

    /** The errors of the running parse, which {@link #parse} returns next to the tree. */
    private final List<ParseError> errors = new ArrayList<>();

    /**
     * Counts down the tokens which still have to be shifted before syntax errors are reported again. Zero while the
     * parser is in sync with the input.
     */
    private int errorRecoveryShiftsRemaining;

    /**
     * Parses the tokens the scanner delivers. Can be called more than once, with a different scanner each time.
     *
     * <p>When the grammar marks places to resume at with the error symbol, a syntax error does not end the parse: the
     * result then holds both the tree parsed so far, with a node for the error symbol at every place resumed at, and
     * every error found. The tree is null when the parse could not be carried to its end.
     */
    public ParseResult parse(TokenSkipperScanner scanner) {
        this.scanner = scanner;

        // The stacks are emptied rather than replaced, so a parser hands out the room it already has to the parse
        // after it instead of allocating anew.
        stateStackSize = 0;
        nodeStack.clear();
        errors.clear();
        errorRecoveryShiftsRemaining = 0;

        pushState(0);

        // A source with no tokens at all reports false right away. That is not an error: the token is the end of input
        // either way, and whether a parse of nothing but that is legal is for the table to decide.
        scanner.next();

        while (true) {
            StepOutcome outcome = step();
            if (outcome instanceof StepOutcome.Accept) {
                return new ParseResult(nodeStack.get(0), List.copyOf(errors));
            }
            if (!(outcome instanceof StepOutcome.Failed failed)) {
                // The parse goes on.
                continue;
            }
            ParseError failure = failed.error();

            if (!failure.isSyntaxError()) {
                // Only an error in the input can be recovered from.
                errors.add(failure);
                return new ParseResult(null, List.copyOf(errors));
            }
            if (errorRecoveryShiftsRemaining == 0) {
                // While recovering, the parser is not in sync with the input, so the errors it runs into there follow
                // from the one already reported.
                errors.add(failure);
            }
            if (!recoverFromError()) {
                return new ParseResult(null, List.copyOf(errors));
            }
        }
    }

    /**
     * Returns the state to continue in when the error symbol is shifted in the given state, or
     * {@link #NO_ERROR_SHIFT_STATE} when the state cannot shift it. The states which can are the places the grammar
     * marked to resume at after a syntax error.
     *
     * <p>The default action of the state is deliberately not consulted, because only an entry the state has of its own
     * is a place to resume at.
     */
    private static int errorShiftState(int state) {
        int cellIdx = ACTION_BASE[state] + ERROR_TERMINAL_COLUMN;
        if (ACTION_CHECK[cellIdx] != ERROR_TERMINAL_COLUMN) {
            return NO_ERROR_SHIFT_STATE;
        }

        int action = ACTION_NEXT[cellIdx];
        if ((action & ACTION_KIND_MASK) != ACTION_KIND_SHIFT) {
            return NO_ERROR_SHIFT_STATE;
        }
        return action >> ACTION_KIND_BITS;
    }

    /**
     * Performs the one action the state on top of the stack takes for the current token. The outcome carries the error
     * only when the parse cannot go on.
     */
    private StepOutcome step() {
        Scanner.Token terminal = scanner.token();

        // A token which is no terminal of this grammar takes the default action of the state.
        int column = NO_TERMINAL_COLUMN;
        if (terminal.ordinal() < TERMINAL_COLUMN_BY_TOKEN.length) {
            column = TERMINAL_COLUMN_BY_TOKEN[terminal.ordinal()];
        }

        int state = currentState();
        int cellIdx = ACTION_BASE[state] + column;
        int action = DEFAULT_ACTION_BY_STATE[state];
        if (ACTION_CHECK[cellIdx] == column) {
            // An entry the state has of its own beats its default action, which is what keeps a token the grammar
            // rejects on purpose an error even in a state which reduces on everything else.
            action = ACTION_NEXT[cellIdx];
        }

        return switch (action & ACTION_KIND_MASK) {
            case ACTION_KIND_SHIFT -> {
                pushState(action >> ACTION_KIND_BITS);
                nodeStack.add(new ParseNode(new TerminalSymbol(terminal), scanner.lexeme(), List.of()));
                scanner.next();
                if (errorRecoveryShiftsRemaining > 0) {
                    // Getting tokens of the input shifted again is what makes the parser trust its position.
                    errorRecoveryShiftsRemaining--;
                }
                yield CONTINUE;
            }
            case ACTION_KIND_REDUCE -> {
                reduce(action >> ACTION_KIND_BITS);
                yield CONTINUE;
            }
            case ACTION_KIND_ACCEPT -> ACCEPT;
            case ACTION_KIND_ERROR ->
                new StepOutcome.Failed(new ParseError("unexpected token " + terminal, true, scanner));
            default ->
                new StepOutcome.Failed(
                        new ParseError("unexpected action " + action + " in state " + state, false, scanner));
        };
    }

    /**
     * Replaces the right hand side of the production on the stacks with the nonterminal on its left hand side, and
     * continues in the state the goto of the uncovered state leads to.
     */
    private void reduce(int productionIdx) {
        int popCount = POP_COUNT_BY_PRODUCTION[productionIdx];
        int nonterminal = NONTERMINAL_BY_PRODUCTION[productionIdx];

        stateStackSize -= popCount;

        int state = currentState();
        // A state without a goto of its own on the nonterminal goes where most states go with it. A state which a
        // reduction uncovers always has one, so there is no case for a nonterminal missing from both.
        int gotoState = DEFAULT_GOTO_BY_NONTERMINAL[nonterminal];
        int cellIdx = GOTO_BASE[state] + nonterminal;
        if (GOTO_CHECK[cellIdx] == nonterminal) {
            gotoState = GOTO_NEXT[cellIdx];
        }
        pushState(gotoState);

        // The right hand side comes off the node stack and is handed over as the children.
        List<ParseNode> rightHandSide = nodeStack.subList(nodeStack.size() - popCount, nodeStack.size());
        List<ParseNode> children = List.copyOf(rightHandSide);
        rightHandSide.clear();
        nodeStack.add(new ParseNode(new NonterminalSymbol(NONTERMINALS[nonterminal]), EMPTY_LEXEME, children));
    }

    /**
     * Puts the parser back where it can carry on with the remaining input after a syntax error. Once it reports false,
     * the parse is given up.
     *
     * <p>This is panic mode recovery as described in section 7 "Error Handling" of the yacc report: the stack is
     * popped until a state is reached which can shift the error symbol, and the symbol is shifted there. Everything
     * the popped states had parsed is discarded with them. The token which caused the error is kept for the resumed
     * state to look at, and only discarded when the parse fails on it a second time.
     */
    private boolean recoverFromError() {
        if (errorRecoveryShiftsRemaining == ERROR_RECOVERY_SHIFTS) {
            // Nothing was shifted since the last error, so the parser is failing on the token it already failed on.
            if (scanner.token() == Scanner.Token.END_TOKEN) {
                // The end of input is the one token which cannot be discarded.
                return false;
            }
            scanner.next();
        }
        errorRecoveryShiftsRemaining = ERROR_RECOVERY_SHIFTS;

        while (true) {
            int nextState = errorShiftState(currentState());
            if (nextState != NO_ERROR_SHIFT_STATE) {
                // Shift the error symbol. Its node stands for the dropped part of the input and has no lexeme.
                pushState(nextState);
                nodeStack.add(
                        new ParseNode(new TerminalSymbol(Scanner.Token.ERROR_TOKEN), EMPTY_LEXEME, List.of()));
                return true;
            }
            if (stateStackSize == 1) {
                // Only the state the parse started in is left and it cannot shift the error symbol either.
                return false;
            }
            // The state cannot resume here, so it is dropped together with what it had parsed. One state carries one
            // node, so dropping one drops one.
            stateStackSize--;
            nodeStack.remove(nodeStack.size() - 1);
        }
    }

    /** Returns the state on top of the stack, which is the one the parse is in. */
    private int currentState() {
        return stateStack[stateStackSize - 1];
    }

    /** Puts the given state on top of the stack, growing it when it is full. */
    private void pushState(int state) {
        if (stateStackSize == stateStack.length) {
            stateStack = Arrays.copyOf(stateStack, stateStack.length * 2);
        }
        stateStack[stateStackSize] = state;
        stateStackSize++;
    }

    /**
     * Builds {@link #TERMINAL_COLUMN_BY_TOKEN} from the tokens and the columns they stand at, sized to the highest
     * token named.
     */
    private static byte[] newTerminalColumnByToken() {
        Scanner.Token[] tokens = {
            Scanner.Token.END_TOKEN,
            Scanner.Token.TOKEN_WHITESPACE,
            Scanner.Token.TOKEN_INTEGER,
            Scanner.Token.TOKEN_PLUS,
            Scanner.Token.TOKEN_MINUS,
            Scanner.Token.TOKEN_MULTIPLY,
            Scanner.Token.TOKEN_DIVIDE,
            Scanner.Token.TOKEN_LPAREN,
            Scanner.Token.TOKEN_RPAREN,
            Scanner.Token.TOKEN_UMINUS,
        };
        byte[] columns = {
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
        };

        int length = 0;
        for (Scanner.Token token : tokens) {
            length = Math.max(length, token.ordinal() + 1);
        }

        byte[] result = new byte[length];
        for (int i = 0; i < tokens.length; i++) {
            result[tokens[i].ordinal()] = columns[i];
        }
        return result;
    }

    /** Returns chunk 0 of {@link #ACTION_BASE}. */
    private static byte[] actionBase0() {
        return new byte[] {
            9, 1, 9, 9, 0, 1, 4, 1, 9, 9, 9, 9, 1, 12, 12, 1,
            1,
        };
    }

    /** Returns chunk 0 of {@link #ACTION_NEXT}. */
    private static byte[] actionNext0() {
        return new byte[] {
            0, 28, 0, 0, 32, 36, 40, 44, 32, 36, 40, 44, 4, 48, 8, 0,
            0, 12, 40, 44, 0, 0, 0,
        };
    }

    /** Returns chunk 0 of {@link #ACTION_CHECK}. */
    private static byte[] actionCheck0() {
        return new byte[] {
            11, 1, 11, 11, 4, 5, 6, 7, 4, 5, 6, 7, 3, 9, 5, 11,
            11, 8, 6, 7, 11, 11, 11,
        };
    }

    /** Returns chunk 0 of {@link #DEFAULT_ACTION_BY_STATE}. */
    private static byte[] defaultActionByState0() {
        return new byte[] {
            3, 5, 3, 3, 3, 25, 3, 2, 3, 3, 3, 3, 29, 9, 13, 17,
            21,
        };
    }

    /** Returns chunk 0 of {@link #GOTO_BASE}. */
    private static byte[] gotoBase0() {
        return new byte[] {
            6, 6, 0, 1, 6, 6, 6, 6, 2, 3, 4, 5, 6, 6, 6, 6,
            6,
        };
    }

    /** Returns chunk 0 of {@link #GOTO_NEXT}. */
    private static byte[] gotoNext0() {
        return new byte[] {
            0, 5, 6, 13, 14, 15, 16, 0,
        };
    }

    /** Returns chunk 0 of {@link #GOTO_CHECK}. */
    private static byte[] gotoCheck0() {
        return new byte[] {
            2, 1, 1, 1, 1, 1, 1, 2,
        };
    }

    /** Returns chunk 0 of {@link #DEFAULT_GOTO_BY_NONTERMINAL}. */
    private static byte[] defaultGotoByNonterminal0() {
        return new byte[] {
            0, 4,
        };
    }

    /** Returns chunk 0 of {@link #POP_COUNT_BY_PRODUCTION}. */
    private static byte[] popCountByProduction0() {
        return new byte[] {
            2, 1, 3, 3, 3, 3, 2, 3,
        };
    }

    /** Returns chunk 0 of {@link #NONTERMINAL_BY_PRODUCTION}. */
    private static byte[] nonterminalByProduction0() {
        return new byte[] {
            0, 1, 1, 1, 1, 1, 1, 1,
        };
    }

    /** Returns the given chunks of a table as the one table they make up. */
    private static byte[] concat(byte[]... parts) {
        int length = 0;
        for (byte[] part : parts) {
            length += part.length;
        }

        byte[] result = new byte[length];
        int offset = 0;
        for (byte[] part : parts) {
            System.arraycopy(part, 0, result, offset, part.length);
            offset += part.length;
        }
        return result;
    }
}
