// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser

import (
	"errors"
	"fmt"
)

// Nonterminal is the data type representing all nonterminal symbols.
type Nonterminal int

const (
	// AcceptNonterminal is the start symbol the generator adds around the one the grammar declares.
	// Reaching it accepts the input.
	AcceptNonterminal Nonterminal = 0

	NonterminalInput                     Nonterminal = 1
	NonterminalPrologueDeclarations      Nonterminal = 2
	NonterminalPrologueDeclaration       Nonterminal = 3
	NonterminalParams                    Nonterminal = 4
	NonterminalGrammarDeclaration        Nonterminal = 5
	NonterminalCodePropsType             Nonterminal = 6
	NonterminalUnionName                 Nonterminal = 7
	NonterminalSymbolDeclaration         Nonterminal = 8
	NonterminalPrecedenceDeclarator      Nonterminal = 9
	NonterminalString_opt                Nonterminal = 10
	NonterminalTag_opt                   Nonterminal = 11
	NonterminalGenericSymlist            Nonterminal = 12
	NonterminalGenericSymlistItem        Nonterminal = 13
	NonterminalTag                       Nonterminal = 14
	NonterminalNtermDecls                Nonterminal = 15
	NonterminalTokenDecls                Nonterminal = 16
	NonterminalTokenDecl_1               Nonterminal = 17
	NonterminalTokenDecl                 Nonterminal = 18
	NonterminalInt_opt                   Nonterminal = 19
	NonterminalAlias                     Nonterminal = 20
	NonterminalTokenDeclsForPrec         Nonterminal = 21
	NonterminalTokenDeclForPrec_1        Nonterminal = 22
	NonterminalTokenDeclForPrec          Nonterminal = 23
	NonterminalSymbolDecls               Nonterminal = 24
	NonterminalSymbols_1                 Nonterminal = 25
	NonterminalGrammar                   Nonterminal = 26
	NonterminalRulesOrGrammarDeclaration Nonterminal = 27
	NonterminalRules                     Nonterminal = 28
	NonterminalRhses_1                   Nonterminal = 29
	NonterminalRhs                       Nonterminal = 30
	NonterminalNamedRef_opt              Nonterminal = 31
	NonterminalVariable                  Nonterminal = 32
	NonterminalValue                     Nonterminal = 33
	NonterminalId                        Nonterminal = 34
	NonterminalIdColon                   Nonterminal = 35
	NonterminalSymbol                    Nonterminal = 36
	NonterminalStringAsId                Nonterminal = 37
	NonterminalEpilogue_opt              Nonterminal = 38
)

// Nonterminal implements fmt.Stringer.
var _ fmt.Stringer = (*Nonterminal)(nil)

// String returns a string representation of the nonterminal.
func (n Nonterminal) String() string {
	switch n {
	case AcceptNonterminal:
		return `$accept`
	case NonterminalInput:
		return `input`
	case NonterminalPrologueDeclarations:
		return `prologue_declarations`
	case NonterminalPrologueDeclaration:
		return `prologue_declaration`
	case NonterminalParams:
		return `params`
	case NonterminalGrammarDeclaration:
		return `grammar_declaration`
	case NonterminalCodePropsType:
		return `code_props_type`
	case NonterminalUnionName:
		return `union_name`
	case NonterminalSymbolDeclaration:
		return `symbol_declaration`
	case NonterminalPrecedenceDeclarator:
		return `precedence_declarator`
	case NonterminalString_opt:
		return `string.opt`
	case NonterminalTag_opt:
		return `tag.opt`
	case NonterminalGenericSymlist:
		return `generic_symlist`
	case NonterminalGenericSymlistItem:
		return `generic_symlist_item`
	case NonterminalTag:
		return `tag`
	case NonterminalNtermDecls:
		return `nterm_decls`
	case NonterminalTokenDecls:
		return `token_decls`
	case NonterminalTokenDecl_1:
		return `token_decl.1`
	case NonterminalTokenDecl:
		return `token_decl`
	case NonterminalInt_opt:
		return `int.opt`
	case NonterminalAlias:
		return `alias`
	case NonterminalTokenDeclsForPrec:
		return `token_decls_for_prec`
	case NonterminalTokenDeclForPrec_1:
		return `token_decl_for_prec.1`
	case NonterminalTokenDeclForPrec:
		return `token_decl_for_prec`
	case NonterminalSymbolDecls:
		return `symbol_decls`
	case NonterminalSymbols_1:
		return `symbols.1`
	case NonterminalGrammar:
		return `grammar`
	case NonterminalRulesOrGrammarDeclaration:
		return `rules_or_grammar_declaration`
	case NonterminalRules:
		return `rules`
	case NonterminalRhses_1:
		return `rhses.1`
	case NonterminalRhs:
		return `rhs`
	case NonterminalNamedRef_opt:
		return `named_ref.opt`
	case NonterminalVariable:
		return `variable`
	case NonterminalValue:
		return `value`
	case NonterminalId:
		return `id`
	case NonterminalIdColon:
		return `id_colon`
	case NonterminalSymbol:
		return `symbol`
	case NonterminalStringAsId:
		return `string_as_id`
	case NonterminalEpilogue_opt:
		return `epilogue.opt`
	default:
		return "unknown"
	}
}

// Production is the data type representing all productions of the grammar. It has no entry for production 0
// ($accept), which is never reduced.
type Production int

const (
	// NoProduction is the Production a terminal node carries, since no production reduces to it.
	NoProduction                         Production = 0
	ProductionInput1                     Production = 1
	ProductionPrologueDeclarations1      Production = 2
	ProductionPrologueDeclarations2      Production = 3
	ProductionPrologueDeclaration1       Production = 4
	ProductionPrologueDeclaration2       Production = 5
	ProductionPrologueDeclaration3       Production = 6
	ProductionPrologueDeclaration4       Production = 7
	ProductionPrologueDeclaration5       Production = 8
	ProductionPrologueDeclaration6       Production = 9
	ProductionPrologueDeclaration7       Production = 10
	ProductionPrologueDeclaration8       Production = 11
	ProductionPrologueDeclaration9       Production = 12
	ProductionPrologueDeclaration10      Production = 13
	ProductionPrologueDeclaration11      Production = 14
	ProductionPrologueDeclaration12      Production = 15
	ProductionPrologueDeclaration13      Production = 16
	ProductionPrologueDeclaration14      Production = 17
	ProductionPrologueDeclaration15      Production = 18
	ProductionPrologueDeclaration16      Production = 19
	ProductionPrologueDeclaration17      Production = 20
	ProductionPrologueDeclaration18      Production = 21
	ProductionPrologueDeclaration19      Production = 22
	ProductionPrologueDeclaration20      Production = 23
	ProductionPrologueDeclaration21      Production = 24
	ProductionPrologueDeclaration22      Production = 25
	ProductionPrologueDeclaration23      Production = 26
	ProductionPrologueDeclaration24      Production = 27
	ProductionPrologueDeclaration25      Production = 28
	ProductionParams1                    Production = 29
	ProductionParams2                    Production = 30
	ProductionGrammarDeclaration1        Production = 31
	ProductionGrammarDeclaration2        Production = 32
	ProductionGrammarDeclaration3        Production = 33
	ProductionGrammarDeclaration4        Production = 34
	ProductionGrammarDeclaration5        Production = 35
	ProductionGrammarDeclaration6        Production = 36
	ProductionGrammarDeclaration7        Production = 37
	ProductionCodePropsType1             Production = 38
	ProductionCodePropsType2             Production = 39
	ProductionUnionName1                 Production = 40
	ProductionUnionName2                 Production = 41
	ProductionGrammarDeclaration8        Production = 42
	ProductionSymbolDeclaration1         Production = 43
	ProductionSymbolDeclaration2         Production = 44
	ProductionSymbolDeclaration3         Production = 45
	ProductionSymbolDeclaration4         Production = 46
	ProductionPrecedenceDeclarator1      Production = 47
	ProductionPrecedenceDeclarator2      Production = 48
	ProductionPrecedenceDeclarator3      Production = 49
	ProductionPrecedenceDeclarator4      Production = 50
	ProductionString_opt1                Production = 51
	ProductionString_opt2                Production = 52
	ProductionTag_opt1                   Production = 53
	ProductionTag_opt2                   Production = 54
	ProductionGenericSymlist1            Production = 55
	ProductionGenericSymlist2            Production = 56
	ProductionGenericSymlistItem1        Production = 57
	ProductionGenericSymlistItem2        Production = 58
	ProductionTag1                       Production = 59
	ProductionTag2                       Production = 60
	ProductionTag3                       Production = 61
	ProductionNtermDecls1                Production = 62
	ProductionTokenDecls1                Production = 63
	ProductionTokenDecls2                Production = 64
	ProductionTokenDecls3                Production = 65
	ProductionTokenDecl_11               Production = 66
	ProductionTokenDecl_12               Production = 67
	ProductionTokenDecl1                 Production = 68
	ProductionInt_opt1                   Production = 69
	ProductionInt_opt2                   Production = 70
	ProductionAlias1                     Production = 71
	ProductionAlias2                     Production = 72
	ProductionAlias3                     Production = 73
	ProductionTokenDeclsForPrec1         Production = 74
	ProductionTokenDeclsForPrec2         Production = 75
	ProductionTokenDeclsForPrec3         Production = 76
	ProductionTokenDeclForPrec_11        Production = 77
	ProductionTokenDeclForPrec_12        Production = 78
	ProductionTokenDeclForPrec1          Production = 79
	ProductionTokenDeclForPrec2          Production = 80
	ProductionSymbolDecls1               Production = 81
	ProductionSymbolDecls2               Production = 82
	ProductionSymbolDecls3               Production = 83
	ProductionSymbols_11                 Production = 84
	ProductionSymbols_12                 Production = 85
	ProductionGrammar1                   Production = 86
	ProductionGrammar2                   Production = 87
	ProductionRulesOrGrammarDeclaration1 Production = 88
	ProductionRulesOrGrammarDeclaration2 Production = 89
	ProductionRulesOrGrammarDeclaration3 Production = 90
	ProductionRules1                     Production = 91
	ProductionRhses_11                   Production = 92
	ProductionRhses_12                   Production = 93
	ProductionRhses_13                   Production = 94
	ProductionRhs1                       Production = 95
	ProductionRhs2                       Production = 96
	ProductionRhs3                       Production = 97
	ProductionRhs4                       Production = 98
	ProductionRhs5                       Production = 99
	ProductionRhs6                       Production = 100
	ProductionRhs7                       Production = 101
	ProductionRhs8                       Production = 102
	ProductionRhs9                       Production = 103
	ProductionRhs10                      Production = 104
	ProductionNamedRef_opt1              Production = 105
	ProductionNamedRef_opt2              Production = 106
	ProductionVariable1                  Production = 107
	ProductionValue1                     Production = 108
	ProductionValue2                     Production = 109
	ProductionValue3                     Production = 110
	ProductionValue4                     Production = 111
	ProductionId1                        Production = 112
	ProductionId2                        Production = 113
	ProductionIdColon1                   Production = 114
	ProductionSymbol1                    Production = 115
	ProductionSymbol2                    Production = 116
	ProductionStringAsId1                Production = 117
	ProductionEpilogue_opt1              Production = 118
	ProductionEpilogue_opt2              Production = 119
)

// Production implements fmt.Stringer.
var _ fmt.Stringer = (*Production)(nil)

// String returns the name of the production.
func (p Production) String() string {
	switch p {
	case NoProduction:
		return "none"
	case ProductionInput1:
		return `input_1`
	case ProductionPrologueDeclarations1:
		return `prologue_declarations_1`
	case ProductionPrologueDeclarations2:
		return `prologue_declarations_2`
	case ProductionPrologueDeclaration1:
		return `prologue_declaration_1`
	case ProductionPrologueDeclaration2:
		return `prologue_declaration_2`
	case ProductionPrologueDeclaration3:
		return `prologue_declaration_3`
	case ProductionPrologueDeclaration4:
		return `prologue_declaration_4`
	case ProductionPrologueDeclaration5:
		return `prologue_declaration_5`
	case ProductionPrologueDeclaration6:
		return `prologue_declaration_6`
	case ProductionPrologueDeclaration7:
		return `prologue_declaration_7`
	case ProductionPrologueDeclaration8:
		return `prologue_declaration_8`
	case ProductionPrologueDeclaration9:
		return `prologue_declaration_9`
	case ProductionPrologueDeclaration10:
		return `prologue_declaration_10`
	case ProductionPrologueDeclaration11:
		return `prologue_declaration_11`
	case ProductionPrologueDeclaration12:
		return `prologue_declaration_12`
	case ProductionPrologueDeclaration13:
		return `prologue_declaration_13`
	case ProductionPrologueDeclaration14:
		return `prologue_declaration_14`
	case ProductionPrologueDeclaration15:
		return `prologue_declaration_15`
	case ProductionPrologueDeclaration16:
		return `prologue_declaration_16`
	case ProductionPrologueDeclaration17:
		return `prologue_declaration_17`
	case ProductionPrologueDeclaration18:
		return `prologue_declaration_18`
	case ProductionPrologueDeclaration19:
		return `prologue_declaration_19`
	case ProductionPrologueDeclaration20:
		return `prologue_declaration_20`
	case ProductionPrologueDeclaration21:
		return `prologue_declaration_21`
	case ProductionPrologueDeclaration22:
		return `prologue_declaration_22`
	case ProductionPrologueDeclaration23:
		return `prologue_declaration_23`
	case ProductionPrologueDeclaration24:
		return `prologue_declaration_24`
	case ProductionPrologueDeclaration25:
		return `prologue_declaration_25`
	case ProductionParams1:
		return `params_1`
	case ProductionParams2:
		return `params_2`
	case ProductionGrammarDeclaration1:
		return `grammar_declaration_1`
	case ProductionGrammarDeclaration2:
		return `grammar_declaration_2`
	case ProductionGrammarDeclaration3:
		return `grammar_declaration_3`
	case ProductionGrammarDeclaration4:
		return `grammar_declaration_4`
	case ProductionGrammarDeclaration5:
		return `grammar_declaration_5`
	case ProductionGrammarDeclaration6:
		return `grammar_declaration_6`
	case ProductionGrammarDeclaration7:
		return `grammar_declaration_7`
	case ProductionCodePropsType1:
		return `code_props_type_1`
	case ProductionCodePropsType2:
		return `code_props_type_2`
	case ProductionUnionName1:
		return `union_name_1`
	case ProductionUnionName2:
		return `union_name_2`
	case ProductionGrammarDeclaration8:
		return `grammar_declaration_8`
	case ProductionSymbolDeclaration1:
		return `symbol_declaration_1`
	case ProductionSymbolDeclaration2:
		return `symbol_declaration_2`
	case ProductionSymbolDeclaration3:
		return `symbol_declaration_3`
	case ProductionSymbolDeclaration4:
		return `symbol_declaration_4`
	case ProductionPrecedenceDeclarator1:
		return `precedence_declarator_1`
	case ProductionPrecedenceDeclarator2:
		return `precedence_declarator_2`
	case ProductionPrecedenceDeclarator3:
		return `precedence_declarator_3`
	case ProductionPrecedenceDeclarator4:
		return `precedence_declarator_4`
	case ProductionString_opt1:
		return `string.opt_1`
	case ProductionString_opt2:
		return `string.opt_2`
	case ProductionTag_opt1:
		return `tag.opt_1`
	case ProductionTag_opt2:
		return `tag.opt_2`
	case ProductionGenericSymlist1:
		return `generic_symlist_1`
	case ProductionGenericSymlist2:
		return `generic_symlist_2`
	case ProductionGenericSymlistItem1:
		return `generic_symlist_item_1`
	case ProductionGenericSymlistItem2:
		return `generic_symlist_item_2`
	case ProductionTag1:
		return `tag_1`
	case ProductionTag2:
		return `tag_2`
	case ProductionTag3:
		return `tag_3`
	case ProductionNtermDecls1:
		return `nterm_decls_1`
	case ProductionTokenDecls1:
		return `token_decls_1`
	case ProductionTokenDecls2:
		return `token_decls_2`
	case ProductionTokenDecls3:
		return `token_decls_3`
	case ProductionTokenDecl_11:
		return `token_decl.1_1`
	case ProductionTokenDecl_12:
		return `token_decl.1_2`
	case ProductionTokenDecl1:
		return `token_decl_1`
	case ProductionInt_opt1:
		return `int.opt_1`
	case ProductionInt_opt2:
		return `int.opt_2`
	case ProductionAlias1:
		return `alias_1`
	case ProductionAlias2:
		return `alias_2`
	case ProductionAlias3:
		return `alias_3`
	case ProductionTokenDeclsForPrec1:
		return `token_decls_for_prec_1`
	case ProductionTokenDeclsForPrec2:
		return `token_decls_for_prec_2`
	case ProductionTokenDeclsForPrec3:
		return `token_decls_for_prec_3`
	case ProductionTokenDeclForPrec_11:
		return `token_decl_for_prec.1_1`
	case ProductionTokenDeclForPrec_12:
		return `token_decl_for_prec.1_2`
	case ProductionTokenDeclForPrec1:
		return `token_decl_for_prec_1`
	case ProductionTokenDeclForPrec2:
		return `token_decl_for_prec_2`
	case ProductionSymbolDecls1:
		return `symbol_decls_1`
	case ProductionSymbolDecls2:
		return `symbol_decls_2`
	case ProductionSymbolDecls3:
		return `symbol_decls_3`
	case ProductionSymbols_11:
		return `symbols.1_1`
	case ProductionSymbols_12:
		return `symbols.1_2`
	case ProductionGrammar1:
		return `grammar_1`
	case ProductionGrammar2:
		return `grammar_2`
	case ProductionRulesOrGrammarDeclaration1:
		return `rules_or_grammar_declaration_1`
	case ProductionRulesOrGrammarDeclaration2:
		return `rules_or_grammar_declaration_2`
	case ProductionRulesOrGrammarDeclaration3:
		return `rules_or_grammar_declaration_3`
	case ProductionRules1:
		return `rules_1`
	case ProductionRhses_11:
		return `rhses.1_1`
	case ProductionRhses_12:
		return `rhses.1_2`
	case ProductionRhses_13:
		return `rhses.1_3`
	case ProductionRhs1:
		return `rhs_1`
	case ProductionRhs2:
		return `rhs_2`
	case ProductionRhs3:
		return `rhs_3`
	case ProductionRhs4:
		return `rhs_4`
	case ProductionRhs5:
		return `rhs_5`
	case ProductionRhs6:
		return `rhs_6`
	case ProductionRhs7:
		return `rhs_7`
	case ProductionRhs8:
		return `rhs_8`
	case ProductionRhs9:
		return `rhs_9`
	case ProductionRhs10:
		return `rhs_10`
	case ProductionNamedRef_opt1:
		return `named_ref.opt_1`
	case ProductionNamedRef_opt2:
		return `named_ref.opt_2`
	case ProductionVariable1:
		return `variable_1`
	case ProductionValue1:
		return `value_1`
	case ProductionValue2:
		return `value_2`
	case ProductionValue3:
		return `value_3`
	case ProductionValue4:
		return `value_4`
	case ProductionId1:
		return `id_1`
	case ProductionId2:
		return `id_2`
	case ProductionIdColon1:
		return `id_colon_1`
	case ProductionSymbol1:
		return `symbol_1`
	case ProductionSymbol2:
		return `symbol_2`
	case ProductionStringAsId1:
		return `string_as_id_1`
	case ProductionEpilogue_opt1:
		return `epilogue.opt_1`
	case ProductionEpilogue_opt2:
		return `epilogue.opt_2`
	default:
		return "unknown"
	}
}

// Symbol is either a terminal or a nonterminal. The most significant bit is used to signal a
// nonterminal. The maximum terminal or nonterminal index which can be stored is 32767.
type Symbol uint16

const (
	// symbolNonterminalBit is the most significant bit which is set when the Symbol stores a nonterminal.
	symbolNonterminalBit = 1 << 15

	// symbolMask is the bitmask for selecting only the value from Symbol.
	symbolMask = symbolNonterminalBit - 1
)

// NewTerminal creates a new Symbol for a terminal.
func NewTerminal(terminal Token) Symbol {
	return Symbol(terminal)
}

// NewNonterminal creates a new Symbol for a nonterminal.
func NewNonterminal(nonterminal Nonterminal) Symbol {
	return Symbol(symbolNonterminalBit | nonterminal)
}

// Terminal returns the terminal value of the Symbol. The boolean reports if the value is in fact a terminal.
func (s Symbol) Terminal() (Token, bool) {
	return Token(s & symbolMask), s&symbolNonterminalBit == 0
}

// Nonterminal returns the nonterminal value of the Symbol. The boolean reports if the value is in fact a nonterminal.
func (s Symbol) Nonterminal() (Nonterminal, bool) {
	return Nonterminal(s & symbolMask), s&symbolNonterminalBit != 0
}

// Symbol implements fmt.Stringer.
var _ fmt.Stringer = (*Symbol)(nil)

// String returns what the symbol is and the name the grammar spells it with.
func (s Symbol) String() string {
	nonterminal, ok := s.Nonterminal()
	if ok {
		return fmt.Sprintf("nonterminal %s", nonterminal)
	}
	terminal, _ := s.Terminal()
	return fmt.Sprintf("terminal %s", terminal)
}

// Node is a single node of the parse tree.
type Node struct {
	// Symbol is the terminal or nonterminal this node stands for.
	Symbol Symbol

	// Lexeme are the bytes of the terminal, as a view into the source rather than a copy of it. Empty for a
	// nonterminal and for the error symbol, which no input produced.
	Lexeme []byte

	// Children are the nodes of the right hand side of the production which was reduced to this node. Empty for a
	// terminal.
	Children []Node

	// Production is the production which was reduced to this node. NoProduction for a terminal, which no
	// production reduces to.
	Production Production
}

var (
	// ErrInternal marks a defect of the parser itself, which ends the parse.
	ErrInternal = errors.New("internal parser error")

	// ErrSyntax marks an error in the input: a token which the grammar does not allow at the position it was found at.
	// Those are the errors the parser recovers from when the grammar marks places to resume at with the error symbol,
	// so Parse can return several of them joined together.
	ErrSyntax = errors.New("syntax error")
)

// Error is a single parse error. Parse errors are returned by Parse rather than raised, so reporting many of them
// costs nothing.
type Error struct {
	// Token is the token the parse stopped on.
	Token Token

	// ByteOffset is the start of that token in bytes from the start of the source.
	ByteOffset int

	// Line is the line that token starts on, counted from one.
	Line int

	// Column is the column that token starts on, counted from one.
	Column int

	// Lexeme are the bytes of that token.
	Lexeme []byte

	// FilePath is the file path the scanner was given.
	FilePath string

	// Cause is what is wrong, without the position in front of it.
	Cause error
}

// Error implements error
var _ error = (*Error)(nil)

// Error returns an string describing this error.
func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: %s", e.FilePath, e.Line, e.Column, e.Cause)
}

func (e *Error) Unwrap() error {
	return e.Cause
}

// errorRecoveryShifts is the number of tokens which have to be shifted after a syntax error before the parser reports
// errors again. Suppressing the errors in between keeps a single mistake in the input from producing an avalanche of
// messages which are all consequences of the first one. It is the number of tokens yacc and GNU Bison use, see
// section 7 "Error Handling" of the yacc report.
const errorRecoveryShifts = 3

// arenaChunkSize is the number of nodes the arena allocator hands out from a single chunk. A parse which needs more
// nodes than one chunk holds takes further chunks of the same size and keeps them for the parses after it.
const arenaChunkSize = 16 * 1024

// initialStackCapacity is how many entries the stacks start with room for. They grow as a deeper parse needs them to.
const initialStackCapacity = 64

// The parse table is held in lookup tables. A token is translated into the column of the action table which holds the
// decisions for it, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao. The
// gotos are held the same way, with the nonterminal as the column.
//
// The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the action
// table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the tables.
//
// The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
// range check of its own.
const (
	// actionKindBits is the number of low bits of an action which hold what it does. The value it carries sits above
	// them.
	actionKindBits = 2

	// actionKindMask selects out of an action what it does.
	actionKindMask = 3

	// actionKindShift shifts the terminal and continues in the state the action carries.
	actionKindShift = 0

	// actionKindReduce reduces by the production the action carries.
	actionKindReduce = 1

	// actionKindAccept ends the parse successfully, the input having been reduced to the start symbol.
	actionKindAccept = 2

	// actionKindError rejects the terminal as a syntax error.
	actionKindError = 3

	// noTerminalColumn is the column a token gets which is no terminal of this grammar. No state has an entry in it,
	// so a lookup falls through to the default action of the state.
	noTerminalColumn = 0

	// errorTerminalColumn is the column holding the shifts of the error symbol, where the recovery reads the state to
	// resume in.
	errorTerminalColumn = 2
)

var (
	// terminalColumnByToken translates a token into the column of the action table which holds the decisions for it.
	//
	// The entries are indexed by the token constants themselves, which lets the compiler place each of them at
	// whatever value the scanner gave it. Neither generator has to know the numbering of the other because of that.
	// A token the grammar does not have is not named here at all and keeps the noTerminalColumn every unnamed index
	// holds.
	terminalColumnByToken = [...]uint8{
		EndToken:                           1,
		ErrorToken:                         2,
		TokenString:                        3,
		TokenTstring:                       4,
		TokenPercentToken:                  5,
		TokenPercentNterm:                  6,
		TokenPercentType:                   7,
		TokenPercentDestructor:             8,
		TokenPercentPrinter:                9,
		TokenPercentLeft:                   10,
		TokenPercentRight:                  11,
		TokenPercentNonassoc:               12,
		TokenPercentPrecedence:             13,
		TokenPercentPrec:                   14,
		TokenPercentDprec:                  15,
		TokenPercentMerge:                  16,
		TokenPercentCode:                   17,
		TokenPercentDefaultPrec:            18,
		TokenPercentDefine:                 19,
		TokenPercentErrorVerbose:           20,
		TokenPercentExpect:                 21,
		TokenPercentExpectRr:               22,
		TokenPercentFilePrefix:             23,
		TokenPercentFlag:                   24,
		TokenPercentGlrParser:              25,
		TokenPercentHeader:                 26,
		TokenPercentInitialAction:          27,
		TokenPercentLanguage:               28,
		TokenPercentNamePrefix:             29,
		TokenPercentNoDefaultPrec:          30,
		TokenPercentNoLines:                31,
		TokenPercentNondeterministicParser: 32,
		TokenPercentOutput:                 33,
		TokenPercentPureParser:             34,
		TokenPercentRequire:                35,
		TokenPercentSkeleton:               36,
		TokenPercentStart:                  37,
		TokenPercentTokenTable:             38,
		TokenPercentVerbose:                39,
		TokenPercentYacc:                   40,
		TokenBracedCode:                    41,
		TokenBracedPredicate:               42,
		TokenBracketedId:                   43,
		TokenCharLiteral:                   44,
		TokenColon:                         45,
		TokenEpilogue:                      46,
		TokenEqual:                         47,
		TokenId:                            48,
		TokenIdColon:                       49,
		TokenPercentPercent:                50,
		TokenPipe:                          51,
		TokenPrologue:                      52,
		TokenSemicolon:                     53,
		TokenTag:                           54,
		TokenTagAny:                        55,
		TokenTagNone:                       56,
		TokenIntLiteral:                    57,
		TokenPercentParam:                  58,
		TokenPercentUnion:                  59,
		TokenPercentEmpty:                  60,
	}

	// actionBase maps a state to the displacement of its row within actionNext.
	actionBase = [164]uint8{
		4, 2, 0, 4, 16, 46, 46, 1, 4, 4, 4, 4, 4, 4, 3, 4,
		6, 4, 26, 41, 13, 4, 4, 38, 5, 39, 40, 4, 4, 4, 44, 4,
		98, 107, 45, 4, 4, 4, 69, 4, 4, 72, 68, 4, 4, 76, 4, 67,
		4, 4, 4, 64, 65, 64, 4, 63, 4, 65, 4, 45, 70, 45, 4, 4,
		4, 4, 86, 4, 85, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
		45, 77, 4, 78, 55, 4, 4, 91, 4, 96, 4, 97, 88, 45, 92, 45,
		4, 63, 4, 64, 64, 4, 4, 11, 45, 45, 4, 4, 4, 4, 4, 4,
		4, 4, 93, 4, 4, 4, 95, 4, 4, 4, 4, 4, 88, 4, 4, 4,
		45, 45, 4, 4, 64, 4, 4, 4, 45, 4, 4, 4, 45, 56, 81, 4,
		4, 45, 90, 94, 99, 100, 4, 4, 4, 104, 91, 81, 4, 4, 4, 4,
		4, 91, 4, 4,
	}

	// actionNext holds the action of every entry. The action a state has for a column lives at
	// actionBase[state] + column, but only if actionCheck confirms the cell belongs to that column.
	actionNext = [168]uint16{
		0, 0, 16, 12, 232, 20, 24, 28, 32, 36, 40, 44, 48, 52, 232, 532,
		284, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112,
		116, 120, 124, 128, 132, 136, 140, 144, 148, 288, 300, 304, 260, 196, 296, 308,
		232, 200, 152, 264, 156, 160, 268, 236, 473, 324, 164, 168, 20, 24, 28, 32,
		36, 40, 44, 48, 52, 192, 232, 324, 56, 60, 20, 24, 28, 32, 36, 40,
		44, 48, 52, 276, 232, 108, 56, 60, 432, 196, 196, 232, 136, 200, 200, 580,
		584, 588, 280, 108, 204, 312, 592, 596, 328, 456, 136, 572, 196, 576, 316, 196,
		200, 352, 168, 200, 360, 368, 328, 400, 408, 372, 213, 600, 420, 196, 436, 428,
		168, 200, 448, 452, 196, 440, 468, 604, 200, 476, 480, 548, 552, 608, 484, 488,
		492, 644, 516, 628, 632, 0, 0, 0, 0, 0, 0, 0, 636, 640, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
	}

	// actionCheck holds the column every cell of actionNext belongs to. A cell no state occupies holds
	// 61, which is one past the highest column in use and can never be asked for.
	actionCheck = [168]uint8{
		61, 61, 2, 1, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 3, 4,
		3, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
		32, 33, 34, 35, 36, 37, 38, 39, 40, 3, 3, 3, 41, 44, 41, 3,
		3, 48, 50, 48, 52, 53, 48, 54, 1, 2, 58, 59, 5, 6, 7, 8,
		9, 10, 11, 12, 13, 53, 3, 2, 17, 18, 5, 6, 7, 8, 9, 10,
		11, 12, 13, 57, 3, 30, 17, 18, 3, 44, 44, 3, 37, 48, 48, 14,
		15, 16, 57, 30, 54, 3, 21, 22, 49, 50, 37, 51, 44, 53, 3, 44,
		48, 41, 59, 48, 48, 41, 49, 54, 57, 54, 41, 42, 54, 44, 41, 41,
		59, 48, 53, 53, 44, 48, 43, 54, 48, 41, 41, 46, 45, 60, 54, 55,
		56, 41, 54, 57, 54, 61, 61, 61, 61, 61, 61, 61, 57, 57, 61, 61,
		61, 61, 61, 61, 61, 61, 61, 61,
	}

	// defaultActionByState holds the action a state takes for every column it has no entry of its own for. A state
	// which has none carries the error action.
	defaultActionByState = [164]uint16{
		9, 3, 3, 2, 3, 3, 3, 3, 153, 157, 189, 193, 197, 201, 3, 137,
		3, 37, 3, 3, 3, 25, 53, 205, 3, 3, 3, 141, 69, 73, 3, 85,
		3, 3, 3, 97, 101, 105, 3, 21, 113, 3, 161, 13, 17, 3, 125, 3,
		109, 453, 449, 3, 177, 253, 265, 277, 173, 249, 469, 3, 181, 325, 461, 337,
		465, 145, 3, 429, 433, 41, 45, 49, 209, 33, 57, 61, 65, 77, 89, 93,
		129, 3, 457, 3, 3, 345, 353, 421, 121, 81, 165, 3, 3, 3, 185, 297,
		309, 277, 321, 257, 3, 269, 281, 285, 329, 3, 341, 149, 441, 445, 437, 29,
		361, 357, 3, 349, 5, 425, 3, 117, 169, 237, 241, 245, 133, 221, 233, 229,
		301, 3, 313, 317, 261, 293, 273, 289, 333, 477, 381, 225, 305, 365, 369, 381,
		377, 3, 3, 3, 3, 3, 393, 217, 397, 3, 421, 373, 401, 405, 409, 413,
		417, 421, 385, 389,
	}

	// gotoBase maps a state to the displacement of its row within gotoNext.
	gotoBase = [164]uint8{
		9, 9, 3, 9, 9, 13, 2, 9, 9, 9, 9, 9, 9, 9, 9, 9,
		9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
		9, 9, 23, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 6,
		9, 9, 9, 11, 9, 7, 9, 9, 9, 9, 9, 24, 9, 14, 9, 9,
		9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
		14, 9, 9, 9, 4, 9, 9, 9, 9, 9, 9, 9, 15, 0, 9, 1,
		9, 33, 9, 7, 12, 9, 9, 16, 14, 29, 9, 9, 9, 9, 9, 9,
		9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9,
		1, 5, 9, 9, 7, 9, 9, 9, 14, 9, 9, 9, 1, 9, 19, 26,
		9, 21, 9, 9, 9, 9, 9, 9, 9, 9, 27, 19, 9, 9, 9, 9,
		9, 28, 9, 9,
	}

	// gotoNext holds the state a goto leads to. The goto a state has for a nonterminal lives at
	// gotoBase[state] + nonterminal, but only if gotoCheck confirms the cell belongs to that nonterminal.
	gotoNext = [72]uint8{
		0, 0, 0, 0, 0, 0, 0, 0, 44, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 57, 0, 0, 139, 128, 0, 130, 101, 0, 140, 99, 132, 0, 115,
		0, 0, 97, 97, 55, 98, 98, 97, 97, 55, 98, 98, 127, 55, 55, 55,
		80, 104, 106, 127, 131, 135, 136, 154, 155, 156, 162, 163, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
	}

	// gotoCheck holds the nonterminal every cell of gotoNext belongs to. A cell no state occupies holds
	// 39, which is one past the highest nonterminal and can never be asked for.
	gotoCheck = [72]uint8{
		39, 39, 39, 39, 39, 39, 39, 39, 5, 39, 39, 39, 39, 39, 39, 39,
		39, 39, 16, 39, 39, 13, 22, 39, 23, 18, 39, 22, 17, 17, 39, 27,
		39, 39, 34, 34, 34, 37, 37, 34, 34, 34, 37, 37, 36, 34, 34, 34,
		25, 25, 36, 36, 19, 37, 25, 36, 30, 36, 31, 31, 39, 39, 39, 39,
		39, 39, 39, 39, 39, 39, 39, 39,
	}

	// defaultGotoByNonterminal holds the state a goto on a nonterminal leads to for every state gotoNext has no entry
	// for.
	defaultGotoByNonterminal = [39]uint8{
		0, 1, 2, 43, 89, 83, 45, 91, 46, 47, 73, 153, 124, 125, 126, 56,
		52, 53, 54, 103, 134, 94, 95, 96, 60, 61, 84, 85, 86, 141, 142, 118,
		68, 111, 62, 87, 63, 64, 116,
	}

	// popCountByProduction holds how many symbols a reduction takes off the stacks, which is the length of the right
	// hand side.
	popCountByProduction = [120]uint8{
		2, 4, 0, 2, 1, 1, 1, 3, 2, 1, 2, 2, 2, 1, 2, 2,
		2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1,
		2, 3, 1, 1, 2, 3, 1, 1, 0, 1, 3, 2, 2, 2, 2, 1,
		1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
		2, 3, 1, 2, 3, 0, 1, 0, 1, 1, 1, 2, 3, 1, 2, 2,
		1, 1, 2, 3, 1, 2, 1, 2, 1, 2, 2, 4, 1, 3, 2, 0,
		3, 4, 2, 2, 3, 3, 3, 3, 3, 0, 1, 1, 0, 1, 1, 1,
		1, 1, 1, 1, 1, 1, 0, 2,
	}

	// nonterminalByProduction holds the nonterminal on the left hand side of a production.
	nonterminalByProduction = [120]uint8{
		0, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
		3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 5,
		5, 5, 5, 5, 5, 5, 6, 6, 7, 7, 5, 8, 8, 8, 8, 9,
		9, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 14, 15, 16,
		16, 16, 17, 17, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 23,
		23, 24, 24, 24, 25, 25, 26, 26, 27, 27, 27, 28, 29, 29, 29, 30,
		30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 32, 33, 33, 33, 33,
		34, 34, 35, 36, 36, 37, 38, 38,
	}
)

// Parser provides the parser implementation.
type Parser struct {
	// stateStack holds the states of the running parse, the current one on top.
	stateStack []int

	// nodeStack holds one node per symbol shifted or reduced so far.
	nodeStack []Node

	// arenaChunks holds every chunk of nodes the parser has allocated so far, in the order they are handed out. A
	// parse starts over at the first chunk instead of allocating new ones, so only a parse which needs more nodes
	// than every parse before it adds a chunk. Parse invalidates the tree of the parse before it in any case, so
	// handing the memory of that tree out again takes away nothing a caller could rely on.
	arenaChunks   [][]Node
	arenaChunkIdx int

	// arenaAllocator is the chunk nodes are handed out from at the moment, which aliases arenaChunks[arenaChunkIdx].
	// Keeping it here lets allocateNodes read the room left in the chunk straight off the parser.
	arenaAllocator    []Node
	arenaAllocatorTop int

	// errors collects the syntax errors of the current parse, which Parse returns joined together.
	errors []error

	// errorRecoveryShiftsRemaining counts down the tokens which still have to be shifted before syntax errors are
	// reported again. It is zero while the parser is in sync with the input and errorRecoveryShifts right after the
	// error symbol was shifted.
	errorRecoveryShiftsRemaining int
}

// NewParser creates a new parser.
func NewParser() *Parser {
	parser := Parser{
		stateStack:  make([]int, 0, initialStackCapacity),
		nodeStack:   make([]Node, 0, initialStackCapacity),
		arenaChunks: [][]Node{make([]Node, arenaChunkSize)},
	}
	parser.resetArena()
	return &parser
}

// errAccept is used to signal the successful end of the parse. It is filtered out by the main parse loop and not
// exposed to the user.
var errAccept = errors.New("accept")

// Parse executes a parse on the tokens provided by the scanner and returns a parse tree or an error. Parse can be
// called multiple times with different scanners to re-use the memory already allocated by the parser.
//
// When the grammar marks places to resume at with the error symbol, the parser recovers from a syntax error and carries
// on parsing. Parse then returns both a tree and an error: the tree of the input as far as the parser could make sense
// of it, with a node for the error symbol at every place it resumed at, and all syntax errors it found joined into one
// error. A tree is only returned if the parse reached its end, otherwise the recovery gave up somewhere in the middle
// and there is no tree to speak of.
//
// The errors are joined even when there is only one of them, so the shape of the returned error does not depend on how
// many errors the parse found. Use errors.Is and errors.As to get at them, both of which look into a join.
func (p *Parser) Parse(scanner TokenSource) (Node, error) {
	p.resetArena()

	p.stateStack = p.stateStack[:0]
	p.stateStack = append(p.stateStack, 0)
	p.nodeStack = p.nodeStack[:0]
	p.errors = p.errors[:0]
	p.errorRecoveryShiftsRemaining = 0

	// A source with no tokens at all reports false right away. That is not an error: the token is the end of input
	// either way, and whether a parse of nothing but that is legal is for the table to decide.
	scanner.Next()

	for {
		err := p.step(scanner)
		if err == nil {
			continue
		}
		if errors.Is(err, errAccept) {
			// What is left on the node stack is the start symbol, which is the root of the tree.
			return p.nodeStack[0], errors.Join(p.errors...)
		}
		if !errors.Is(err, ErrSyntax) {
			// Only an error in the input can be recovered from.
			p.errors = append(p.errors, err)
			return Node{}, errors.Join(p.errors...)
		}
		if p.errorRecoveryShiftsRemaining == 0 {
			// While recovering, the parser is not in sync with the input, so the errors it runs into there follow
			// from the one already reported.
			p.errors = append(p.errors, err)
		}
		if !p.recoverFromError(scanner) {
			return Node{}, errors.Join(p.errors...)
		}
	}
}

// step performs the single action which the state on top of the stack takes for the token the scanner currently
// delivers. This is the whole automaton: everything which distinguishes one state from another is in the tables.
func (p *Parser) step(scanner TokenSource) error {
	terminal := scanner.Token()

	// A token which is no terminal of this grammar takes the default action of the state.
	column := p.terminalColumn(terminal)

	state := p.currentState()
	cellIdx := uint32(actionBase[state]) + column
	action := uint32(defaultActionByState[state])
	if uint32(actionCheck[cellIdx]) == column {
		// An entry the state has of its own beats its default action, which is what keeps a token the grammar
		// rejects on purpose an error even in a state which reduces on everything else.
		action = uint32(actionNext[cellIdx])
	}

	switch action & actionKindMask {
	case actionKindShift:
		p.stateStack = append(p.stateStack, int(action>>actionKindBits))
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: scanner.Lexeme(),
		})
		scanner.Next()
		if p.errorRecoveryShiftsRemaining > 0 {
			// Getting tokens of the input shifted again is what makes the parser trust its position.
			p.errorRecoveryShiftsRemaining--
		}
		return nil
	case actionKindReduce:
		p.reduce(action >> actionKindBits)
		return nil
	case actionKindAccept:
		// The parse is successfully finished.
		return errAccept
	case actionKindError:
		return p.raiseError(scanner, fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	default:
		return p.raiseError(scanner, fmt.Errorf("%w: unexpected action %d in state %d", ErrInternal, action, state))
	}
}

// reduce replaces the right hand side of the given production on the stacks with the nonterminal on its left hand side,
// and continues in the state the goto of the uncovered state leads to.
func (p *Parser) reduce(productionIdx uint32) {
	popCount := int(popCountByProduction[productionIdx])
	nonterminal := uint32(nonterminalByProduction[productionIdx])

	p.stateStack = p.stateStack[:len(p.stateStack)-popCount]

	state := p.currentState()
	// A state without a goto of its own on the nonterminal goes where most states go with it. A state which a
	// reduction uncovers always has one, so there is no case for a nonterminal missing from both.
	gotoState := uint32(defaultGotoByNonterminal[nonterminal])
	cellIdx := uint32(gotoBase[state]) + nonterminal
	if uint32(gotoCheck[cellIdx]) == nonterminal {
		gotoState = uint32(gotoNext[cellIdx])
	}
	p.stateStack = append(p.stateStack, int(gotoState))

	newNode := Node{
		Symbol:     NewNonterminal(Nonterminal(nonterminal)),
		Production: Production(productionIdx),
	}
	if popCount != 0 {
		newNode.Children = p.allocateNodes(popCount)
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-popCount:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-popCount]
	}
	p.nodeStack = append(p.nodeStack, newNode)
}

// recoverFromError puts the parser back where it can carry on with the remaining input after a syntax error. Once it
// reports false, the parse is given up.
//
// This is the panic mode recovery of section 9 "Error Recovery" of "LR Parsing" by Aho and Johnson, in the shape which
// section 7 "Error Handling" of the yacc report describes: the parser pops its stack until it reaches a state which can
// shift the error symbol - a place the grammar marked as one to resume at - and shifts the symbol there. Everything the
// popped states had parsed is discarded with them.
//
// The token which caused the error is kept for the resumed state to look at, because that state is usually waiting for
// exactly it: in a production like "{" @error "}" it is the closing brace which ends the recovery. Only when the parse
// fails on that very same token again is the token discarded, which is what an untouched countdown of tokens to shift
// tells us. Popping and discarding in the same handler is what guarantees progress: every round of recovery either gets
// the parse going again or consumes one token of the input, so a parse cannot get stuck between the two.
func (p *Parser) recoverFromError(scanner TokenSource) bool {
	if p.errorRecoveryShiftsRemaining == errorRecoveryShifts {
		// Nothing was shifted since the last error, so the parser is failing on the token it already failed on.
		if scanner.Token() == EndToken {
			// The end of input is the one token which cannot be discarded.
			return false
		}
		scanner.Next()
	}
	p.errorRecoveryShiftsRemaining = errorRecoveryShifts

	for {
		if nextState, ok := p.errorShiftState(p.currentState()); ok {
			// Shift the error symbol. Its node stands for the dropped part of the input and has no lexeme.
			p.stateStack = append(p.stateStack, nextState)
			p.nodeStack = append(p.nodeStack, Node{
				Symbol: NewTerminal(ErrorToken),
			})
			return true
		}
		if len(p.stateStack) == 1 {
			// Only the state the parse started in is left and it cannot shift the error symbol either.
			return false
		}
		// The state cannot resume here, so it is dropped together with what it had parsed. One state carries one
		// node, so dropping one drops one.
		p.stateStack = p.stateStack[:len(p.stateStack)-1]
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-1]
	}
}

// currentState returns the state on top of the stack, which is the one the parse is in.
func (p *Parser) currentState() int {
	return p.stateStack[len(p.stateStack)-1]
}

// terminalColumn returns the column of the action table which holds the decisions for the given token. A token the
// grammar does not have, and one outside the range the scanner promises, both get noTerminalColumn.
func (p *Parser) terminalColumn(terminal Token) uint32 {
	if uint32(terminal) < uint32(len(terminalColumnByToken)) {
		return uint32(terminalColumnByToken[terminal])
	}
	return noTerminalColumn
}

// errorShiftState returns the state to continue in when the error symbol is shifted in the given state, and reports if
// the state can shift it at all. The states which can are the places the grammar marked to resume at after a syntax
// error.
//
// The default action of the state is deliberately not consulted, because only an entry the state has of its own is a
// place to resume at.
func (p *Parser) errorShiftState(state int) (int, bool) {
	cellIdx := uint32(actionBase[state]) + errorTerminalColumn
	if uint32(actionCheck[cellIdx]) != errorTerminalColumn {
		return 0, false
	}
	action := uint32(actionNext[cellIdx])
	if action&actionKindMask != actionKindShift {
		return 0, false
	}
	return int(action >> actionKindBits), true
}

// raiseError returns an error with the given cause at the position the scanner is at.
func (p *Parser) raiseError(scanner TokenSource, cause error) error {
	return &Error{
		Token:      scanner.Token(),
		ByteOffset: scanner.ByteOffset(),
		Line:       scanner.Line(),
		Column:     scanner.Column(),
		Lexeme:     scanner.Lexeme(),
		FilePath:   scanner.FilePath(),
		Cause:      cause,
	}
}

// allocateNodes provides an arena allocator for slices of Node.
func (p *Parser) allocateNodes(n int) []Node {
	if p.arenaAllocatorTop+n > len(p.arenaAllocator) {
		p.nextArenaChunk(n)
	}
	nodes := p.arenaAllocator[p.arenaAllocatorTop : p.arenaAllocatorTop+n]
	p.arenaAllocatorTop += n
	return nodes
}

// nextArenaChunk moves the arena on to the chunk after the current one, to serve a request of n nodes which the
// current chunk has no room left for. Where an earlier parse left a chunk behind, that chunk is handed out again, so
// a parser settles on the number of chunks its largest parse needed and allocates none after that.
//
// A reused chunk is not cleared. Every slice allocateNodes returns is filled completely by its caller before anything
// reads it, so what an earlier parse left behind in the chunk is never observable.
func (p *Parser) nextArenaChunk(n int) {
	p.arenaChunkIdx++
	if p.arenaChunkIdx == len(p.arenaChunks) {
		p.arenaChunks = append(p.arenaChunks, make([]Node, max(n, arenaChunkSize)))
	} else if len(p.arenaChunks[p.arenaChunkIdx]) < n {
		// A single reduction which takes more nodes than a chunk holds gets a chunk sized to itself, so a chunk kept
		// from an earlier parse is not guaranteed to have room for a later request.
		p.arenaChunks[p.arenaChunkIdx] = make([]Node, n)
	}
	p.arenaAllocator = p.arenaChunks[p.arenaChunkIdx]
	p.arenaAllocatorTop = 0
}

// resetArena puts the arena back to where it starts a parse, handing out from the beginning of the first chunk again.
func (p *Parser) resetArena() {
	p.arenaChunkIdx = 0
	p.arenaAllocator = p.arenaChunks[0]
	p.arenaAllocatorTop = 0
}
