// Code generated by GoLR. DO NOT EDIT.

package parser

import (
	"errors"
	"fmt"
)

// Token is the data type representing all terminal symbols.
type Token int

const (
	// InvalidToken is a terminal which does not exist. It is used for situations where no token was found.
	InvalidToken Token = iota

	// EndToken is a terminal which does not exist. It is used for situations where the end of the source was reached.
	EndToken

	TokenWhitespace
	TokenInteger
	TokenPlus
	TokenMinus
	TokenMultiply
	TokenDivide
	TokenLparen
	TokenRparen
	TokenUminus
)

// Token implements fmt.Stringer.
var _ fmt.Stringer = (*Token)(nil)

// String returns a string representation of the terminal.
func (t Token) String() string {
	switch t {
	case InvalidToken:
		return "invalid token"
	case EndToken:
		return "end token"
	case TokenWhitespace:
		return `WHITESPACE`
	case TokenInteger:
		return `INTEGER`
	case TokenPlus:
		return `PLUS`
	case TokenMinus:
		return `MINUS`
	case TokenMultiply:
		return `MULTIPLY`
	case TokenDivide:
		return `DIVIDE`
	case TokenLparen:
		return `LPAREN`
	case TokenRparen:
		return `RPAREN`
	case TokenUminus:
		return `UMINUS`
	default:
		return "unknown"
	}
}

// TokenSkipper wraps a scanner and skips all tokens which were marked for skipping. This is usually used for skipping
// whitespaces and comments.
type TokenSkipper struct {
	scanner *Scanner
}

// NewTokenSkipper creates a new TokenSkipper by wrapping the given Scanner.
func NewTokenSkipper(scanner *Scanner) *TokenSkipper {
	return &TokenSkipper{
		scanner: scanner,
	}
}

// Reset updates the scanner with the given source and starts scanning at the given offset. This can be useful for
// situations where you only want to re-tokenize parts of the source after the source has been changed.
func (s *TokenSkipper) Reset(source []byte, offset int) {
	s.scanner.Reset(source, offset)
}

// Token returns the current token.
func (s *TokenSkipper) Token() Token {
	return s.scanner.Token()
}

// ByteOffset returns the start of the token in bytes from the source start.
// When Next() returned false, it returns the location after the last byte.
func (s *TokenSkipper) ByteOffset() int {
	return s.scanner.ByteOffset()
}

// Line returns the line the token is located on.
func (s *TokenSkipper) Line() int {
	return s.scanner.Line()
}

// Column returns the column the token is located on.
func (s *TokenSkipper) Column() int {
	return s.scanner.Column()
}

// Lexeme returns the bytes which make up the token.
func (s *TokenSkipper) Lexeme() []byte {
	return s.scanner.Lexeme()
}

// FilePath returns the file path of the file being parsed. This information can be useful in error messages.
func (s *TokenSkipper) FilePath() string {
	return s.scanner.FilePath()
}

// Next consumes tokens until it found a token which should not be skipped.
func (s *TokenSkipper) Next() bool {
	for {
		if !s.scanner.Next() {
			return false
		}
		switch s.scanner.Token() {
		case TokenWhitespace:
			continue
		default:
			return true
		}
	}
}

// Scanner reads source code and returns tokens.
type Scanner struct {
	source []byte

	lexemeStartIdx int
	lexemeEndIdx   int
	lexemePeekIdx  int

	line   int
	column int

	state int
	token Token

	filePath string
}

// NewScanner creates a new instance of the scanner with the given source. The filePath parameter is used to
// return information about which file has an error. You can provide any string you want if you don't have a file.
func NewScanner(source []byte, filePath string) *Scanner {
	scanner := Scanner{
		filePath: filePath,
	}
	scanner.Reset(source, 0)
	return &scanner
}

// Reset updates the scanner with the given source and starts scanning at the given offset. This can be useful for
// situations where you only want to re-tokenize parts of the source after the source has been changed.
func (s *Scanner) Reset(source []byte, offset int) {
	s.source = source

	s.lexemeStartIdx = 0
	s.lexemeEndIdx = offset

	s.line = 1
	s.column = 1

	s.token = InvalidToken
}

// Token returns the current token.
func (s *Scanner) Token() Token {
	return s.token
}

// ByteOffset returns the start of the token in bytes from the source start.
// When Next() returned false, it returns the location after the last byte.
func (s *Scanner) ByteOffset() int {
	return s.lexemeStartIdx
}

// Line returns the line the token is located on.
func (s *Scanner) Line() int {
	return s.line
}

// Column returns the column the token is located on.
func (s *Scanner) Column() int {
	return s.column
}

// Lexeme returns the bytes which make up the token.
func (s *Scanner) Lexeme() []byte {
	return s.source[s.lexemeStartIdx:s.lexemeEndIdx]
}

// FilePath returns the file path of the file being parsed. This information can be useful in error messages.
func (s *Scanner) FilePath() string {
	return s.filePath
}

// Next consumes characters until it found the next token.
func (s *Scanner) Next() bool {
	s.updateLineAndColumn(s.source[s.lexemeStartIdx:s.lexemeEndIdx])
	s.lexemeStartIdx = s.lexemeEndIdx
	s.state = 0

	for s.lexemePeekIdx = s.lexemeEndIdx; s.lexemePeekIdx < len(s.source); s.lexemePeekIdx++ {
		if err := s.dispatchState(); err != nil {
			break
		}
	}
	if s.lexemePeekIdx == len(s.source) {
		// We need to capture the last character of the source.
		s.dispatchEOF()
	}

	if s.lexemeStartIdx < s.lexemeEndIdx {
		// We found a token.
		return true
	}

	if len(s.source) <= s.lexemeStartIdx {
		// We have reached the end of the source.
		s.token = EndToken
		return false
	}

	// We found some characters which do not form a token. We need to emit an invalid token for them.
	s.token = InvalidToken
	s.lexemeEndIdx = s.lexemePeekIdx + 1
	return true
}

// updateLineAndColumn updates the current line and column information by scanning the given source for newlines.
func (s *Scanner) updateLineAndColumn(source []byte) {
	for _, currByte := range source {
		if currByte == '\n' {
			s.line++
			s.column = 1
		} else {
			s.column++
		}
	}
}

// dispatchState calls the code corresponding to the current scanner state.
func (s *Scanner) dispatchState() error {
	switch s.state {
	case 0:
		return s.state0Whitespace()
	case 1:
		return s.state1Whitespace()
	case 2:
		return s.state2Integer()
	case 3:
		return s.state3Plus()
	case 4:
		return s.state4Minus()
	case 5:
		return s.state5Multiply()
	case 6:
		return s.state6Divide()
	case 7:
		return s.state7Lparen()
	case 8:
		return s.state8Rparen()
	default:
		return fmt.Errorf("unexpected scanner state %d", s.state)
	}
}

func (s *Scanner) dispatchEOF() {
	switch s.state {
	case 1:
		s.token = TokenWhitespace
		s.lexemeEndIdx = s.lexemePeekIdx
	case 2:
		s.token = TokenInteger
		s.lexemeEndIdx = s.lexemePeekIdx
	case 3:
		s.token = TokenPlus
		s.lexemeEndIdx = s.lexemePeekIdx
	case 4:
		s.token = TokenMinus
		s.lexemeEndIdx = s.lexemePeekIdx
	case 5:
		s.token = TokenMultiply
		s.lexemeEndIdx = s.lexemePeekIdx
	case 6:
		s.token = TokenDivide
		s.lexemeEndIdx = s.lexemePeekIdx
	case 7:
		s.token = TokenLparen
		s.lexemeEndIdx = s.lexemePeekIdx
	case 8:
		s.token = TokenRparen
		s.lexemeEndIdx = s.lexemePeekIdx
	}
}

var (
	// errInvalidByte is an error which is returned when no transition matches the current byte.
	errInvalidByte = errors.New("invalid byte")
)

func (s *Scanner) state0Whitespace() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == '\t':
		s.state = 1
	case nextByte == '\n':
		s.state = 1
	case nextByte == '\r':
		s.state = 1
	case nextByte == ' ':
		s.state = 1
	case nextByte == '(':
		s.state = 7
	case nextByte == ')':
		s.state = 8
	case nextByte == '*':
		s.state = 5
	case nextByte == '+':
		s.state = 3
	case nextByte == '-':
		s.state = 4
	case nextByte == '/':
		s.state = 6
	case '0' <= nextByte && nextByte <= '9':
		s.state = 2
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state1Whitespace() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenWhitespace
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == '\t':
		s.state = 1
	case nextByte == '\n':
		s.state = 1
	case nextByte == '\r':
		s.state = 1
	case nextByte == ' ':
		s.state = 1
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state2Integer() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenInteger
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case '0' <= nextByte && nextByte <= '9':
		s.state = 2
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state3Plus() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenPlus
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state4Minus() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenMinus
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state5Multiply() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenMultiply
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state6Divide() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenDivide
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state7Lparen() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenLparen
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state8Rparen() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRparen
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}
