# Code generated by GoLR. DO NOT EDIT.
#
# This file is output of GoLR. It is exempt from the conditions of GoLR's
# Apache-2.0 license and may be licensed under terms of your choosing.
# See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

"""A scanner which turns the bytes of a source into tokens."""

from enum import IntEnum
from typing import Final, Protocol

__all__ = ["Scanner", "Token", "TokenSkipper", "TokenSource", "is_skipped"]


class Token(IntEnum):
    """Every terminal symbol this scanner knows."""

    INVALID_TOKEN = 0
    """No token was found."""

    END_TOKEN = 1
    """The end of the source was reached."""

    ERROR_TOKEN = 2
    """The symbol a grammar marks its error recovery points with. No input ever produces it."""

    TOKEN_WHITESPACE = 3
    TOKEN_INTEGER = 4
    TOKEN_PLUS = 5
    TOKEN_MINUS = 6
    TOKEN_MULTIPLY = 7
    TOKEN_DIVIDE = 8
    TOKEN_LPAREN = 9
    TOKEN_RPAREN = 10
    TOKEN_UMINUS = 11

    def __str__(self) -> str:
        """Returns the name of the token, as the grammar spells it."""
        return _TOKEN_NAMES[self]


_TOKEN_NAMES: Final[dict[Token, str]] = {
    Token.INVALID_TOKEN: "invalid token",
    Token.END_TOKEN: "end token",
    Token.ERROR_TOKEN: "error token",
    Token.TOKEN_WHITESPACE: "WHITESPACE",
    Token.TOKEN_INTEGER: "INTEGER",
    Token.TOKEN_PLUS: "PLUS",
    Token.TOKEN_MINUS: "MINUS",
    Token.TOKEN_MULTIPLY: "MULTIPLY",
    Token.TOKEN_DIVIDE: "DIVIDE",
    Token.TOKEN_LPAREN: "LPAREN",
    Token.TOKEN_RPAREN: "RPAREN",
    Token.TOKEN_UMINUS: "UMINUS",
}
"""The name of every token, as the grammar spells it."""


_SKIPPED_TOKENS: Final[frozenset[Token]] = frozenset((
    Token.TOKEN_WHITESPACE,
))
"""The tokens the grammar marked for skipping."""


def is_skipped(token: Token) -> bool:
    """Reports whether the grammar marked the token for skipping, which is what the token skipper drops."""
    return token in _SKIPPED_TOKENS


class TokenSource(Protocol):
    """What a scanner offers. Both `Scanner` and `TokenSkipper` satisfy it."""

    @property
    def token(self) -> Token:
        """The current token."""
        ...

    @property
    def byte_offset(self) -> int:
        """The start of the token in bytes from the start of the source.

        After `next` returned false it is the offset one past the last byte.
        """
        ...

    @property
    def line(self) -> int:
        """The line the token starts on, counted from one."""
        ...

    @property
    def column(self) -> int:
        """The column the token starts on, counted from one."""
        ...

    @property
    def lexeme(self) -> bytes:
        """The bytes of the token."""
        ...

    @property
    def file_path(self) -> str:
        """The file path the scanner was given."""
        ...

    def reset(self, source: bytes, offset: int) -> None:
        """Scans the given source from the given byte offset on.

        Useful for re-tokenizing the part of a source which changed.
        """
        ...

    def next(self) -> bool:
        """Advances to the next token.

        Returns false when the source holds no such token any more.
        """
        ...


class TokenSkipper:
    """Skips the tokens the grammar marked for skipping, which are usually whitespace and comments.

    It wraps a scanner and offers the same members as `Scanner`.
    """

    __slots__ = ("_scanner",)

    _scanner: TokenSource
    """The wrapped scanner."""

    def __init__(self, scanner: TokenSource) -> None:
        """Creates a skipper which hands on the tokens of the given scanner."""
        self._scanner = scanner

    @property
    def token(self) -> Token:
        """The current token."""
        return self._scanner.token

    @property
    def byte_offset(self) -> int:
        """The start of the token in bytes from the start of the source.

        After `next` returned false it is the offset one past the last byte.
        """
        return self._scanner.byte_offset

    @property
    def line(self) -> int:
        """The line the token starts on, counted from one."""
        return self._scanner.line

    @property
    def column(self) -> int:
        """The column the token starts on, counted from one."""
        return self._scanner.column

    @property
    def lexeme(self) -> bytes:
        """The bytes of the token."""
        return self._scanner.lexeme

    @property
    def file_path(self) -> str:
        """The file path the scanner was given."""
        return self._scanner.file_path

    def reset(self, source: bytes, offset: int) -> None:
        """Scans the given source from the given byte offset on.

        Useful for re-tokenizing the part of a source which changed.
        """
        self._scanner.reset(source, offset)

    def next(self) -> bool:
        """Advances to the next token which is not marked for skipping.

        Returns false when the source holds no such token any more.
        """
        while self._scanner.next():
            if not is_skipped(self._scanner.token):
                return True
        return False


# The automaton is held in lookup tables. An input byte is mapped to its byte class, which is the column of the
# transition table, and the rows of that table are displaced into a single array so that the entries of one row fall
# into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao.
#
# The displaced arrays are padded so that every state and byte class lands inside them, which is why a lookup needs no
# range check of its own.

_BYTE_CLASS_BY_BYTE: Final[tuple[int, ...]] = (
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 0, 6, 0, 7,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
)
"""Maps an input byte to its byte class. Bytes which every state treats alike share a class."""

_TRANSITION_BASE: Final[tuple[int, ...]] = (
    0, 8, 2, 1, 1, 1, 1, 1, 1,
)
"""Maps a state to the displacement of its row within `_TRANSITION_NEXT`."""

_TRANSITION_NEXT: Final[tuple[int, ...]] = (
    0, 1, 7, 8, 5, 3, 4, 6, 2, 1, 2, 0, 0, 0, 0, 0,
    0,
)
"""Holds the target state of every transition.

The transition a state has on a byte class lives at `_TRANSITION_BASE[state] + byte_class`, but only if
`_TRANSITION_CHECK` confirms the cell belongs to that class.
"""

_TRANSITION_CHECK: Final[tuple[int, ...]] = (
    9, 1, 2, 3, 4, 5, 6, 7, 8, 1, 8, 9, 9, 9, 9, 9,
    9,
)
"""Holds the byte class every cell of `_TRANSITION_NEXT` belongs to.

A cell no state occupies holds 9, which is one past the highest byte class in use and can never
be asked for.
"""

_ACCEPT_TOKEN_BY_STATE: Final[tuple[Token, ...]] = (
    Token.INVALID_TOKEN,
    Token.TOKEN_WHITESPACE,
    Token.TOKEN_INTEGER,
    Token.TOKEN_PLUS,
    Token.TOKEN_MINUS,
    Token.TOKEN_MULTIPLY,
    Token.TOKEN_DIVIDE,
    Token.TOKEN_LPAREN,
    Token.TOKEN_RPAREN,
)
"""Holds the token a state accepts, or `Token.INVALID_TOKEN` for a state which does not accept."""


class Scanner:
    """Turns the bytes of a source into tokens."""

    __slots__ = (
        "_source",
        "_file_path",
        "_token",
        "_lexeme_start_idx",
        "_lexeme_end_idx",
        "_line",
        "_column",
    )

    _source: bytes
    """The bytes being scanned."""

    _file_path: str
    """The file path the scanner was given."""

    _token: Token
    """The current token."""

    _lexeme_start_idx: int
    """Index of the first byte of the current token."""

    _lexeme_end_idx: int
    """Index one past the last byte of the current token."""

    _line: int
    """The line the current token starts on, counted from one."""

    _column: int
    """The column the current token starts on, counted from one."""

    def __init__(self, source: bytes, file_path: str) -> None:
        """Creates a scanner which turns the given bytes into tokens, starting at the first of them.

        :param source: The bytes to scan.
        :param file_path: Used in error messages. Any string will do when the source is not a file.
        """
        self._file_path = file_path
        self.reset(source, 0)

    @property
    def token(self) -> Token:
        """The current token."""
        return self._token

    @property
    def byte_offset(self) -> int:
        """The start of the token in bytes from the start of the source.

        After `next` returned false it is the offset one past the last byte.
        """
        return self._lexeme_start_idx

    @property
    def line(self) -> int:
        """The line the token starts on, counted from one."""
        return self._line

    @property
    def column(self) -> int:
        """The column the token starts on, counted from one."""
        return self._column

    @property
    def lexeme(self) -> bytes:
        """The bytes of the token."""
        return self._source[self._lexeme_start_idx:self._lexeme_end_idx]

    @property
    def file_path(self) -> str:
        """The file path the scanner was given."""
        return self._file_path

    def reset(self, source: bytes, offset: int) -> None:
        """Scans the given source from the given byte offset on.

        Useful for re-tokenizing the part of a source which changed.
        """
        self._source = source

        self._lexeme_start_idx = 0
        # An offset past the end of the source would walk the line and column counters over bytes which are not
        # there. Clamping it leaves the scanner at the end of the source, where it reports the end token.
        self._lexeme_end_idx = min(offset, len(source))

        self._line = 1
        self._column = 1

        self._token = Token.INVALID_TOKEN

    def next(self) -> bool:
        """Advances to the next token. Bytes which form no token become an invalid token.

        Returns false once the end of the source is reached, which sets the token to the end token.
        """
        self._update_line_and_column(self._lexeme_start_idx, self._lexeme_end_idx)
        self._lexeme_start_idx = self._lexeme_end_idx

        source = self._source
        source_len = len(source)

        state = 0
        lexeme_peek_idx = self._lexeme_end_idx
        while True:
            # Remember every accepting state passed through, so the longest match wins over the first one.
            if _ACCEPT_TOKEN_BY_STATE[state] != Token.INVALID_TOKEN:
                self._token = _ACCEPT_TOKEN_BY_STATE[state]
                self._lexeme_end_idx = lexeme_peek_idx
            if lexeme_peek_idx == source_len:
                # The end of the source is reached, so the state it stopped in was the last one to test.
                break

            byte_class = _BYTE_CLASS_BY_BYTE[source[lexeme_peek_idx]]
            cell_idx = _TRANSITION_BASE[state] + byte_class
            if _TRANSITION_CHECK[cell_idx] != byte_class:
                # The state has no transition on this byte, so the token ends here.
                break
            state = _TRANSITION_NEXT[cell_idx]
            lexeme_peek_idx += 1

        if self._lexeme_start_idx < self._lexeme_end_idx:
            # A token was found.
            return True

        if source_len <= self._lexeme_start_idx:
            # The end of the source was reached.
            self._token = Token.END_TOKEN
            return False

        # The bytes here form no token. The invalid token ends where the automaton stopped, because the byte it could
        # not consume is where the next attempt starts. Only when the automaton consumed nothing does it cover that
        # byte, which is what keeps the scan moving forward.
        self._token = Token.INVALID_TOKEN
        self._lexeme_end_idx = max(self._lexeme_start_idx + 1, lexeme_peek_idx)
        return True

    def _update_line_and_column(self, start_idx: int, end_idx: int) -> None:
        """Advances the line and column counters over the bytes between the two indexes."""
        for byte in self._source[start_idx:end_idx]:
            if byte == 0x0A:
                self._line += 1
                self._column = 1
            else:
                self._column += 1
