// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser

import (
	"errors"
	"fmt"
)

// Nonterminal is the data type representing all nonterminal symbols.
type Nonterminal int

const (
	// AcceptNonterminal is the start symbol the generator adds around the one the grammar declares.
	// Reaching it accepts the input.
	AcceptNonterminal Nonterminal = 0

	NonterminalExpression Nonterminal = 1
)

// Nonterminal implements fmt.Stringer.
var _ fmt.Stringer = (*Nonterminal)(nil)

// String returns a string representation of the nonterminal.
func (n Nonterminal) String() string {
	switch n {
	case AcceptNonterminal:
		return `$accept`
	case NonterminalExpression:
		return `expression`
	default:
		return "unknown"
	}
}

// Production is the data type representing all productions of the grammar. It has no entry for production 0
// ($accept), which is never reduced.
type Production int

const (
	// NoProduction is the Production a terminal node carries, since no production reduces to it.
	NoProduction          Production = 0
	ProductionExpression1 Production = 1
	ProductionExpression2 Production = 2
	ProductionExpression3 Production = 3
	ProductionExpression4 Production = 4
	ProductionExpression5 Production = 5
	ProductionExpression6 Production = 6
	ProductionExpression7 Production = 7
)

// Production implements fmt.Stringer.
var _ fmt.Stringer = (*Production)(nil)

// String returns the name of the production.
func (p Production) String() string {
	switch p {
	case NoProduction:
		return "none"
	case ProductionExpression1:
		return `expression_1`
	case ProductionExpression2:
		return `expression_2`
	case ProductionExpression3:
		return `expression_3`
	case ProductionExpression4:
		return `expression_4`
	case ProductionExpression5:
		return `expression_5`
	case ProductionExpression6:
		return `expression_6`
	case ProductionExpression7:
		return `expression_7`
	default:
		return "unknown"
	}
}

// Symbol is either a terminal or a nonterminal. The most significant bit is used to signal a
// nonterminal. The maximum terminal or nonterminal index which can be stored is 32767.
type Symbol uint16

const (
	// symbolNonterminalBit is the most significant bit which is set when the Symbol stores a nonterminal.
	symbolNonterminalBit = 1 << 15

	// symbolMask is the bitmask for selecting only the value from Symbol.
	symbolMask = symbolNonterminalBit - 1
)

// NewTerminal creates a new Symbol for a terminal.
func NewTerminal(terminal Token) Symbol {
	return Symbol(terminal)
}

// NewNonterminal creates a new Symbol for a nonterminal.
func NewNonterminal(nonterminal Nonterminal) Symbol {
	return Symbol(symbolNonterminalBit | nonterminal)
}

// Terminal returns the terminal value of the Symbol. The boolean reports if the value is in fact a terminal.
func (s Symbol) Terminal() (Token, bool) {
	return Token(s & symbolMask), s&symbolNonterminalBit == 0
}

// Nonterminal returns the nonterminal value of the Symbol. The boolean reports if the value is in fact a nonterminal.
func (s Symbol) Nonterminal() (Nonterminal, bool) {
	return Nonterminal(s & symbolMask), s&symbolNonterminalBit != 0
}

// Symbol implements fmt.Stringer.
var _ fmt.Stringer = (*Symbol)(nil)

// String returns what the symbol is and the name the grammar spells it with.
func (s Symbol) String() string {
	nonterminal, ok := s.Nonterminal()
	if ok {
		return fmt.Sprintf("nonterminal %s", nonterminal)
	}
	terminal, _ := s.Terminal()
	return fmt.Sprintf("terminal %s", terminal)
}

// Node is a single node of the parse tree. It carries the span of the source it covers, which TokenSource.Text turns
// back into bytes and TokenSource.Position into a file path, a line and a column.
//
// A terminal covers its lexeme and a nonterminal covers its children. The error symbol covers what the error recovery
// threw away, up to the point it resumed at. A production with an empty right hand side has zero length at the end of
// the symbol to its left.
type Node struct {
	// Symbol is the terminal or nonterminal this node stands for.
	Symbol Symbol

	// ByteOffset is the start of the source this node covers, in bytes from the start of the source.
	ByteOffset int

	// ByteLength is the number of bytes of the source this node covers.
	ByteLength int

	// Children are the nodes of the right hand side of the production which was reduced to this node. Empty for a
	// terminal.
	Children []Node

	// Production is the production which was reduced to this node. NoProduction for a terminal, which no
	// production reduces to.
	Production Production
}

var (
	// ErrInternal marks a defect of the parser itself, which ends the parse.
	ErrInternal = errors.New("internal parser error")

	// ErrSyntax marks an error in the input: a token which the grammar does not allow at the position it was found at.
	// Those are the errors the parser recovers from when the grammar marks places to resume at with the error symbol,
	// so Parse can return several of them joined together.
	ErrSyntax = errors.New("syntax error")
)

// Error is a single parse error. Parse errors are returned by Parse rather than raised, so reporting many of them
// costs nothing.
type Error struct {
	// Token is the token the parse stopped on.
	Token Token

	// ByteOffset is the start of that token in bytes from the start of the source.
	ByteOffset int

	// Line is the line that token starts on, counted from one.
	Line int

	// Column is the column that token starts on, counted from one.
	Column int

	// Lexeme are the bytes of that token.
	Lexeme []byte

	// FilePath is the file path the scanner was given.
	FilePath string

	// Cause is what is wrong, without the position in front of it.
	Cause error
}

// Error implements error
var _ error = (*Error)(nil)

// Error returns an string describing this error.
func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: %s", e.FilePath, e.Line, e.Column, e.Cause)
}

func (e *Error) Unwrap() error {
	return e.Cause
}

// errorRecoveryShifts is the number of tokens which have to be shifted after a syntax error before the parser reports
// errors again. Suppressing the errors in between keeps a single mistake in the input from producing an avalanche of
// messages which are all consequences of the first one. It is the number of tokens yacc and GNU Bison use, see
// section 7 "Error Handling" of the yacc report.
const errorRecoveryShifts = 3

// expectedTokensMax is the largest number of expected tokens a syntax error lists. With more of them, the list is left
// out, because it would not help the reader any more.
const expectedTokensMax = 4

// arenaChunkSize is the number of nodes the arena allocator hands out from a single chunk. A parse which needs more
// nodes than one chunk holds takes further chunks of the same size and keeps them for the parses after it.
const arenaChunkSize = 16 * 1024

// initialStackCapacity is how many entries the stacks start with room for. They grow as a deeper parse needs them to.
const initialStackCapacity = 64

// The parse table is held in lookup tables. A token is translated into the column of the action table which holds the
// decisions for it, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao. The
// gotos are held the same way, with the nonterminal as the column.
//
// The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the action
// table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the tables.
//
// The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
// range check of its own.
const (
	// actionKindBits is the number of low bits of an action which hold what it does. The value it carries sits above
	// them.
	actionKindBits = 2

	// actionKindMask selects out of an action what it does.
	actionKindMask = 3

	// actionKindShift shifts the terminal and continues in the state the action carries.
	actionKindShift = 0

	// actionKindReduce reduces by the production the action carries.
	actionKindReduce = 1

	// actionKindAccept ends the parse successfully, the input having been reduced to the start symbol.
	actionKindAccept = 2

	// actionKindError rejects the terminal as a syntax error.
	actionKindError = 3

	// noTerminalColumn is the column a token gets which is no terminal of this grammar. No state has an entry in it,
	// so a lookup falls through to the default action of the state.
	noTerminalColumn = 0

	// errorTerminalColumn is the column holding the shifts of the error symbol, where the recovery reads the state to
	// resume in.
	errorTerminalColumn = 0
)

var (
	// terminalColumnByToken translates a token into the column of the action table which holds the decisions for it.
	//
	// The entries are indexed by the token constants themselves, which lets the compiler place each of them at
	// whatever value the scanner gave it. Neither generator has to know the numbering of the other because of that.
	// A token the grammar does not have is not named here at all and keeps the noTerminalColumn every unnamed index
	// holds.
	terminalColumnByToken = [...]uint8{
		EndToken:        1,
		TokenWhitespace: 2,
		TokenInteger:    3,
		TokenPlus:       4,
		TokenMinus:      5,
		TokenMultiply:   6,
		TokenDivide:     7,
		TokenLparen:     8,
		TokenRparen:     9,
		TokenUminus:     10,
	}

	// tokenByTerminalColumn translates a column of the action table back into the token of its terminal. The
	// noTerminalColumn stands for no token.
	tokenByTerminalColumn = [...]Token{
		1:  EndToken,
		2:  TokenWhitespace,
		3:  TokenInteger,
		4:  TokenPlus,
		5:  TokenMinus,
		6:  TokenMultiply,
		7:  TokenDivide,
		8:  TokenLparen,
		9:  TokenRparen,
		10: TokenUminus,
	}

	// actionBase maps a state to the displacement of its row within actionNext.
	actionBase = [17]uint8{
		9, 1, 9, 9, 0, 1, 4, 1, 9, 9, 9, 9, 1, 12, 12, 1,
		1,
	}

	// actionNext holds the action of every entry. The action a state has for a column lives at
	// actionBase[state] + column, but only if actionCheck confirms the cell belongs to that column.
	actionNext = [23]uint8{
		0, 28, 0, 0, 32, 36, 40, 44, 32, 36, 40, 44, 4, 48, 8, 0,
		0, 12, 40, 44, 0, 0, 0,
	}

	// actionCheck holds the column every cell of actionNext belongs to. A cell no state occupies holds
	// 11, which is one past the highest column in use and can never be asked for.
	actionCheck = [23]uint8{
		11, 1, 11, 11, 4, 5, 6, 7, 4, 5, 6, 7, 3, 9, 5, 11,
		11, 8, 6, 7, 11, 11, 11,
	}

	// defaultActionByState holds the action a state takes for every column it has no entry of its own for. A state
	// which has none carries the error action.
	defaultActionByState = [17]uint8{
		3, 5, 3, 3, 3, 25, 3, 2, 3, 3, 3, 3, 29, 9, 13, 17,
		21,
	}

	// consistentByState holds 1 for a state which reduces by the same production whatever the lookahead is, and 0
	// otherwise. A consistent state needs no lookahead, so it never starts an exploratory parse.
	consistentByState = [17]uint8{
		0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
		1,
	}

	// gotoBase maps a state to the displacement of its row within gotoNext.
	gotoBase = [17]uint8{
		6, 6, 0, 1, 6, 6, 6, 6, 2, 3, 4, 5, 6, 6, 6, 6,
		6,
	}

	// gotoNext holds the state a goto leads to. The goto a state has for a nonterminal lives at
	// gotoBase[state] + nonterminal, but only if gotoCheck confirms the cell belongs to that nonterminal.
	gotoNext = [8]uint8{
		0, 5, 6, 13, 14, 15, 16, 0,
	}

	// gotoCheck holds the nonterminal every cell of gotoNext belongs to. A cell no state occupies holds
	// 2, which is one past the highest nonterminal and can never be asked for.
	gotoCheck = [8]uint8{
		2, 1, 1, 1, 1, 1, 1, 2,
	}

	// defaultGotoByNonterminal holds the state a goto on a nonterminal leads to for every state gotoNext has no entry
	// for.
	defaultGotoByNonterminal = [2]uint8{
		0, 4,
	}

	// popCountByProduction holds how many symbols a reduction takes off the stacks, which is the length of the right
	// hand side.
	popCountByProduction = [8]uint8{
		2, 1, 3, 3, 3, 3, 2, 3,
	}

	// nonterminalByProduction holds the nonterminal on the left hand side of a production.
	nonterminalByProduction = [8]uint8{
		0, 1, 1, 1, 1, 1, 1, 1,
	}
)

// TraceFunc receives one line per parser action. It is a debug aid; the line format carries no stability guarantee.
type TraceFunc func(line string)

// Parser provides the parser implementation.
type Parser struct {
	// Trace, when not nil, is called with one line for every action the parser takes. Set it after NewParser.
	Trace TraceFunc

	// stateStack holds the states of the running parse, the current one on top.
	stateStack []int

	// nodeStack holds one node per symbol shifted or reduced so far.
	nodeStack []Node

	// arenaChunks holds every chunk of nodes the parser has allocated so far, in the order they are handed out. A
	// parse starts over at the first chunk instead of allocating new ones, so only a parse which needs more nodes
	// than every parse before it adds a chunk. Parse invalidates the tree of the parse before it in any case, so
	// handing the memory of that tree out again takes away nothing a caller could rely on.
	arenaChunks   [][]Node
	arenaChunkIdx int

	// arenaAllocator is the chunk nodes are handed out from at the moment, which aliases arenaChunks[arenaChunkIdx].
	// Keeping it here lets allocateNodes read the room left in the chunk straight off the parser.
	arenaAllocator    []Node
	arenaAllocatorTop int

	// errors collects the syntax errors of the current parse, which Parse returns joined together.
	errors []error

	// errorRecoveryShiftsRemaining counts down the tokens which still have to be shifted before syntax errors are
	// reported again. It is zero while the parser is in sync with the input and errorRecoveryShifts right after the
	// error symbol was shifted.
	errorRecoveryShiftsRemaining int

	// exploratoryParsePassed reports that an exploratory parse found the current lookahead to be shifted eventually,
	// so the reductions leading there need no further check. It is cleared whenever the lookahead or the stack below
	// the reductions changes, which is on every shift and on every token discarded.
	exploratoryParsePassed bool

	// exploratoryStack holds the states an exploratory parse pushes. The states below them are the ones of stateStack
	// below exploratoryStackBase, which the exploratory parse reads but never writes.
	exploratoryStack     []int
	exploratoryStackBase int
}

// NewParser creates a new parser.
func NewParser() *Parser {
	parser := Parser{
		stateStack:       make([]int, 0, initialStackCapacity),
		nodeStack:        make([]Node, 0, initialStackCapacity),
		arenaChunks:      [][]Node{make([]Node, arenaChunkSize)},
		exploratoryStack: make([]int, 0, initialStackCapacity),
	}
	parser.resetArena()
	return &parser
}

// errAccept is used to signal the successful end of the parse. It is filtered out by the main parse loop and not
// exposed to the user.
var errAccept = errors.New("accept")

// Parse executes a parse on the tokens provided by the scanner and returns a parse tree or an error. Parse can be
// called multiple times with different scanners to re-use the memory already allocated by the parser.
//
// When the grammar marks places to resume at with the error symbol, the parser recovers from a syntax error and carries
// on parsing. Parse then returns both a tree and an error: the tree of the input as far as the parser could make sense
// of it, with a node for the error symbol at every place it resumed at, and all syntax errors it found joined into one
// error. A tree is only returned if the parse reached its end, otherwise the recovery gave up somewhere in the middle
// and there is no tree to speak of.
//
// The errors are joined even when there is only one of them, so the shape of the returned error does not depend on how
// many errors the parse found. Use errors.Is and errors.As to get at them, both of which look into a join.
func (p *Parser) Parse(scanner TokenSource) (Node, error) {
	p.resetArena()

	p.stateStack = p.stateStack[:0]
	p.stateStack = append(p.stateStack, 0)
	p.nodeStack = p.nodeStack[:0]
	p.errors = p.errors[:0]
	p.errorRecoveryShiftsRemaining = 0
	p.exploratoryParsePassed = false

	// A source with no tokens at all reports false right away. That is not an error: the token is the end of input
	// either way, and whether a parse of nothing but that is legal is for the table to decide.
	scanner.Next()

	for {
		err := p.step(scanner)
		if err == nil {
			continue
		}
		if errors.Is(err, errAccept) {
			// What is left on the node stack is the start symbol, which is the root of the tree.
			return p.nodeStack[0], errors.Join(p.errors...)
		}
		if !errors.Is(err, ErrSyntax) {
			// Only an error in the input can be recovered from.
			p.errors = append(p.errors, err)
			return Node{}, errors.Join(p.errors...)
		}
		if p.errorRecoveryShiftsRemaining == 0 {
			// While recovering, the parser is not in sync with the input, so the errors it runs into there follow
			// from the one already reported.
			p.errors = append(p.errors, err)
		}
		if !p.recoverFromError(scanner) {
			return Node{}, errors.Join(p.errors...)
		}
	}
}

// step performs the single action which the state on top of the stack takes for the token the scanner currently
// delivers. This is the whole automaton: everything which distinguishes one state from another is in the tables.
func (p *Parser) step(scanner TokenSource) error {
	terminal := scanner.Token()

	// A token which is no terminal of this grammar takes the default action of the state.
	column := p.terminalColumn(terminal)

	state := p.currentState()
	action := p.action(state, column)

	switch action & actionKindMask {
	case actionKindShift:
		if p.Trace != nil {
			p.emitTrace(scanner, "SHIFT", p.terminalTraceName(terminal)+` "`+p.escapeLexeme(scanner.Lexeme())+`"`)
		}
		p.stateStack = append(p.stateStack, int(action>>actionKindBits))
		p.nodeStack = append(p.nodeStack, Node{
			Symbol:     NewTerminal(terminal),
			ByteOffset: scanner.ByteOffset(),
			ByteLength: scanner.ByteLength(),
		})
		scanner.Next()
		p.exploratoryParsePassed = false
		if p.errorRecoveryShiftsRemaining > 0 {
			// Getting tokens of the input shifted again is what makes the parser trust its position.
			p.errorRecoveryShiftsRemaining--
		}
		return nil
	case actionKindReduce:
		if !p.exploratoryParsePassed && consistentByState[state] == 0 {
			// The state reduces because of the lookahead, which might be one it only accepts because states were
			// merged or a default reduction was chosen. Reducing on it would leave the state the error belongs to.
			if !p.exploratoryParse(column) {
				return p.raiseSyntaxError(scanner, terminal)
			}
			p.exploratoryParsePassed = true
		}
		p.reduce(scanner, action>>actionKindBits)
		return nil
	case actionKindAccept:
		if p.Trace != nil {
			p.emitTrace(scanner, "ACCEPT", "")
		}
		// The parse is successfully finished.
		return errAccept
	case actionKindError:
		return p.raiseSyntaxError(scanner, terminal)
	default:
		if p.Trace != nil {
			p.emitErrorTrace(scanner, fmt.Sprintf("unexpected action %d in state %d", action, state))
		}
		return p.raiseError(scanner, fmt.Errorf("%w: unexpected action %d in state %d", ErrInternal, action, state))
	}
}

// reduce replaces the right hand side of the given production on the stacks with the nonterminal on its left hand side,
// and continues in the state the goto of the uncovered state leads to.
func (p *Parser) reduce(scanner TokenSource, productionIdx uint32) {
	popCount := int(popCountByProduction[productionIdx])
	nonterminal := uint32(nonterminalByProduction[productionIdx])

	if p.Trace != nil {
		// The right hand side is still on the node stack here, before it is cut back below.
		p.emitTrace(scanner, "REDUCE", p.reduceTracePayload(Nonterminal(nonterminal), p.nodeStack[len(p.nodeStack)-popCount:]))
	}

	p.stateStack = p.stateStack[:len(p.stateStack)-popCount]

	p.stateStack = append(p.stateStack, p.gotoState(p.currentState(), nonterminal))

	// The node starts where its first child starts and ends where its last child ends.
	rightHandSide := p.nodeStack[len(p.nodeStack)-popCount:]
	var byteOffset, byteLength int
	switch {
	case popCount != 0:
		lastChild := rightHandSide[popCount-1]
		byteOffset = rightHandSide[0].ByteOffset
		byteLength = lastChild.ByteOffset + lastChild.ByteLength - byteOffset
	case len(p.nodeStack) != 0:
		// A production with an empty right hand side goes at the end of the symbol to its left, so that it lies
		// inside the node it becomes a child of instead of at the lookahead beyond it.
		left := p.nodeStack[len(p.nodeStack)-1]
		byteOffset = left.ByteOffset + left.ByteLength
	default:
		// Nothing has been parsed yet, so there is no symbol to the left of it.
		byteOffset = scanner.ByteOffset()
	}

	newNode := Node{
		Symbol:     NewNonterminal(Nonterminal(nonterminal)),
		ByteOffset: byteOffset,
		ByteLength: byteLength,
		Production: Production(productionIdx),
	}
	if popCount != 0 {
		newNode.Children = p.allocateNodes(popCount)
		copy(newNode.Children, rightHandSide)
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-popCount]
	}
	p.nodeStack = append(p.nodeStack, newNode)
}

// exploratoryParse reports whether the parse from the current stack shifts the terminal of the given column eventually,
// instead of running into an error. It performs the reductions the terminal leads to on the states alone and without
// building nodes, so the stacks of the parse are still intact when the terminal turns out to be an error.
//
// This is the lookahead correction of section 3.5.2 "Parser" of "PSLR(1): Pseudo-Scannerless Minimal LR(1) for the
// Deterministic Parsing of Composite Languages" by Joel E. Denny. It deviates from the paper in two ways. The paper
// runs an exploratory parse as soon as a lookahead arrives, step runs it only before the first reduction the
// lookahead decides in a state which is not consistent, because a shift or an error action needs no exploring. And
// the paper explores on a copy of the stack, while this reads the stack in place, see exploratoryPop.
func (p *Parser) exploratoryParse(column uint32) bool {
	p.exploratoryStack = p.exploratoryStack[:0]
	p.exploratoryStackBase = len(p.stateStack)
	for {
		action := p.action(p.exploratoryTop(), column)
		switch action & actionKindMask {
		case actionKindReduce:
			productionIdx := action >> actionKindBits
			p.exploratoryPop(int(popCountByProduction[productionIdx]))
			p.exploratoryPush(p.gotoState(p.exploratoryTop(), uint32(nonterminalByProduction[productionIdx])))
		case actionKindShift, actionKindAccept:
			return true
		default:
			return false
		}
	}
}

// exploratoryTop returns the state on top of the stack of the exploratory parse.
func (p *Parser) exploratoryTop() int {
	if len(p.exploratoryStack) != 0 {
		return p.exploratoryStack[len(p.exploratoryStack)-1]
	}
	return p.stateStack[p.exploratoryStackBase-1]
}

// exploratoryPop takes the given number of states off the stack of the exploratory parse. The states it pushed itself
// go first. Below them, it lowers the base index into stateStack instead of popping, so the stack of the parse is never
// written and needs no copy.
func (p *Parser) exploratoryPop(count int) {
	pushedCount := min(count, len(p.exploratoryStack))
	p.exploratoryStack = p.exploratoryStack[:len(p.exploratoryStack)-pushedCount]
	p.exploratoryStackBase -= count - pushedCount
}

// exploratoryPush puts the given state on top of the stack of the exploratory parse.
func (p *Parser) exploratoryPush(state int) {
	p.exploratoryStack = append(p.exploratoryStack, state)
}

// expectedTokens returns the tokens which the parse from the current stack would shift eventually, in the order of
// their columns. It runs an exploratory parse per terminal of the grammar and leaves out the error symbol, which no
// scanner delivers. More than expectedTokensMax of them are not returned at all.
func (p *Parser) expectedTokens() []Token {
	var result []Token
	for column := range uint32(len(tokenByTerminalColumn)) {
		if column == noTerminalColumn || column == errorTerminalColumn || !p.exploratoryParse(column) {
			continue
		}
		if len(result) == expectedTokensMax {
			return nil
		}
		result = append(result, tokenByTerminalColumn[column])
	}
	return result
}

// raiseSyntaxError returns the error for the given token being unexpected on the current stack, listing the tokens
// which would have been expected instead.
func (p *Parser) raiseSyntaxError(scanner TokenSource, terminal Token) error {
	expected := p.expectedTokens()
	if p.Trace != nil {
		p.emitErrorTrace(scanner, p.unexpectedTokenMessage(terminal, expected, p.terminalTraceName))
	}
	return p.raiseError(scanner, fmt.Errorf("%w: %s", ErrSyntax, p.unexpectedTokenMessage(terminal, expected, Token.String)))
}

// unexpectedTokenMessage describes the given token as unexpected in place of the expected ones, naming each token with
// the given function.
func (p *Parser) unexpectedTokenMessage(terminal Token, expected []Token, name func(Token) string) string {
	message := "unexpected token " + name(terminal)
	for i, token := range expected {
		if i == 0 {
			message += ", expecting " + name(token)
		} else {
			message += " or " + name(token)
		}
	}
	return message
}

// recoverFromError puts the parser back where it can carry on with the remaining input after a syntax error. Once it
// reports false, the parse is given up.
//
// This is the panic mode recovery of section 9 "Error Recovery" of "LR Parsing" by Aho and Johnson, in the shape which
// section 7 "Error Handling" of the yacc report describes: the parser pops its stack until it reaches a state which can
// shift the error symbol - a place the grammar marked as one to resume at - and shifts the symbol there. Everything the
// popped states had parsed is discarded with them.
//
// The token which caused the error is kept for the resumed state to look at, because that state is usually waiting for
// exactly it: in a production like "{" @error "}" it is the closing brace which ends the recovery. Only when the parse
// fails on that very same token again is the token discarded, which is what an untouched countdown of tokens to shift
// tells us. Popping and discarding in the same handler is what guarantees progress: every round of recovery either gets
// the parse going again or consumes one token of the input, so a parse cannot get stuck between the two.
func (p *Parser) recoverFromError(scanner TokenSource) bool {
	// The error node this round ends with runs from the start of what the round throws away to the point where it
	// resumes, so the span starts out empty at the token the parser stopped on and grows to the front with every node
	// the round pops.
	droppedOffset, droppedLength := scanner.ByteOffset(), 0

	if p.errorRecoveryShiftsRemaining == errorRecoveryShifts {
		// Nothing was shifted since the last error, so the parser is failing on the token it already failed on.
		if scanner.Token() == EndToken {
			// The end of input is the one token which cannot be discarded.
			if p.Trace != nil {
				p.emitTrace(scanner, "FAIL", "")
			}
			return false
		}
		if p.Trace != nil {
			p.emitTrace(scanner, "DISCARD", p.terminalTraceName(scanner.Token())+` "`+p.escapeLexeme(scanner.Lexeme())+`"`)
		}
		// The discarded token is thrown away as well, so the span reaches to its end and not to its start.
		droppedLength = scanner.ByteLength()
		scanner.Next()
		p.exploratoryParsePassed = false
	}
	p.errorRecoveryShiftsRemaining = errorRecoveryShifts

	for {
		if nextState, ok := p.errorShiftState(p.currentState()); ok {
			if p.Trace != nil {
				p.emitTrace(scanner, "RESYNC", "")
			}
			if droppedLength == 0 && len(p.nodeStack) != 0 {
				// The round threw no bytes away, so its node goes at the end of the symbol to its left, where a
				// production with an empty right hand side goes, and not at the lookahead beyond it.
				left := p.nodeStack[len(p.nodeStack)-1]
				droppedOffset = left.ByteOffset + left.ByteLength
			}
			// Shift the error symbol. Its node covers what this round dropped.
			p.stateStack = append(p.stateStack, nextState)
			p.exploratoryParsePassed = false
			p.nodeStack = append(p.nodeStack, Node{
				Symbol:     NewTerminal(ErrorToken),
				ByteOffset: droppedOffset,
				ByteLength: droppedLength,
			})
			return true
		}
		if len(p.stateStack) == 1 {
			// Only the state the parse started in is left and it cannot shift the error symbol either.
			if p.Trace != nil {
				p.emitTrace(scanner, "FAIL", "")
			}
			return false
		}
		if p.Trace != nil {
			p.emitTrace(scanner, "POP", p.symbolTraceName(p.nodeStack[len(p.nodeStack)-1].Symbol))
		}
		// The state cannot resume here, so it is dropped together with what it had parsed. One state carries one
		// node, so dropping one drops one.
		droppedNode := p.nodeStack[len(p.nodeStack)-1]
		droppedLength = droppedOffset + droppedLength - droppedNode.ByteOffset
		droppedOffset = droppedNode.ByteOffset
		p.stateStack = p.stateStack[:len(p.stateStack)-1]
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-1]
	}
}

// currentState returns the state on top of the stack, which is the one the parse is in.
func (p *Parser) currentState() int {
	return p.stateStack[len(p.stateStack)-1]
}

// terminalColumn returns the column of the action table which holds the decisions for the given token. A token the
// grammar does not have, and one outside the range the scanner promises, both get noTerminalColumn.
func (p *Parser) terminalColumn(terminal Token) uint32 {
	if uint32(terminal) < uint32(len(terminalColumnByToken)) {
		return uint32(terminalColumnByToken[terminal])
	}
	return noTerminalColumn
}

// action returns the action the given state takes for the terminal of the given column.
func (p *Parser) action(state int, column uint32) uint32 {
	cellIdx := uint32(actionBase[state]) + column
	if uint32(actionCheck[cellIdx]) == column {
		// An entry the state has of its own beats its default action, which is what keeps a token the grammar
		// rejects on purpose an error even in a state which reduces on everything else.
		return uint32(actionNext[cellIdx])
	}
	return uint32(defaultActionByState[state])
}

// gotoState returns the state the parse continues in when it reduced to the given nonterminal and uncovered the given
// state.
func (p *Parser) gotoState(state int, nonterminal uint32) int {
	cellIdx := uint32(gotoBase[state]) + nonterminal
	if uint32(gotoCheck[cellIdx]) == nonterminal {
		return int(gotoNext[cellIdx])
	}
	// A state without a goto of its own on the nonterminal goes where most states go with it. A state which a
	// reduction uncovers always has one, so there is no case for a nonterminal missing from both.
	return int(defaultGotoByNonterminal[nonterminal])
}

// errorShiftState returns the state to continue in when the error symbol is shifted in the given state, and reports if
// the state can shift it at all. The states which can are the places the grammar marked to resume at after a syntax
// error.
//
// The default action of the state is deliberately not consulted, because only an entry the state has of its own is a
// place to resume at.
func (p *Parser) errorShiftState(state int) (int, bool) {
	cellIdx := uint32(actionBase[state]) + errorTerminalColumn
	if uint32(actionCheck[cellIdx]) != errorTerminalColumn {
		return 0, false
	}
	action := uint32(actionNext[cellIdx])
	if action&actionKindMask != actionKindShift {
		return 0, false
	}
	return int(action >> actionKindBits), true
}

// raiseError returns an error with the given cause at the position the scanner is at.
func (p *Parser) raiseError(scanner TokenSource, cause error) error {
	position := scanner.Position(scanner.ByteOffset())
	return &Error{
		Token:      scanner.Token(),
		ByteOffset: position.ByteOffset,
		Line:       position.Line,
		Column:     position.Column,
		Lexeme:     scanner.Lexeme(),
		FilePath:   position.FilePath,
		Cause:      cause,
	}
}

// allocateNodes provides an arena allocator for slices of Node.
func (p *Parser) allocateNodes(n int) []Node {
	if p.arenaAllocatorTop+n > len(p.arenaAllocator) {
		p.nextArenaChunk(n)
	}
	nodes := p.arenaAllocator[p.arenaAllocatorTop : p.arenaAllocatorTop+n]
	p.arenaAllocatorTop += n
	return nodes
}

// nextArenaChunk moves the arena on to the chunk after the current one, to serve a request of n nodes which the
// current chunk has no room left for. Where an earlier parse left a chunk behind, that chunk is handed out again, so
// a parser settles on the number of chunks its largest parse needed and allocates none after that.
//
// A reused chunk is not cleared. Every slice allocateNodes returns is filled completely by its caller before anything
// reads it, so what an earlier parse left behind in the chunk is never observable.
func (p *Parser) nextArenaChunk(n int) {
	p.arenaChunkIdx++
	if p.arenaChunkIdx == len(p.arenaChunks) {
		p.arenaChunks = append(p.arenaChunks, make([]Node, max(n, arenaChunkSize)))
	} else if len(p.arenaChunks[p.arenaChunkIdx]) < n {
		// A single reduction which takes more nodes than a chunk holds gets a chunk sized to itself, so a chunk kept
		// from an earlier parse is not guaranteed to have room for a later request.
		p.arenaChunks[p.arenaChunkIdx] = make([]Node, n)
	}
	p.arenaAllocator = p.arenaChunks[p.arenaChunkIdx]
	p.arenaAllocatorTop = 0
}

// resetArena puts the arena back to where it starts a parse, handing out from the beginning of the first chunk again.
func (p *Parser) resetArena() {
	p.arenaChunkIdx = 0
	p.arenaAllocator = p.arenaChunks[0]
	p.arenaAllocatorTop = 0
}

// emitTrace hands one trace line to p.Trace: the position of the current lookahead, the keyword, and an optional
// payload. The caller has already checked that p.Trace is not nil.
func (p *Parser) emitTrace(scanner TokenSource, keyword string, payload string) {
	position := scanner.Position(scanner.ByteOffset())
	location := fmt.Sprintf("%d:%d", position.Line, position.Column)
	if payload == "" {
		p.Trace(fmt.Sprintf("%-7s %s", location, keyword))
		return
	}
	p.Trace(fmt.Sprintf("%-7s %-7s %s", location, keyword, payload))
}

// emitErrorTrace emits an ERROR line, marked suppressed while error recovery is not reporting to the caller.
func (p *Parser) emitErrorTrace(scanner TokenSource, detail string) {
	if p.errorRecoveryShiftsRemaining != 0 {
		detail = "(suppressed) " + detail
	}
	p.emitTrace(scanner, "ERROR", detail)
}

// reduceTracePayload renders a reduction as "lhs => rhs", or "lhs => ε" for an empty right hand side.
func (p *Parser) reduceTracePayload(lhs Nonterminal, rhs []Node) string {
	payload := lhs.String() + " =>"
	if len(rhs) == 0 {
		return payload + " ε"
	}
	for i := range rhs {
		payload += " " + p.symbolTraceName(rhs[i].Symbol)
	}
	return payload
}

// symbolTraceName is the bare grammar name of a symbol, without the prefix Symbol.String adds.
func (p *Parser) symbolTraceName(symbol Symbol) string {
	if nonterminal, ok := symbol.Nonterminal(); ok {
		return nonterminal.String()
	}
	terminal, _ := symbol.Terminal()
	return p.terminalTraceName(terminal)
}

// terminalTraceName names a terminal for a trace line, giving the three tokens the grammar cannot spell a dollar name.
func (p *Parser) terminalTraceName(terminal Token) string {
	switch terminal {
	case EndToken:
		return "$end"
	case ErrorToken:
		return "$error"
	case InvalidToken:
		return "$invalid"
	default:
		return terminal.String()
	}
}

// escapeLexeme escapes the bytes of a lexeme for a trace line. The caller writes the quotes around the result.
func (p *Parser) escapeLexeme(lexeme []byte) string {
	const hexDigits = "0123456789abcdef"
	result := make([]byte, 0, len(lexeme))
	for _, value := range lexeme {
		switch {
		case value == '\\':
			result = append(result, '\\', '\\')
		case value == '"':
			result = append(result, '\\', '"')
		case value == '\n':
			result = append(result, '\\', 'n')
		case value == '\r':
			result = append(result, '\\', 'r')
		case value == '\t':
			result = append(result, '\\', 't')
		case 0x20 <= value && value <= 0x7E:
			result = append(result, value)
		default:
			result = append(result, '\\', 'x', hexDigits[value>>4], hexDigits[value&0x0F])
		}
	}
	return string(result)
}
