// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser

import (
	"errors"
	"fmt"
)

// Nonterminal is the data type representing all nonterminal symbols.
type Nonterminal int

const (
	Nonterminal_accept    Nonterminal = 0 // $accept
	NonterminalExpression Nonterminal = 1 // expression
)

// Nonterminal implements fmt.Stringer.
var _ fmt.Stringer = (*Nonterminal)(nil)

// String returns a string representation of the nonterminal.
func (n Nonterminal) String() string {
	switch n {
	case Nonterminal_accept:
		return `$accept`
	case NonterminalExpression:
		return `expression`
	default:
		return "unknown"
	}
}

// Symbol is either a terminal or a nonterminal. The most significant bit is used to signal a
// nonterminal. The maximum terminal or nonterminal index which can be stored is 32767.
type Symbol uint16

const (
	// symbolNonterminalBit is the most significant bit which is set when the Symbol stores a nonterminal.
	symbolNonterminalBit = 1 << 15

	// symbolMask is the bitmask for selecting only the value from Symbol.
	symbolMask = symbolNonterminalBit - 1
)

// NewTerminal creates a new Symbol for a terminal.
func NewTerminal(terminal Token) Symbol {
	return Symbol(terminal)
}

// NewNonterminal creates a new Symbol for a nonterminal.
func NewNonterminal(nonterminal Nonterminal) Symbol {
	return Symbol(symbolNonterminalBit | nonterminal)
}

// Terminal returns the terminal value of the Symbol. The boolean reports if the value is in fact a terminal.
func (s Symbol) Terminal() (Token, bool) {
	return Token(s & symbolMask), s&symbolNonterminalBit == 0
}

// Nonterminal returns the nonterminal value of the Symbol. The boolean reports if the value is in fact a nonterminal.
func (s Symbol) Nonterminal() (Nonterminal, bool) {
	return Nonterminal(s & symbolMask), s&symbolNonterminalBit != 0
}

// Symbol implements fmt.Stringer.
var _ fmt.Stringer = (*Symbol)(nil)

// String returns a string representation.
func (s Symbol) String() string {
	nonterminal, ok := s.Nonterminal()
	if ok {
		return fmt.Sprintf("nonterminal %d", nonterminal)
	}
	return fmt.Sprintf("terminal %d", Token(nonterminal))
}

// Node is a single node of the parse tree.
type Node struct {
	Symbol   Symbol
	Lexeme   []byte
	Children []Node
}

// ParserScanner is the interface the scanner for the parser needs to implement.
type ParserScanner interface {
	Token() Token
	ByteOffset() int
	Line() int
	Column() int
	Lexeme() []byte
	Next() bool
	FilePath() string
}

var (
	// This error is used in cases where the mechanic of the parser is wrong.
	ErrInternal = errors.New("internal parser error")

	// ErrSyntax marks an error in the input: a token which the grammar does not allow at the position it was found at.
	// Those are the errors the parser recovers from when the grammar marks places to resume at with the error symbol,
	// so Parse can return several of them joined together.
	ErrSyntax = errors.New("syntax error")
)

// errorRecoveryShifts is the number of tokens which have to be shifted after a syntax error before the parser reports
// errors again. Suppressing the errors in between keeps a single mistake in the input from producing an avalanche of
// messages which are all consequences of the first one. It is the number of tokens yacc and GNU Bison use, see
// section 7 "Error Handling" of the yacc report.
const errorRecoveryShifts = 3

// Error represents a single parse error.
type Error struct {
	Token      Token
	ByteOffset int
	Line       int
	Column     int
	Lexeme     []byte
	FilePath   string
	Cause      error
}

// Error implements error
var _ error = (*Error)(nil)

// Error returns an string describing this error.
func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: %s", e.FilePath, e.Line, e.Column, e.Cause)
}

func (e *Error) Unwrap() error {
	return e.Cause
}

// Parser provides the parser implementation.
type Parser struct {
	scanner ParserScanner

	stateStack []int
	nodeStack  []Node

	arenaAllocator    []Node
	arenaAllocatorTop int

	// errors collects the syntax errors of the current parse, which Parse returns joined together.
	errors []error

	// errorRecoveryShiftsRemaining counts down the tokens which still have to be shifted before syntax errors are
	// reported again. It is zero while the parser is in sync with the input and errorRecoveryShifts right after the
	// error symbol was shifted. In a parser for a grammar which marks no place to resume at it never leaves zero,
	// because there is nothing to recover from an error with, which is why the shift actions of such a parser do not
	// carry the countdown at all.
	errorRecoveryShiftsRemaining int
}

// NewParser creates a new parser.
func NewParser() *Parser {
	parser := Parser{
		stateStack:     make([]int, 0, 1024),
		nodeStack:      make([]Node, 0, 1024),
		arenaAllocator: make([]Node, 16*1024),
	}
	return &parser
}

// errAccept is used to signal the successful end of the parse. It is filtered out by the main parse loop and not
// exposed to the user.
var errAccept = errors.New("accept")

// Parse executes a parse on the tokens provided by the scanner and returns a parse tree or an error. Parse can be
// called multiple times with different scanners to re-use the memory already allocated by the parser.
//
// When the grammar marks places to resume at with the error symbol, the parser recovers from a syntax error and carries
// on parsing, see recoverFromError. Parse then returns both a tree and an error: the tree of the input as far as the
// parser could make sense of it, with a node for the error symbol at every place it resumed at, and all syntax errors
// it found joined into one error. A tree is only returned if the parse reached its end, otherwise the recovery gave up
// somewhere in the middle and there is no tree to speak of.
//
// The errors are joined even when there is only one of them, so the shape of the returned error does not depend on how
// many errors the parse found. Use errors.Is and errors.As to get at them, both of which look into a join.
func (p *Parser) Parse(scanner ParserScanner) (Node, error) {
	p.scanner = scanner
	p.arenaAllocatorTop = 0
	if !p.scanner.Next() {
		return Node{}, errors.New("Unexpected end of tokens")
	}

	p.stateStack = p.stateStack[:0]
	p.stateStack = append(p.stateStack, 0)
	p.nodeStack = p.nodeStack[:0]
	p.errors = p.errors[:0]
	p.errorRecoveryShiftsRemaining = 0

	for {
		currState := p.stateStack[len(p.stateStack)-1]
		err := p.dispatchState(currState)
		if err == nil {
			continue
		}
		if errors.Is(err, errAccept) {
			// The parse is finished. It still reports the errors it recovered from along the way.
			return p.nodeStack[0], errors.Join(p.errors...)
		}
		if !errors.Is(err, ErrSyntax) {
			// Only an error in the input can be recovered from. Anything else is a defect of the parser itself.
			p.errors = append(p.errors, err)
			return Node{}, errors.Join(p.errors...)
		}
		if p.errorRecoveryShiftsRemaining == 0 {
			// While recovering, the parser is not in sync with the input, so the errors it runs into there are most
			// likely consequences of the error which is already reported. Reporting those as well is the avalanche of
			// messages the countdown exists to prevent.
			p.errors = append(p.errors, err)
		}
		if !p.recoverFromError() {
			return Node{}, errors.Join(p.errors...)
		}
	}
}

// recoverFromError puts the parser back into a state where it can continue on the remaining input after a syntax error.
// It reports if that succeeded. Once it did not, the parse is given up.
//
// This is the panic mode recovery of section 9 "Error Recovery" of "LR Parsing" by Aho and Johnson, in the shape which
// section 7 "Error Handling" of the yacc report describes: the parser pops its stack until it reaches a state which can
// shift the error symbol - a place the grammar marked as one to resume at - and shifts the symbol there. Everything the
// popped states had parsed is discarded with them.
//
// The token which caused the error is kept for the resumed state to look at, because that state is usually waiting for
// exactly it: in a production like "{" @error "}" it is the closing brace which ends the recovery. Only when the parse
// fails on that very same token again is the token discarded, which is what an untouched countdown of tokens to shift
// tells us. Popping and discarding in the same handler is what guarantees progress: every round of recovery either gets
// the parse going again or consumes one token of the input, so a parse cannot get stuck between the two.
func (p *Parser) recoverFromError() bool {
	if p.errorRecoveryShiftsRemaining == errorRecoveryShifts {
		// Nothing was shifted since the last error, so the parser is failing on the token it already failed on and
		// keeping it would only lead here again.
		if p.scanner.Token() == EndToken {
			// The end of input is the one token which cannot be discarded, so there is nothing left to try.
			return false
		}
		p.scanner.Next()
	}
	p.errorRecoveryShiftsRemaining = errorRecoveryShifts

	for {
		if nextState, ok := errorShiftState(p.stateStack[len(p.stateStack)-1]); ok {
			// Shift the error symbol. Its node stands for the part of the input which was dropped and has no lexeme.
			p.stateStack = append(p.stateStack, nextState)
			p.nodeStack = append(p.nodeStack, Node{
				Symbol: NewTerminal(ErrorToken),
			})
			return true
		}
		if len(p.stateStack) == 1 {
			// Only the state the parse started in is left and it cannot shift the error symbol either, so no place the
			// grammar marked to resume at covers the position of the error.
			return false
		}
		// The state cannot resume here, so it is dropped together with what it had parsed and the state below it gets
		// to try. The two stacks hold one node per symbol which was shifted or reduced and one state on top of that,
		// so dropping one state drops one node.
		p.stateStack = p.stateStack[:len(p.stateStack)-1]
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-1]
	}
}

func (p *Parser) dispatchState(state int) error {
	switch state {
	case 0:
		return p.state0()
	case 1:
		return p.state1()
	case 2:
		return p.state2()
	case 3:
		return p.state3()
	case 4:
		return p.state4()
	case 5:
		return p.state5()
	case 6:
		return p.state6()
	case 7:
		return p.state7()
	case 8:
		return p.state8()
	case 9:
		return p.state9()
	case 10:
		return p.state10()
	case 11:
		return p.state11()
	case 12:
		return p.state12()
	case 13:
		return p.state13()
	case 14:
		return p.state14()
	case 15:
		return p.state15()
	case 16:
		return p.state16()
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected parser state %d", ErrInternal, state))
	}
}

// raiseError is a helper function which collects the current location of the parse and wraps the given cause.
func (p *Parser) raiseError(cause error) error {
	return &Error{
		Token:      p.scanner.Token(),
		ByteOffset: p.scanner.ByteOffset(),
		Line:       p.scanner.Line(),
		Column:     p.scanner.Column(),
		Lexeme:     p.scanner.Lexeme(),
		FilePath:   p.scanner.FilePath(),
		Cause:      cause,
	}
}

// allocateNodes provides and arena allocator for slices of Node.
func (p *Parser) allocateNodes(n int) []Node {
	if p.arenaAllocatorTop+n > len(p.arenaAllocator) {
		p.arenaAllocator = make([]Node, max(n, 16*1024))
		p.arenaAllocatorTop = 0
	}
	nodes := p.arenaAllocator[p.arenaAllocatorTop : p.arenaAllocatorTop+n]
	p.arenaAllocatorTop += n
	return nodes
}

func (p *Parser) state0() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state1() error {
	terminal := p.scanner.Token()
	switch terminal {
	default:
		// Reduce: expression -> INTEGER
		p.stateStack = p.stateStack[:len(p.stateStack)-1]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(1),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-1:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-1]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

func (p *Parser) state2() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state3() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state4() error {
	terminal := p.scanner.Token()
	switch terminal {
	// $end
	case EndToken:
		// Shift action
		p.stateStack = append(p.stateStack, 7)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// PLUS
	case TokenPlus:
		// Shift action
		p.stateStack = append(p.stateStack, 8)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 9)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MULTIPLY
	case TokenMultiply:
		// Shift action
		p.stateStack = append(p.stateStack, 10)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// DIVIDE
	case TokenDivide:
		// Shift action
		p.stateStack = append(p.stateStack, 11)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state5() error {
	terminal := p.scanner.Token()
	switch terminal {
	default:
		// Reduce: expression -> MINUS expression
		p.stateStack = p.stateStack[:len(p.stateStack)-2]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(2),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-2:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-2]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

func (p *Parser) state6() error {
	terminal := p.scanner.Token()
	switch terminal {
	// PLUS
	case TokenPlus:
		// Shift action
		p.stateStack = append(p.stateStack, 8)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 9)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MULTIPLY
	case TokenMultiply:
		// Shift action
		p.stateStack = append(p.stateStack, 10)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// DIVIDE
	case TokenDivide:
		// Shift action
		p.stateStack = append(p.stateStack, 11)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// RPAREN
	case TokenRparen:
		// Shift action
		p.stateStack = append(p.stateStack, 12)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state7() error {
	terminal := p.scanner.Token()
	switch terminal {
	default:
		// Reduce: $accept -> expression $end
		// The parse is successfully finished.
		return errAccept
	}
}

func (p *Parser) state8() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state9() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state10() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state11() error {
	terminal := p.scanner.Token()
	switch terminal {
	// INTEGER
	case TokenInteger:
		// Shift action
		p.stateStack = append(p.stateStack, 1)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// MINUS
	case TokenMinus:
		// Shift action
		p.stateStack = append(p.stateStack, 2)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// LPAREN
	case TokenLparen:
		// Shift action
		p.stateStack = append(p.stateStack, 3)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	}
}

func (p *Parser) state12() error {
	terminal := p.scanner.Token()
	switch terminal {
	default:
		// Reduce: expression -> LPAREN expression RPAREN
		p.stateStack = p.stateStack[:len(p.stateStack)-3]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(3),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-3:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-3]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

func (p *Parser) state13() error {
	terminal := p.scanner.Token()
	switch terminal {
	// MULTIPLY
	case TokenMultiply:
		// Shift action
		p.stateStack = append(p.stateStack, 10)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// DIVIDE
	case TokenDivide:
		// Shift action
		p.stateStack = append(p.stateStack, 11)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		// Reduce: expression -> expression PLUS expression
		p.stateStack = p.stateStack[:len(p.stateStack)-3]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(3),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-3:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-3]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

func (p *Parser) state14() error {
	terminal := p.scanner.Token()
	switch terminal {
	// MULTIPLY
	case TokenMultiply:
		// Shift action
		p.stateStack = append(p.stateStack, 10)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	// DIVIDE
	case TokenDivide:
		// Shift action
		p.stateStack = append(p.stateStack, 11)
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		return nil
	default:
		// Reduce: expression -> expression MINUS expression
		p.stateStack = p.stateStack[:len(p.stateStack)-3]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(3),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-3:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-3]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

func (p *Parser) state15() error {
	terminal := p.scanner.Token()
	switch terminal {
	default:
		// Reduce: expression -> expression MULTIPLY expression
		p.stateStack = p.stateStack[:len(p.stateStack)-3]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(3),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-3:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-3]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

func (p *Parser) state16() error {
	terminal := p.scanner.Token()
	switch terminal {
	default:
		// Reduce: expression -> expression DIVIDE expression
		p.stateStack = p.stateStack[:len(p.stateStack)-3]
		nextState, err := p.gotoAfterNonterminalExpression(p.stateStack[len(p.stateStack)-1])
		if err != nil {
			return err
		}
		p.stateStack = append(p.stateStack, nextState)
		newNode := Node{
			Symbol:   NewNonterminal(NonterminalExpression),
			Children: p.allocateNodes(3),
		}
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-3:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-3]
		p.nodeStack = append(p.nodeStack, newNode)
		return nil
	}
}

// errorShiftState returns the state to continue in when the error symbol is shifted in the given state, and reports if
// the state can shift the error symbol at all. The states which can are the places the grammar marked to resume at
// after a syntax error, which is what the error recovery pops the stack down to. For a grammar which marks no such
// place there is no such state and no parse can be recovered.
func errorShiftState(state int) (int, bool) {
	switch state {
	default:
		return 0, false
	}
}

func (p *Parser) gotoAfterNonterminal_accept(state int) (int, error) {
	switch state {
	default:
		return 0, p.raiseError(fmt.Errorf("%w: unexpected state for gotoAfterNonterminal_accept", ErrInternal))
	}
}

func (p *Parser) gotoAfterNonterminalExpression(state int) (int, error) {
	switch state {
	case 0:
		return 4, nil
	case 2:
		return 5, nil
	case 3:
		return 6, nil
	case 8:
		return 13, nil
	case 9:
		return 14, nil
	case 10:
		return 15, nil
	case 11:
		return 16, nil
	default:
		return 0, p.raiseError(fmt.Errorf("%w: unexpected state for gotoAfterNonterminalExpression", ErrInternal))
	}
}
