// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

// A grammar declares tokens and a scanner offers members which a given user has no use for.
#![allow(dead_code)]

use std::fmt;

/// Every terminal symbol this scanner knows.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum Token {
    /// No token was found.
    #[default]
    InvalidToken,

    /// The end of the source was reached.
    EndToken,

    /// The symbol a grammar marks its error recovery points with. No input ever produces it.
    ErrorToken,

    TokenWhitespace,
    TokenInteger,
    TokenPlus,
    TokenMinus,
    TokenMultiply,
    TokenDivide,
    TokenLparen,
    TokenRparen,
    TokenUminus,
}

impl fmt::Display for Token {
    /// Writes the name of the token, as the grammar spells it.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Token::InvalidToken => "invalid token",
            Token::EndToken => "end token",
            Token::ErrorToken => "error token",
            Token::TokenWhitespace => "WHITESPACE",
            Token::TokenInteger => "INTEGER",
            Token::TokenPlus => "PLUS",
            Token::TokenMinus => "MINUS",
            Token::TokenMultiply => "MULTIPLY",
            Token::TokenDivide => "DIVIDE",
            Token::TokenLparen => "LPAREN",
            Token::TokenRparen => "RPAREN",
            Token::TokenUminus => "UMINUS",
        };
        f.write_str(name)
    }
}

/// Holds the tokens the grammar marked for skipping.
#[rustfmt::skip]
static SKIPPED_TOKENS: [Token; 1] = [
    Token::TokenWhitespace,
];

/// Reports whether the grammar marked the token for skipping, which is what the token skipper drops.
pub fn is_skipped(token: Token) -> bool {
    SKIPPED_TOKENS.contains(&token)
}

/// What a scanner offers. Both [`Scanner`] and [`TokenSkipper`] implement it. The lifetime is the one of the source.
pub trait TokenSkipperScanner<'a> {
    /// Returns the current token.
    fn token(&self) -> Token;

    /// Returns the start of the token in bytes from the start of the source. After [`Self::next`] returned false it
    /// is the offset one past the last byte.
    fn byte_offset(&self) -> usize;

    /// Returns the line the token starts on, counted from one.
    fn line(&self) -> usize;

    /// Returns the column the token starts on, counted from one.
    fn column(&self) -> usize;

    /// Returns the bytes of the token, as a view into the source rather than a copy of it.
    fn lexeme(&self) -> &'a [u8];

    /// Returns the file path the scanner was given.
    fn file_path(&self) -> &str;

    /// Scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
    /// changed.
    fn reset(&mut self, source: &'a [u8], offset: usize);

    /// Advances to the next token. Returns false when the source holds no such token any more.
    fn next(&mut self) -> bool;
}

/// Wraps a scanner and skips the tokens marked for skipping, which are usually whitespace and comments. It offers the
/// same members as [`Scanner`].
pub struct TokenSkipper<S> {
    /// The wrapped scanner.
    scanner: S,
}

impl<S> TokenSkipper<S> {
    /// Creates a skipper which hands on the tokens of the given scanner.
    pub fn new(scanner: S) -> Self {
        Self { scanner }
    }
}

impl<'a, S: TokenSkipperScanner<'a>> TokenSkipperScanner<'a> for TokenSkipper<S> {
    fn token(&self) -> Token {
        self.scanner.token()
    }

    fn byte_offset(&self) -> usize {
        self.scanner.byte_offset()
    }

    fn line(&self) -> usize {
        self.scanner.line()
    }

    fn column(&self) -> usize {
        self.scanner.column()
    }

    fn lexeme(&self) -> &'a [u8] {
        self.scanner.lexeme()
    }

    fn file_path(&self) -> &str {
        self.scanner.file_path()
    }

    fn reset(&mut self, source: &'a [u8], offset: usize) {
        self.scanner.reset(source, offset);
    }

    /// Advances to the next token which is not marked for skipping. Returns false when the source holds no such token
    /// any more.
    fn next(&mut self) -> bool {
        while self.scanner.next() {
            if !is_skipped(self.scanner.token()) {
                return true;
            }
        }
        false
    }
}

// The automaton is held in lookup tables. An input byte is mapped to its byte class, which is the column of the
// transition table, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao.
//
// The displaced arrays are padded so that every state and byte class lands inside them, which is why a lookup needs no
// range check of its own.

/// Maps an input byte to its byte class. Bytes which every state treats alike share a class.
#[rustfmt::skip]
static BYTE_CLASS_BY_BYTE: [u8; 256] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 0, 6, 0, 7,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

/// Maps a state to the displacement of its row within [`TRANSITION_NEXT`].
#[rustfmt::skip]
static TRANSITION_BASE: [u8; 9] = [
    0, 8, 2, 1, 1, 1, 1, 1, 1,
];

/// Holds the target state of every transition. The transition a state has on a byte class lives at
/// `TRANSITION_BASE[state] + class`, but only if [`TRANSITION_CHECK`] confirms the cell belongs to that class.
#[rustfmt::skip]
static TRANSITION_NEXT: [u8; 17] = [
    0, 1, 7, 8, 5, 3, 4, 6, 2, 1, 2, 0, 0, 0, 0, 0,
    0,
];

/// Holds the byte class every cell of [`TRANSITION_NEXT`] belongs to. A cell no state occupies holds
/// 9, which is one past the highest byte class in use and can never be asked for.
#[rustfmt::skip]
static TRANSITION_CHECK: [u8; 17] = [
    9, 1, 2, 3, 4, 5, 6, 7, 8, 1, 8, 9, 9, 9, 9, 9,
    9,
];

/// Holds the token a state accepts, or [`Token::InvalidToken`] for a state which does not accept.
#[rustfmt::skip]
static ACCEPT_TOKEN_BY_STATE: [Token; 9] = [
    Token::InvalidToken,
    Token::TokenWhitespace,
    Token::TokenInteger,
    Token::TokenPlus,
    Token::TokenMinus,
    Token::TokenMultiply,
    Token::TokenDivide,
    Token::TokenLparen,
    Token::TokenRparen,
];

/// Turns the bytes of a source into tokens. The source is borrowed, so the caller keeps it alive while it is scanned.
#[derive(Default)]
pub struct Scanner<'a> {
    /// The bytes being scanned.
    source: &'a [u8],

    /// The file path the scanner was given.
    file_path: String,

    /// The current token.
    token: Token,

    /// Index of the first byte of the current token.
    lexeme_start_idx: usize,

    /// Index one past the last byte of the current token.
    lexeme_end_idx: usize,

    /// The line the current token starts on, counted from one.
    line: usize,

    /// The column the current token starts on, counted from one.
    column: usize,
}

impl<'a> Scanner<'a> {
    /// Creates a scanner which turns the given bytes into tokens, starting at the first of them. The file path is used
    /// in error messages, so any string will do when the source is not a file.
    pub fn new(source: &'a [u8], file_path: &str) -> Self {
        // Everything the scan runs on is left to reset, so that a new scanner and a reset one start out the same.
        let mut scanner = Self {
            file_path: file_path.to_owned(),
            ..Self::default()
        };
        scanner.reset(source, 0);
        scanner
    }

    /// Advances the line and column counters over the bytes between the two indexes.
    fn update_line_and_column(&mut self, start_idx: usize, end_idx: usize) {
        for &byte in &self.source[start_idx..end_idx] {
            if byte == b'\n' {
                self.line += 1;
                self.column = 1;
            } else {
                self.column += 1;
            }
        }
    }
}

impl<'a> TokenSkipperScanner<'a> for Scanner<'a> {
    fn token(&self) -> Token {
        self.token
    }

    fn byte_offset(&self) -> usize {
        self.lexeme_start_idx
    }

    fn line(&self) -> usize {
        self.line
    }

    fn column(&self) -> usize {
        self.column
    }

    fn lexeme(&self) -> &'a [u8] {
        &self.source[self.lexeme_start_idx..self.lexeme_end_idx]
    }

    fn file_path(&self) -> &str {
        &self.file_path
    }

    fn reset(&mut self, source: &'a [u8], offset: usize) {
        self.source = source;

        self.lexeme_start_idx = 0;
        // An offset past the end of the source would walk the line and column counters over bytes which are not
        // there. Clamping it leaves the scanner at the end of the source, where it reports the end token.
        self.lexeme_end_idx = offset.min(source.len());

        self.line = 1;
        self.column = 1;

        self.token = Token::InvalidToken;
    }

    /// Advances to the next token. Bytes which form no token become an invalid token. Returns false once the end of
    /// the source is reached, which sets the token to the end token.
    fn next(&mut self) -> bool {
        self.update_line_and_column(self.lexeme_start_idx, self.lexeme_end_idx);
        self.lexeme_start_idx = self.lexeme_end_idx;

        let mut state = 0usize;
        let mut lexeme_peek_idx = self.lexeme_end_idx;
        loop {
            // Remember every accepting state passed through, so the longest match wins over the first one.
            if ACCEPT_TOKEN_BY_STATE[state] != Token::InvalidToken {
                self.token = ACCEPT_TOKEN_BY_STATE[state];
                self.lexeme_end_idx = lexeme_peek_idx;
            }
            if lexeme_peek_idx == self.source.len() {
                // The end of the source is reached, so the state it stopped in was the last one to test.
                break;
            }

            let byte_class = BYTE_CLASS_BY_BYTE[self.source[lexeme_peek_idx] as usize] as usize;
            let cell_idx = TRANSITION_BASE[state] as usize + byte_class;
            if TRANSITION_CHECK[cell_idx] as usize != byte_class {
                // The state has no transition on this byte, so the token ends here.
                break;
            }
            state = TRANSITION_NEXT[cell_idx] as usize;
            lexeme_peek_idx += 1;
        }

        if self.lexeme_start_idx < self.lexeme_end_idx {
            // A token was found.
            return true;
        }

        if self.source.len() <= self.lexeme_start_idx {
            // The end of the source was reached.
            self.token = Token::EndToken;
            return false;
        }

        // The bytes here form no token. The invalid token ends where the automaton stopped, because the byte it could
        // not consume is where the next attempt starts. Only when the automaton consumed nothing does it cover that
        // byte, which is what keeps the scan moving forward.
        self.token = Token::InvalidToken;
        self.lexeme_end_idx = (self.lexeme_start_idx + 1).max(lexeme_peek_idx);
        true
    }
}
