// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser

import java.nio.ByteBuffer

/** Every nonterminal symbol of the grammar. */
enum class Nonterminal(private val displayName: String) {
    /** The start symbol the generator adds around the one the grammar declares. Reaching it accepts the input. */
    ACCEPT_NONTERMINAL("\$accept"),

    NONTERMINAL_EXPRESSION("expression"),
    ;

    /** Returns the name of the nonterminal, as the grammar spells it. */
    override fun toString(): String = displayName
}

/** Every production of the grammar. Has no entry for production 0 ($accept), which is never reduced. */
enum class Production(private val displayName: String) {
    PRODUCTION_EXPRESSION1("expression_1"),
    PRODUCTION_EXPRESSION2("expression_2"),
    PRODUCTION_EXPRESSION3("expression_3"),
    PRODUCTION_EXPRESSION4("expression_4"),
    PRODUCTION_EXPRESSION5("expression_5"),
    PRODUCTION_EXPRESSION6("expression_6"),
    PRODUCTION_EXPRESSION7("expression_7"),
    ;

    /** Returns the name of the production. */
    override fun toString(): String = displayName

    companion object {
        /**
         * Returns the production for the given production index, which is 1-based since production 0 ($accept) has
         * no entry.
         */
        fun forIdx(productionIdx: Int): Production = entries[productionIdx - 1]
    }
}

/** A terminal or a nonterminal. */
sealed interface ParseSymbol

/**
 * The symbol of a terminal.
 *
 * @property token the terminal this symbol stands for
 */
data class TerminalSymbol(val token: Token) : ParseSymbol {
    /** Returns what the symbol is and the name the grammar spells it with. */
    override fun toString(): String = "terminal $token"
}

/**
 * The symbol of a nonterminal.
 *
 * @property nonterminal the nonterminal this symbol stands for
 */
data class NonterminalSymbol(val nonterminal: Nonterminal) : ParseSymbol {
    /** Returns what the symbol is and the name the grammar spells it with. */
    override fun toString(): String = "nonterminal $nonterminal"
}

/**
 * A single node of the parse tree.
 *
 * @property symbol the terminal or nonterminal this node stands for
 * @param lexemeBytes the bytes [lexeme] hands out views of. Pass an empty buffer for a nonterminal
 * @property children the nodes of the right hand side of the production which was reduced to this node. Empty for a
 *     terminal
 * @property production the production which was reduced to this node. Null for a terminal, which no production
 *     reduces to
 */
class ParseNode(
    val symbol: ParseSymbol,
    private val lexemeBytes: ByteBuffer,
    val children: List<ParseNode>,
    val production: Production?,
) {
    /**
     * The bytes of the terminal, as a view into the source rather than a copy of it. Empty for a nonterminal and for
     * the error symbol, which no input produced.
     *
     * A buffer carries the position it is read from, so every read hands out a view of its own, which keeps one reader
     * from consuming the bytes for the next.
     */
    val lexeme: ByteBuffer
        get() = lexemeBytes.duplicate()

    /** Returns what the node stands for, which is what its symbol is called. */
    override fun toString(): String = symbol.toString()
}

/** What a parse error is about. */
enum class ErrorKind {
    /** An error in the input. */
    SYNTAX,

    /** A defect of the parser itself, which ends the parse. */
    INTERNAL,
}

/**
 * A single parse error. Parse errors are returned by [Parser.parse] rather than raised, so reporting many of them costs
 * nothing. This is no exception, so it carries no stack trace. Throw one with `error(parseError.message)`.
 *
 * @property reason what is wrong, without the position in front of it
 * @property kind what the error is about
 * @property token the token the parse stopped on
 * @property byteOffset start of that token in bytes from the start of the source
 * @property line line that token starts on, counted from one
 * @property column column that token starts on, counted from one
 * @param lexemeBytes the bytes [lexeme] hands out views of
 * @property filePath the file path the scanner was given
 */
class ParseError(
    val reason: String,
    val kind: ErrorKind,
    val token: Token,
    val byteOffset: Int,
    val line: Int,
    val column: Int,
    private val lexemeBytes: ByteBuffer,
    val filePath: String,
) {
    /**
     * Builds an error which stands where the given scanner is.
     *
     * @param reason what is wrong, without the position in front of it
     * @param kind what the error is about
     * @param scanner the scanner the token and its position are taken from
     */
    constructor(reason: String, kind: ErrorKind, scanner: TokenSource) : this(
        reason,
        kind,
        scanner.token,
        scanner.byteOffset,
        scanner.line,
        scanner.column,
        scanner.lexeme,
        scanner.filePath,
    )

    /**
     * The bytes of the token. A buffer carries the position it is read from, so every read hands out a view of its
     * own, which keeps one reader from consuming the bytes for the next.
     */
    val lexeme: ByteBuffer
        get() = lexemeBytes.duplicate()

    /** The error as one line of text, in the file:line:column: reason form editors and build tools recognize. */
    val message: String
        get() = "$filePath:$line:$column: $reason"

    /** Returns the message with the name of this type in front of it. */
    override fun toString(): String = "ParseError: $message"
}

/**
 * What a parse returns.
 *
 * @property tree the parse tree, or null when the parse could not be finished
 * @property errors every error the parse reported, in the order they were found
 */
data class ParseResult(val tree: ParseNode?, val errors: List<ParseError>)

/** What one step of a parse ended with. */
private sealed interface StepResult {
    /** The parse goes on. */
    data object Continue : StepResult

    /** The input was reduced to the start symbol. */
    data object Accept : StepResult

    /**
     * The parse cannot go on.
     *
     * @property error why it cannot go on
     */
    data class Failed(val error: ParseError) : StepResult
}

/**
 * How many tokens have to be shifted after a syntax error before errors are reported again. Suppressing the errors in
 * between keeps one mistake in the input from producing an avalanche of messages which all follow from it.
 */
private const val ERROR_RECOVERY_SHIFTS = 3

/** How many states the stacks start with room for. They grow as a deeper parse needs them to. */
private const val INITIAL_STACK_CAPACITY = 64

/** The lexeme of a node which no input produced. */
private val EMPTY_LEXEME: ByteBuffer = ByteBuffer.allocate(0).asReadOnlyBuffer()

// The parse table is held in lookup tables. A token is translated into the column of the action table which holds the
// decisions for it, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao. The
// gotos are held the same way, with the nonterminal as the column.
//
// The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the action
// table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the tables.
//
// The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
// range check of its own.
//
// Every table is joined from one function per chunk, because a method may hold only 64 KB of bytecode and every top
// level property of this file is initialized in the one class initializer the compiler writes for it.

/** Number of low bits of an action which hold what it does. The value it carries sits above them. */
private const val ACTION_KIND_BITS = 2

/** Selects out of an action what it does. */
private const val ACTION_KIND_MASK = 3

/** Shifts the terminal and continues in the state the action carries. */
private const val ACTION_KIND_SHIFT = 0

/** Reduces by the production the action carries. */
private const val ACTION_KIND_REDUCE = 1

/** Ends the parse successfully, the input having been reduced to the start symbol. */
private const val ACTION_KIND_ACCEPT = 2

/** Rejects the terminal as a syntax error. */
private const val ACTION_KIND_ERROR = 3

/**
 * The column a token gets which is no terminal of this grammar. No state has an entry in it, so a lookup falls through
 * to the default action of the state.
 */
private const val NO_TERMINAL_COLUMN = 0

/** The column holding the shifts of the error symbol, where the recovery reads the state to resume in. */
private const val ERROR_TERMINAL_COLUMN = 0

/**
 * Translates a token into the column of the action table which holds the decisions for it. A token the grammar does not
 * have is not named in the entries and keeps the NO_TERMINAL_COLUMN every unnamed index holds.
 */
private val TERMINAL_COLUMN_BY_TOKEN: ByteArray = newTerminalColumnByToken()

/** Maps a state to the displacement of its row within [ACTION_NEXT]. */
private val ACTION_BASE: ByteArray = actionBase0()

/**
 * Holds the action of every entry. The action a state has for a column lives at `ACTION_BASE[state] + column`, but
 * only if [ACTION_CHECK] confirms the cell belongs to that column.
 */
private val ACTION_NEXT: ByteArray = actionNext0()

/**
 * Holds the column every cell of [ACTION_NEXT] belongs to. A cell no state occupies holds
 * 11, which is one past the highest column in use and can never be asked for.
 */
private val ACTION_CHECK: ByteArray = actionCheck0()

/**
 * Holds the action a state takes for every column it has no entry of its own for. A state which has none carries the
 * error action.
 */
private val DEFAULT_ACTION_BY_STATE: ByteArray = defaultActionByState0()

/** Maps a state to the displacement of its row within [GOTO_NEXT]. */
private val GOTO_BASE: ByteArray = gotoBase0()

/**
 * Holds the state a goto leads to. The goto a state has for a nonterminal lives at `GOTO_BASE[state] + nonterminal`,
 * but only if [GOTO_CHECK] confirms the cell belongs to that nonterminal.
 */
private val GOTO_NEXT: ByteArray = gotoNext0()

/**
 * Holds the nonterminal every cell of [GOTO_NEXT] belongs to. A cell no state occupies holds
 * 2, which is one past the highest nonterminal and can never be asked for.
 */
private val GOTO_CHECK: ByteArray = gotoCheck0()

/** Holds the state a goto on a nonterminal leads to for every state [GOTO_NEXT] has no entry for. */
private val DEFAULT_GOTO_BY_NONTERMINAL: ByteArray = defaultGotoByNonterminal0()

/** Holds how many symbols a reduction takes off the stacks, which is the length of the right hand side. */
private val POP_COUNT_BY_PRODUCTION: ByteArray = popCountByProduction0()

/** Holds the nonterminal on the left hand side of a production. */
private val NONTERMINAL_BY_PRODUCTION: ByteArray = nonterminalByProduction0()

/** Parses the tokens of a scanner into a parse tree. */
class Parser {
    /** The states of the running parse, the current one on top. */
    private var stateStack = IntArray(INITIAL_STACK_CAPACITY)

    /** How many entries of [stateStack] are in use. */
    private var stateStackSize = 0

    /** One node per symbol shifted or reduced so far. */
    private val nodeStack = ArrayList<ParseNode>(INITIAL_STACK_CAPACITY)

    /** The errors of the running parse, which [parse] returns next to the tree. */
    private val errors = ArrayList<ParseError>()

    /**
     * Counts down the tokens which still have to be shifted before syntax errors are reported again. Zero while the
     * parser is in sync with the input.
     */
    private var errorRecoveryShiftsRemaining = 0

    /**
     * Parses the tokens the scanner delivers. Can be called more than once, with a different scanner each time.
     *
     * When the grammar marks places to resume at with the error symbol, a syntax error does not end the parse: the
     * result then holds both the tree parsed so far, with a node for the error symbol at every place resumed at, and
     * every error found. The tree is null when the parse could not be carried to its end.
     *
     * @param scanner the scanner to take the tokens from
     */
    fun parse(scanner: TokenSource): ParseResult {
        // The stacks are emptied rather than replaced, so a parser hands out the room it already has to the parse
        // after it instead of allocating anew.
        stateStackSize = 0
        nodeStack.clear()
        errors.clear()
        errorRecoveryShiftsRemaining = 0

        pushState(0)

        // A source with no tokens at all reports false right away. That is not an error: the token is the end of input
        // either way, and whether a parse of nothing but that is legal is for the table to decide.
        scanner.next()

        while (true) {
            when (val result = step(scanner)) {
                StepResult.Continue -> continue

                // The errors are copied out, because the list they were collected in is handed to the parse after this
                // one.
                StepResult.Accept -> return ParseResult(nodeStack[0], errors.toList())

                is StepResult.Failed -> {
                    if (result.error.kind != ErrorKind.SYNTAX) {
                        // Only an error in the input can be recovered from.
                        errors.add(result.error)
                        return ParseResult(null, errors.toList())
                    }
                    if (errorRecoveryShiftsRemaining == 0) {
                        // While recovering, the parser is not in sync with the input, so the errors it runs into there
                        // follow from the one already reported.
                        errors.add(result.error)
                    }
                    if (!recoverFromError(scanner)) {
                        return ParseResult(null, errors.toList())
                    }
                }
            }
        }
    }

    /**
     * Performs the one action the state on top of the stack takes for the current token. The outcome carries the error
     * only when the parse cannot go on.
     */
    private fun step(scanner: TokenSource): StepResult {
        val terminal = scanner.token

        // A token which is no terminal of this grammar takes the default action of the state.
        val column = terminalColumn(terminal)

        val state = currentState()
        val cellIdx = ACTION_BASE[state].toInt() + column
        // An entry the state has of its own beats its default action, which is what keeps a token the grammar rejects
        // on purpose an error even in a state which reduces on everything else.
        val action = if (ACTION_CHECK[cellIdx].toInt() == column) {
            ACTION_NEXT[cellIdx].toInt()
        } else {
            DEFAULT_ACTION_BY_STATE[state].toInt()
        }

        return when (action and ACTION_KIND_MASK) {
            ACTION_KIND_SHIFT -> {
                pushState(action shr ACTION_KIND_BITS)
                nodeStack.add(ParseNode(TerminalSymbol(terminal), scanner.lexeme, emptyList(), null))
                scanner.next()
                if (errorRecoveryShiftsRemaining > 0) {
                    // Getting tokens of the input shifted again is what makes the parser trust its position.
                    errorRecoveryShiftsRemaining--
                }
                StepResult.Continue
            }

            ACTION_KIND_REDUCE -> {
                reduce(action shr ACTION_KIND_BITS)
                StepResult.Continue
            }

            ACTION_KIND_ACCEPT -> StepResult.Accept

            ACTION_KIND_ERROR ->
                StepResult.Failed(ParseError("unexpected token $terminal", ErrorKind.SYNTAX, scanner))

            else ->
                StepResult.Failed(
                    ParseError("unexpected action $action in state $state", ErrorKind.INTERNAL, scanner),
                )
        }
    }

    /**
     * Replaces the right hand side of the production on the stacks with the nonterminal on its left hand side, and
     * continues in the state the goto of the uncovered state leads to.
     */
    private fun reduce(productionIdx: Int) {
        val popCount = POP_COUNT_BY_PRODUCTION[productionIdx].toInt()
        val nonterminal = NONTERMINAL_BY_PRODUCTION[productionIdx].toInt()

        stateStackSize -= popCount

        val state = currentState()
        val cellIdx = GOTO_BASE[state].toInt() + nonterminal
        // A state without a goto of its own on the nonterminal goes where most states go with it. A state which a
        // reduction uncovers always has one, so there is no case for a nonterminal missing from both.
        val gotoState = if (GOTO_CHECK[cellIdx].toInt() == nonterminal) {
            GOTO_NEXT[cellIdx].toInt()
        } else {
            DEFAULT_GOTO_BY_NONTERMINAL[nonterminal].toInt()
        }
        pushState(gotoState)

        // The right hand side comes off the node stack and is handed over as the children.
        val rightHandSide = nodeStack.subList(nodeStack.size - popCount, nodeStack.size)
        val children = rightHandSide.toList()
        rightHandSide.clear()
        nodeStack.add(
            ParseNode(NonterminalSymbol(Nonterminal.entries[nonterminal]), EMPTY_LEXEME, children, Production.forIdx(productionIdx)),
        )
    }

    /**
     * Puts the parser back where it can carry on with the remaining input after a syntax error. Once it reports false,
     * the parse is given up.
     *
     * This is the panic mode recovery of section 9 "Error Recovery" of "LR Parsing" by Aho and Johnson, in the shape
     * which section 7 "Error Handling" of the yacc report describes: the parser pops its stack until it reaches a
     * state which can shift the error symbol - a place the grammar marked as one to resume at - and shifts the symbol
     * there. Everything the popped states had parsed is discarded with them.
     *
     * The token which caused the error is kept for the resumed state to look at, because that state is usually waiting
     * for exactly it: in a production like "{" @error "}" it is the closing brace which ends the recovery. Only when
     * the parse fails on that very same token again is the token discarded, which is what an untouched countdown of
     * tokens to shift tells us. Popping and discarding in the same handler is what guarantees progress: every round of
     * recovery either gets the parse going again or consumes one token of the input, so a parse cannot get stuck
     * between the two.
     */
    private fun recoverFromError(scanner: TokenSource): Boolean {
        if (errorRecoveryShiftsRemaining == ERROR_RECOVERY_SHIFTS) {
            // Nothing was shifted since the last error, so the parser is failing on the token it already failed on.
            if (scanner.token == Token.END_TOKEN) {
                // The end of input is the one token which cannot be discarded.
                return false
            }
            scanner.next()
        }
        errorRecoveryShiftsRemaining = ERROR_RECOVERY_SHIFTS

        while (true) {
            val nextState = errorShiftState(currentState())
            if (nextState != null) {
                // Shift the error symbol. Its node stands for the dropped part of the input and has no lexeme.
                pushState(nextState)
                nodeStack.add(ParseNode(TerminalSymbol(Token.ERROR_TOKEN), EMPTY_LEXEME, emptyList(), null))
                return true
            }
            if (stateStackSize == 1) {
                // Only the state the parse started in is left and it cannot shift the error symbol either.
                return false
            }
            // The state cannot resume here, so it is dropped together with what it had parsed. One state carries one
            // node, so dropping one drops one.
            stateStackSize--
            nodeStack.removeAt(nodeStack.size - 1)
        }
    }

    /** Returns the state on top of the stack, which is the one the parse is in. */
    private fun currentState(): Int = stateStack[stateStackSize - 1]

    /** Puts the given state on top of the stack, growing it when it is full. */
    private fun pushState(state: Int) {
        if (stateStackSize == stateStack.size) {
            stateStack = stateStack.copyOf(stateStack.size * 2)
        }
        stateStack[stateStackSize] = state
        stateStackSize++
    }
}

/**
 * Returns the column of the action table which holds the decisions for the given token. A token the grammar does not
 * have, and one outside the range the scanner promises, both get [NO_TERMINAL_COLUMN].
 */
private fun terminalColumn(terminal: Token): Int =
    TERMINAL_COLUMN_BY_TOKEN.getOrElse(terminal.ordinal) { NO_TERMINAL_COLUMN.toByte() }.toInt()

/**
 * Returns the state to continue in when the error symbol is shifted in the given state, or null when the state cannot
 * shift it. The states which can are the places the grammar marked to resume at after a syntax error.
 *
 * The default action of the state is deliberately not consulted, because only an entry the state has of its own is a
 * place to resume at.
 */
private fun errorShiftState(state: Int): Int? {
    val cellIdx = ACTION_BASE[state].toInt() + ERROR_TERMINAL_COLUMN
    if (ACTION_CHECK[cellIdx].toInt() != ERROR_TERMINAL_COLUMN) {
        return null
    }

    val action = ACTION_NEXT[cellIdx].toInt()
    if ((action and ACTION_KIND_MASK) != ACTION_KIND_SHIFT) {
        return null
    }
    return action shr ACTION_KIND_BITS
}

/**
 * Builds [TERMINAL_COLUMN_BY_TOKEN] from the tokens and the columns they stand at, sized to the highest token named.
 */
private fun newTerminalColumnByToken(): ByteArray {
    val columnByToken = listOf(
        Token.END_TOKEN to 1,
        Token.TOKEN_WHITESPACE to 2,
        Token.TOKEN_INTEGER to 3,
        Token.TOKEN_PLUS to 4,
        Token.TOKEN_MINUS to 5,
        Token.TOKEN_MULTIPLY to 6,
        Token.TOKEN_DIVIDE to 7,
        Token.TOKEN_LPAREN to 8,
        Token.TOKEN_RPAREN to 9,
        Token.TOKEN_UMINUS to 10,
    )

    val result = ByteArray(columnByToken.maxOf { (token, _) -> token.ordinal } + 1)
    for ((token, column) in columnByToken) {
        result[token.ordinal] = column.toByte()
    }
    return result
}

/** Returns chunk 0 of [ACTION_BASE]. */
private fun actionBase0(): ByteArray = byteArrayOf(
    9, 1, 9, 9, 0, 1, 4, 1, 9, 9, 9, 9, 1, 12, 12, 1,
    1,
)

/** Returns chunk 0 of [ACTION_NEXT]. */
private fun actionNext0(): ByteArray = byteArrayOf(
    0, 28, 0, 0, 32, 36, 40, 44, 32, 36, 40, 44, 4, 48, 8, 0,
    0, 12, 40, 44, 0, 0, 0,
)

/** Returns chunk 0 of [ACTION_CHECK]. */
private fun actionCheck0(): ByteArray = byteArrayOf(
    11, 1, 11, 11, 4, 5, 6, 7, 4, 5, 6, 7, 3, 9, 5, 11,
    11, 8, 6, 7, 11, 11, 11,
)

/** Returns chunk 0 of [DEFAULT_ACTION_BY_STATE]. */
private fun defaultActionByState0(): ByteArray = byteArrayOf(
    3, 5, 3, 3, 3, 25, 3, 2, 3, 3, 3, 3, 29, 9, 13, 17,
    21,
)

/** Returns chunk 0 of [GOTO_BASE]. */
private fun gotoBase0(): ByteArray = byteArrayOf(
    6, 6, 0, 1, 6, 6, 6, 6, 2, 3, 4, 5, 6, 6, 6, 6,
    6,
)

/** Returns chunk 0 of [GOTO_NEXT]. */
private fun gotoNext0(): ByteArray = byteArrayOf(
    0, 5, 6, 13, 14, 15, 16, 0,
)

/** Returns chunk 0 of [GOTO_CHECK]. */
private fun gotoCheck0(): ByteArray = byteArrayOf(
    2, 1, 1, 1, 1, 1, 1, 2,
)

/** Returns chunk 0 of [DEFAULT_GOTO_BY_NONTERMINAL]. */
private fun defaultGotoByNonterminal0(): ByteArray = byteArrayOf(
    0, 4,
)

/** Returns chunk 0 of [POP_COUNT_BY_PRODUCTION]. */
private fun popCountByProduction0(): ByteArray = byteArrayOf(
    2, 1, 3, 3, 3, 3, 2, 3,
)

/** Returns chunk 0 of [NONTERMINAL_BY_PRODUCTION]. */
private fun nonterminalByProduction0(): ByteArray = byteArrayOf(
    0, 1, 1, 1, 1, 1, 1, 1,
)
