// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

/**
 * Every terminal symbol this scanner knows.
 *
 * @readonly
 * @enum {number}
 */
export const Token = Object.freeze({
    /** No token was found. */
    InvalidToken: 0,

    /** The end of the source was reached. */
    EndToken: 1,

    /** The symbol a grammar marks its error recovery points with. No input ever produces it. */
    ErrorToken: 2,

    TokenWhitespace: 3,
    TokenInteger: 4,
    TokenPlus: 5,
    TokenMinus: 6,
    TokenMultiply: 7,
    TokenDivide: 8,
    TokenLparen: 9,
    TokenRparen: 10,
    TokenUminus: 11,
});

/**
 * Returns the name of the token, as the grammar spells it.
 *
 * @param {number} token
 * @returns {string}
 */
export function tokenToString(token) {
    switch (token) {
        case Token.InvalidToken: return "invalid token";
        case Token.EndToken: return "end token";
        case Token.ErrorToken: return "error token";
        case Token.TokenWhitespace: return "WHITESPACE";
        case Token.TokenInteger: return "INTEGER";
        case Token.TokenPlus: return "PLUS";
        case Token.TokenMinus: return "MINUS";
        case Token.TokenMultiply: return "MULTIPLY";
        case Token.TokenDivide: return "DIVIDE";
        case Token.TokenLparen: return "LPAREN";
        case Token.TokenRparen: return "RPAREN";
        case Token.TokenUminus: return "UMINUS";
        default:
            return "unknown";
    }
}

/**
 * Reports whether the grammar marked the token for skipping, which is what the token skipper drops.
 *
 * @param {number} token
 * @returns {boolean}
 */
export function isSkipped(token) {
    switch (token) {
        case Token.TokenWhitespace: return true;
        default:
            return false;
    }
}

/**
 * Where a byte offset of the source is, in the terms a human reads: the file the scanner was given, the offset itself,
 * and the line and column it falls on.
 *
 * @typedef {object} Position
 * @property {string} filePath The file path the scanner was given.
 * @property {number} byteOffset The offset this position was resolved for, in bytes from the start of the source.
 * @property {number} line The line the offset falls on, counted from one. Only a line feed starts a new line, so the
 *     carriage return of a CRLF pair is the last byte of the line it ends.
 * @property {number} column The column the offset falls on, counted from one in bytes.
 */

/**
 * What a scanner offers. Both Scanner and TokenSkipper implement it.
 *
 * @typedef {object} TokenSource
 * @property {() => number} token
 * @property {() => number} byteOffset
 * @property {() => number} byteLength
 * @property {() => Uint8Array} lexeme
 * @property {(byteOffset: number) => Position} position
 * @property {(byteOffset: number, byteLength: number) => Uint8Array} text
 * @property {() => string} filePath
 * @property {(source: Uint8Array, offset: number) => void} reset
 * @property {() => boolean} next
 */

/**
 * Wraps a scanner and skips the tokens marked for skipping, which are usually whitespace and comments. It offers the
 * same methods as Scanner.
 */
export class TokenSkipper {
    /**
     * The wrapped scanner.
     *
     * @type {TokenSource}
     */
    #scanner;

    /**
     * @param {TokenSource} scanner
     */
    constructor(scanner) {
        this.#scanner = scanner;
    }

    /**
     * Returns the current token.
     *
     * @returns {number}
     */
    token() {
        return this.#scanner.token();
    }

    /**
     * Returns the start of the token in bytes from the start of the source. After next returned false it is the offset
     * one past the last byte.
     *
     * @returns {number}
     */
    byteOffset() {
        return this.#scanner.byteOffset();
    }

    /**
     * Returns the length of the token in bytes. After next returned false it is zero.
     *
     * @returns {number}
     */
    byteLength() {
        return this.#scanner.byteLength();
    }

    /**
     * Returns the bytes of the token, as a view into the source rather than a copy of it.
     *
     * @returns {Uint8Array}
     */
    lexeme() {
        return this.#scanner.lexeme();
    }

    /**
     * Resolves a byte offset of the source into file path, line and column. Offsets from zero up to and including the
     * length of the source are valid, the last of them being the end of the source, and an offset outside of that is
     * clamped into it.
     *
     * @param {number} byteOffset
     * @returns {Position}
     */
    position(byteOffset) {
        return this.#scanner.position(byteOffset);
    }

    /**
     * Returns the bytes the given span covers, as a view into the source rather than a copy of it. The span is clamped
     * to the source, and a negative length is empty.
     *
     * @param {number} byteOffset
     * @param {number} byteLength
     * @returns {Uint8Array}
     */
    text(byteOffset, byteLength) {
        return this.#scanner.text(byteOffset, byteLength);
    }

    /**
     * Returns the file path the scanner was given.
     *
     * @returns {string}
     */
    filePath() {
        return this.#scanner.filePath();
    }

    /**
     * Scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
     * changed.
     *
     * @param {Uint8Array} source
     * @param {number} offset
     */
    reset(source, offset) {
        this.#scanner.reset(source, offset);
    }

    /**
     * Advances to the next token which is not marked for skipping. Returns false when the source holds no such token
     * any more.
     *
     * @returns {boolean}
     */
    next() {
        while (this.#scanner.next()) {
            if (!isSkipped(this.#scanner.token())) {
                return true;
            }
        }
        return false;
    }
}

// The automaton is held in lookup tables. An input byte is mapped to its byte class, which is the column of the
// transition table, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao.
//
// The displaced arrays are padded so that every state and byte class lands inside them, which is why a lookup needs no
// range check of its own.

/** Maps an input byte to its byte class. Bytes which every state treats alike share a class. */
const byteClassByByte = new Uint8Array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 0, 6, 0, 7,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
]);

/** Maps a state to the displacement of its row within transitionNext. */
const transitionBase = new Uint8Array([
    0, 8, 2, 1, 1, 1, 1, 1, 1,
]);

/**
 * Holds the target state of every transition. The transition a state has on a byte class lives at
 * transitionBase[state] + class, but only if transitionCheck confirms the cell belongs to that class.
 */
const transitionNext = new Uint8Array([
    0, 1, 7, 8, 5, 3, 4, 6, 2, 1, 2, 0, 0, 0, 0, 0,
    0,
]);

/**
 * Holds the byte class every cell of transitionNext belongs to. A cell no state occupies holds
 * 9, which is one past the highest byte class in use and can never be asked for.
 */
const transitionCheck = new Uint8Array([
    9, 1, 2, 3, 4, 5, 6, 7, 8, 1, 8, 9, 9, 9, 9, 9,
    9,
]);

/** Holds the token a state accepts, or InvalidToken for a state which does not accept. */
const acceptTokenByState = new Uint8Array([
    Token.InvalidToken,
    Token.TokenWhitespace,
    Token.TokenInteger,
    Token.TokenPlus,
    Token.TokenMinus,
    Token.TokenMultiply,
    Token.TokenDivide,
    Token.TokenLparen,
    Token.TokenRparen,
]);

/**
 * Turns the bytes of a source into tokens.
 */
export class Scanner {
    /**
     * The bytes being scanned.
     *
     * @type {Uint8Array}
     */
    #source;

    /**
     * The file path the scanner was given.
     *
     * @type {string}
     */
    #filePath;

    /**
     * The current token.
     *
     * @type {number}
     */
    #token;

    /**
     * Index of the first byte of the current token.
     *
     * @type {number}
     */
    #lexemeStartIdx;

    /**
     * Index one past the last byte of the current token.
     *
     * @type {number}
     */
    #lexemeEndIdx;

    /**
     * The byte offset every line of the source begins at. It is built on the first call to position and emptied by
     * reset, which keeps its storage for the next source.
     *
     * @type {number[]}
     */
    #lineStarts = [];

    /**
     * @param {Uint8Array} source The bytes to scan.
     * @param {string} filePath Used in error messages. Any string will do when the source is not a file.
     */
    constructor(source, filePath) {
        this.#filePath = filePath;
        this.reset(source, 0);
    }

    /**
     * Returns the current token.
     *
     * @returns {number}
     */
    token() {
        return this.#token;
    }

    /**
     * Returns the start of the token in bytes from the start of the source. After next returned false it is the offset
     * one past the last byte.
     *
     * @returns {number}
     */
    byteOffset() {
        return this.#lexemeStartIdx;
    }

    /**
     * Returns the length of the token in bytes. After next returned false it is zero.
     *
     * @returns {number}
     */
    byteLength() {
        return this.#lexemeEndIdx - this.#lexemeStartIdx;
    }

    /**
     * Returns the bytes of the token, as a view into the source rather than a copy of it.
     *
     * @returns {Uint8Array}
     */
    lexeme() {
        return this.#source.subarray(this.#lexemeStartIdx, this.#lexemeEndIdx);
    }

    /**
     * Resolves a byte offset of the source into file path, line and column. Offsets from zero up to and including the
     * length of the source are valid, the last of them being the end of the source, and an offset outside of that is
     * clamped into it.
     *
     * @param {number} byteOffset
     * @returns {Position}
     */
    position(byteOffset) {
        byteOffset = Math.min(Math.max(byteOffset, 0), this.#source.length);

        if (this.#lineStarts.length === 0) {
            this.#buildLineStarts();
        }

        const line = this.#lineAt(byteOffset);
        return {
            filePath: this.#filePath,
            byteOffset: byteOffset,
            line: line,
            column: byteOffset - this.#lineStarts[line - 1] + 1,
        };
    }

    /**
     * Fills in the byte offset every line of the source begins at, into the storage left over from the source before.
     * The first line begins at zero, so the result is never empty and an empty source has one line.
     */
    #buildLineStarts() {
        this.#lineStarts.push(0);
        for (let byteOffset = 0; byteOffset < this.#source.length;) {
            const lineFeedIdx = this.#source.indexOf(0x0a, byteOffset);
            if (lineFeedIdx < 0) {
                break;
            }
            byteOffset = lineFeedIdx + 1;
            this.#lineStarts.push(byteOffset);
        }
    }

    /**
     * Returns the line the given offset falls on, counted from one. The search is written out, because the language
     * has none to call: it settles on the first line start past the offset, and the number of lines in front of that
     * is the line the offset falls on.
     *
     * @param {number} byteOffset
     * @returns {number}
     */
    #lineAt(byteOffset) {
        let lowIdx = 0;
        let highIdx = this.#lineStarts.length;
        while (lowIdx < highIdx) {
            const midIdx = (lowIdx + highIdx) >>> 1;
            if (this.#lineStarts[midIdx] <= byteOffset) {
                lowIdx = midIdx + 1;
            } else {
                highIdx = midIdx;
            }
        }
        return lowIdx;
    }

    /**
     * Returns the bytes the given span covers, as a view into the source rather than a copy of it. The span is clamped
     * to the source, and a negative length is empty.
     *
     * @param {number} byteOffset
     * @param {number} byteLength
     * @returns {Uint8Array}
     */
    text(byteOffset, byteLength) {
        const startIdx = Math.min(Math.max(byteOffset, 0), this.#source.length);
        // Clamping the length against what is left rather than the end against the source, because subarray reads a
        // negative end as one counted back from the end of the source.
        const length = Math.min(Math.max(byteLength, 0), this.#source.length - startIdx);
        return this.#source.subarray(startIdx, startIdx + length);
    }

    /**
     * Returns the file path the scanner was given.
     *
     * @returns {string}
     */
    filePath() {
        return this.#filePath;
    }

    /**
     * Scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
     * changed.
     *
     * @param {Uint8Array} source
     * @param {number} offset
     */
    reset(source, offset) {
        this.#source = source;

        this.#lexemeStartIdx = 0;
        // An offset past the end of the source would point at bytes which are not there. Clamping it leaves the
        // scanner at the end of the source, where it reports the end token.
        this.#lexemeEndIdx = Math.min(offset, source.length);

        // The line starts belong to the source which was replaced here, but their storage is worth keeping.
        this.#lineStarts.length = 0;

        this.#token = Token.InvalidToken;
    }

    /**
     * Advances to the next token. Bytes which form no token become an invalid token. Returns false once the end of the
     * source is reached, which sets the token to the end token.
     *
     * @returns {boolean}
     */
    next() {
        this.#lexemeStartIdx = this.#lexemeEndIdx;

        let state = 0;
        let lexemePeekIdx = this.#lexemeEndIdx;
        for (;;) {
            // Remember every accepting state passed through, so the longest match wins over the first one.
            if (acceptTokenByState[state] !== Token.InvalidToken) {
                this.#token = acceptTokenByState[state];
                this.#lexemeEndIdx = lexemePeekIdx;
            }
            if (lexemePeekIdx === this.#source.length) {
                // The end of the source is reached, so the state it stopped in was the last one to test.
                break;
            }

            const byteClass = byteClassByByte[this.#source[lexemePeekIdx]];
            const cellIdx = transitionBase[state] + byteClass;
            if (transitionCheck[cellIdx] !== byteClass) {
                // The state has no transition on this byte, so the token ends here.
                break;
            }
            state = transitionNext[cellIdx];
            lexemePeekIdx++;
        }

        if (this.#lexemeStartIdx < this.#lexemeEndIdx) {
            // A token was found.
            return true;
        }

        if (this.#source.length <= this.#lexemeStartIdx) {
            // The end of the source was reached.
            this.#token = Token.EndToken;
            return false;
        }

        // The bytes here form no token. The invalid token ends where the automaton stopped, because the byte it could
        // not consume is where the next attempt starts. Only when the automaton consumed nothing does it cover that
        // byte, which is what keeps the scan moving forward.
        this.#token = Token.InvalidToken;
        this.#lexemeEndIdx = Math.max(this.#lexemeStartIdx + 1, lexemePeekIdx);
        return true;
    }
}
