changelogDir: changelog
catalogFileName: changelog.yaml
unreleasedDir: unreleased
unreleasedFilePattern: changelog-20060102-150405
changelogFileName: CHANGELOG.md
# CHANGELOG.md is shown on the Visual Studio Marketplace, so it has no note for developers and no empty Unreleased
# section.
template: |-
  # Changelog
  {{if .Catalog.Unreleased}}
  ## Unreleased

  {{range .Catalog.Unreleased}}- {{.Description | trim}}
  {{end}}{{end}}
  {{range .Catalog.Releases}}## {{.Version | trim}} ({{.Date.Format "2006-01-02"}})

  {{range .Entries}}- {{.Description | trim}}
  {{end}}
  {{end}}
