#!/usr/bin/env bash

# This script extracts the changelog section of a single release from CHANGELOG.md, so it can be handed to GoReleaser
# via "--release-notes". Without it, GoReleaser would fall back to generating release notes from the git commit list,
# which is far too detailed for the average user.
#
# CHANGELOG.md itself is generated by the changelog utility (https://github.com/backbone81/changelog) from
# changelog/changelog.yaml. The heading format matched below is the one produced by the template in .changelog.yaml.
#
# Usage: scripts/release-notes.sh [TAG]
#
# TAG defaults to the tag GoReleaser is currently building, or to the most recent tag reachable from HEAD.

set -e

TAG="${1:-${GORELEASER_CURRENT_TAG:-$(git describe --tags --abbrev=0)}}"
CHANGELOG_FILE_PATH="$(dirname "$0")/../CHANGELOG.md"

NOTES="$(awk -v tag="${TAG}" '
    BEGIN { heading = "## " tag " (" }
    # A new second level heading ends the section we are interested in.
    /^## / { if (found) exit }
    index($0, heading) == 1 { found = 1; next }
    # Blank lines are buffered and only emitted once more content follows. That drops the blank lines surrounding the
    # section while keeping the ones between entries.
    found && /^[[:space:]]*$/ { blanks++; next }
    found {
        if (started) {
            while (blanks-- > 0) print ""
        }
        blanks = 0
        started = 1
        print
    }
' "${CHANGELOG_FILE_PATH}")"

if [ -z "${NOTES}" ]; then
    echo "No changelog entries found for release ${TAG} in ${CHANGELOG_FILE_PATH}" >&2
    exit 1
fi

printf '%s\n' "${NOTES}"
