// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser

import (
	"errors"
	"fmt"
)

// Nonterminal is the data type representing all nonterminal symbols.
type Nonterminal int

const (
	// AcceptNonterminal is the start symbol the generator adds around the one the grammar declares.
	// Reaching it accepts the input.
	AcceptNonterminal Nonterminal = 0

	NonterminalFile                      Nonterminal = 1
	NonterminalScannerSection            Nonterminal = 2
	NonterminalScannerDeclList           Nonterminal = 3
	NonterminalScannerDecl               Nonterminal = 4
	NonterminalScannerDeclRhs            Nonterminal = 5
	NonterminalScannerPattern            Nonterminal = 6
	NonterminalScannerAnnotationList     Nonterminal = 7
	NonterminalScannerAnnotation         Nonterminal = 8
	NonterminalParserSection             Nonterminal = 9
	NonterminalStartDecl                 Nonterminal = 10
	NonterminalPrecedenceSection         Nonterminal = 11
	NonterminalPrecedenceDeclList        Nonterminal = 12
	NonterminalPrecedenceDecl            Nonterminal = 13
	NonterminalAssociativity             Nonterminal = 14
	NonterminalRuleDeclList              Nonterminal = 15
	NonterminalProductionDecl            Nonterminal = 16
	NonterminalAlternativeList           Nonterminal = 17
	NonterminalAlternative               Nonterminal = 18
	NonterminalAlternativeAnnotationList Nonterminal = 19
	NonterminalAlternativeAnnotation     Nonterminal = 20
	NonterminalSymbolList                Nonterminal = 21
	NonterminalSymbol                    Nonterminal = 22
)

// Nonterminal implements fmt.Stringer.
var _ fmt.Stringer = (*Nonterminal)(nil)

// String returns a string representation of the nonterminal.
func (n Nonterminal) String() string {
	switch n {
	case AcceptNonterminal:
		return `$accept`
	case NonterminalFile:
		return `file`
	case NonterminalScannerSection:
		return `scanner_section`
	case NonterminalScannerDeclList:
		return `scanner_decl_list`
	case NonterminalScannerDecl:
		return `scanner_decl`
	case NonterminalScannerDeclRhs:
		return `scanner_decl_rhs`
	case NonterminalScannerPattern:
		return `scanner_pattern`
	case NonterminalScannerAnnotationList:
		return `scanner_annotation_list`
	case NonterminalScannerAnnotation:
		return `scanner_annotation`
	case NonterminalParserSection:
		return `parser_section`
	case NonterminalStartDecl:
		return `start_decl`
	case NonterminalPrecedenceSection:
		return `precedence_section`
	case NonterminalPrecedenceDeclList:
		return `precedence_decl_list`
	case NonterminalPrecedenceDecl:
		return `precedence_decl`
	case NonterminalAssociativity:
		return `associativity`
	case NonterminalRuleDeclList:
		return `rule_decl_list`
	case NonterminalProductionDecl:
		return `production_decl`
	case NonterminalAlternativeList:
		return `alternative_list`
	case NonterminalAlternative:
		return `alternative`
	case NonterminalAlternativeAnnotationList:
		return `alternative_annotation_list`
	case NonterminalAlternativeAnnotation:
		return `alternative_annotation`
	case NonterminalSymbolList:
		return `symbol_list`
	case NonterminalSymbol:
		return `symbol`
	default:
		return "unknown"
	}
}

// Symbol is either a terminal or a nonterminal. The most significant bit is used to signal a
// nonterminal. The maximum terminal or nonterminal index which can be stored is 32767.
type Symbol uint16

const (
	// symbolNonterminalBit is the most significant bit which is set when the Symbol stores a nonterminal.
	symbolNonterminalBit = 1 << 15

	// symbolMask is the bitmask for selecting only the value from Symbol.
	symbolMask = symbolNonterminalBit - 1
)

// NewTerminal creates a new Symbol for a terminal.
func NewTerminal(terminal Token) Symbol {
	return Symbol(terminal)
}

// NewNonterminal creates a new Symbol for a nonterminal.
func NewNonterminal(nonterminal Nonterminal) Symbol {
	return Symbol(symbolNonterminalBit | nonterminal)
}

// Terminal returns the terminal value of the Symbol. The boolean reports if the value is in fact a terminal.
func (s Symbol) Terminal() (Token, bool) {
	return Token(s & symbolMask), s&symbolNonterminalBit == 0
}

// Nonterminal returns the nonterminal value of the Symbol. The boolean reports if the value is in fact a nonterminal.
func (s Symbol) Nonterminal() (Nonterminal, bool) {
	return Nonterminal(s & symbolMask), s&symbolNonterminalBit != 0
}

// Symbol implements fmt.Stringer.
var _ fmt.Stringer = (*Symbol)(nil)

// String returns a string representation.
func (s Symbol) String() string {
	nonterminal, ok := s.Nonterminal()
	if ok {
		return fmt.Sprintf("nonterminal %s", nonterminal)
	}
	terminal, _ := s.Terminal()
	return fmt.Sprintf("terminal %s", terminal)
}

// Node is a single node of the parse tree.
type Node struct {
	Symbol   Symbol
	Lexeme   []byte
	Children []Node
}

// ParserScanner is the interface the scanner for the parser needs to implement.
type ParserScanner interface {
	Token() Token
	ByteOffset() int
	Line() int
	Column() int
	Lexeme() []byte
	Next() bool
	FilePath() string
}

var (
	// This error is used in cases where the mechanic of the parser is wrong.
	ErrInternal = errors.New("internal parser error")

	// ErrSyntax marks an error in the input: a token which the grammar does not allow at the position it was found at.
	// Those are the errors the parser recovers from when the grammar marks places to resume at with the error symbol,
	// so Parse can return several of them joined together.
	ErrSyntax = errors.New("syntax error")
)

// errorRecoveryShifts is the number of tokens which have to be shifted after a syntax error before the parser reports
// errors again. Suppressing the errors in between keeps a single mistake in the input from producing an avalanche of
// messages which are all consequences of the first one. It is the number of tokens yacc and GNU Bison use, see
// section 7 "Error Handling" of the yacc report.
const errorRecoveryShifts = 3

// arenaChunkSize is the number of nodes the arena allocator hands out from a single chunk. A parse which needs more
// nodes than one chunk holds takes further chunks of the same size and keeps them for the parses after it.
const arenaChunkSize = 16 * 1024

// Error represents a single parse error.
type Error struct {
	Token      Token
	ByteOffset int
	Line       int
	Column     int
	Lexeme     []byte
	FilePath   string
	Cause      error
}

// Error implements error
var _ error = (*Error)(nil)

// Error returns an string describing this error.
func (e *Error) Error() string {
	return fmt.Sprintf("%s:%d:%d: %s", e.FilePath, e.Line, e.Column, e.Cause)
}

func (e *Error) Unwrap() error {
	return e.Cause
}

// The parse table is held in lookup tables. A token is translated into the column of the action table which holds the
// decisions for it, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao. The
// gotos are held the same way, with the nonterminal as the column.
//
// The rows are sparse because what most entries of a row agree on is taken out of it and kept as a default: the action
// table defaults per state and the goto table per nonterminal. Only the entries which deviate are in the tables.
//
// The displaced arrays are padded so that every state and column lands inside them, which is why a lookup needs no
// range check of its own.
const (
	// actionKindBits is the number of low bits of an action which hold what it does. The value it carries sits above
	// them.
	actionKindBits = 2

	// actionKindMask selects out of an action what it does.
	actionKindMask = 3

	// actionKindShift shifts the terminal and continues in the state the action carries.
	actionKindShift = 0

	// actionKindReduce reduces by the production the action carries.
	actionKindReduce = 1

	// actionKindAccept ends the parse successfully, the input having been reduced to the start symbol.
	actionKindAccept = 2

	// actionKindError rejects the terminal as a syntax error.
	actionKindError = 3

	// noTerminalColumn is the column a token gets which is no terminal of this grammar. No state has an entry in it,
	// so a lookup falls through to the default action of the state.
	noTerminalColumn = 0

	// errorTerminalColumn is the column holding the shifts of the error symbol, where the recovery reads the state to
	// resume in.
	errorTerminalColumn = 0
)

var (
	// terminalColumnByToken translates a token into the column of the action table which holds the decisions for it.
	//
	// The entries are indexed by the token constants themselves, which lets the compiler place each of them at
	// whatever value the scanner gave it. Neither generator has to know the numbering of the other because of that.
	// A token the grammar does not have is not named here at all and keeps the noTerminalColumn every unnamed index
	// holds.
	terminalColumnByToken = [...]uint8{
		EndToken:        1,
		TokenWhitespace: 2,
		TokenComment:    3,
		TokenScanner:    4,
		TokenParser:     5,
		TokenPrecedence: 6,
		TokenStart:      7,
		TokenLeft:       8,
		TokenRight:      9,
		TokenNone:       10,
		TokenSkip:       11,
		TokenEmpty:      12,
		TokenError:      13,
		TokenFragment:   14,
		TokenLbrace:     15,
		TokenRbrace:     16,
		TokenLparen:     17,
		TokenRparen:     18,
		TokenColon:      19,
		TokenSemi:       20,
		TokenPipe:       21,
		TokenComma:      22,
		TokenName:       23,
		TokenRegex:      24,
		TokenString:     25,
	}

	// actionBase maps a state to the displacement of its row within actionNext.
	actionBase = [68]uint8{
		3, 4, 10, 7, 6, 6, 19, 6, 12, 11, 6, 21, 6, 22, 30, 5,
		20, 27, 6, 6, 6, 6, 24, 6, 25, 6, 16, 9, 6, 9, 6, 0,
		6, 28, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 29, 1, 8, 6,
		6, 6, 6, 17, 6, 8, 6, 2, 40, 6, 1, 40, 6, 6, 32, 6,
		6, 8, 33, 6,
	}

	// actionNext holds the action of every entry. The action a state has for a column lives at
	// actionBase[state] + column, but only if actionCheck confirms the cell belongs to that column.
	actionNext = [66]uint16{
		0, 0, 0, 0, 0, 0, 152, 4, 156, 160, 164, 20, 24, 188, 192, 192,
		168, 76, 52, 16, 140, 192, 244, 144, 196, 196, 200, 200, 40, 80, 84, 196,
		128, 200, 36, 44, 68, 228, 232, 132, 60, 64, 100, 96, 112, 120, 248, 180,
		184, 260, 0, 268, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		0, 0,
	}

	// actionCheck holds the column every cell of actionNext belongs to. A cell no state occupies holds
	// 26, which is one past the highest column in use and can never be asked for.
	actionCheck = [66]uint8{
		26, 26, 26, 26, 26, 26, 6, 4, 8, 9, 10, 1, 5, 12, 13, 13,
		16, 12, 7, 15, 11, 13, 20, 14, 23, 23, 25, 25, 16, 24, 25, 23,
		16, 25, 15, 23, 6, 20, 21, 23, 19, 19, 15, 23, 20, 20, 6, 19,
		19, 17, 26, 18, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
		26, 26,
	}

	// defaultActionByState holds the action a state takes for every column it has no entry of its own for. A state
	// which has none carries the error action.
	defaultActionByState = [68]uint8{
		3, 3, 3, 3, 13, 2, 3, 5, 3, 61, 9, 3, 17, 3, 69, 3,
		3, 3, 105, 41, 33, 37, 3, 41, 3, 77, 3, 29, 21, 25, 65, 3,
		57, 3, 109, 49, 53, 45, 101, 89, 93, 97, 73, 81, 3, 3, 3, 133,
		161, 153, 157, 3, 117, 133, 145, 3, 129, 113, 3, 125, 149, 85, 3, 137,
		121, 3, 3, 141,
	}

	// gotoBase maps a state to the displacement of its row within gotoNext.
	gotoBase = [68]uint8{
		5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
		5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5,
		5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5,
		5, 5, 5, 5, 5, 0, 5, 3, 5, 5, 6, 5, 5, 5, 5, 5,
		5, 4, 5, 5,
	}

	// gotoNext holds the state a goto leads to. The goto a state has for a nonterminal lives at
	// gotoBase[state] + nonterminal, but only if gotoCheck confirms the cell belongs to that nonterminal.
	gotoNext = [29]uint8{
		0, 0, 0, 0, 0, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 59, 0, 0, 60, 55, 64, 60, 66, 0, 0,
	}

	// gotoCheck holds the nonterminal every cell of gotoNext belongs to. A cell no state occupies holds
	// 23, which is one past the highest nonterminal and can never be asked for.
	gotoCheck = [29]uint8{
		23, 23, 23, 23, 23, 23, 23, 23, 7, 23, 23, 23, 23, 23, 23, 23,
		23, 23, 23, 19, 23, 23, 22, 21, 18, 22, 22, 23, 23,
	}

	// defaultGotoByNonterminal holds the state a goto on a nonterminal leads to for every state gotoNext has no entry
	// for.
	defaultGotoByNonterminal = [23]uint8{
		0, 2, 3, 8, 12, 22, 23, 27, 37, 7, 14, 18, 31, 43, 44, 26,
		34, 51, 52, 56, 63, 53, 54,
	}

	// popCountByProduction holds how many symbols a reduction takes off the stacks, which is the length of the right
	// hand side.
	popCountByProduction = [41]uint8{
		2, 2, 4, 0, 2, 4, 2, 2, 1, 1, 0, 2, 1, 1, 6, 0,
		4, 0, 4, 0, 2, 4, 1, 1, 1, 1, 0, 2, 4, 1, 3, 2,
		2, 0, 2, 4, 1, 2, 1, 1, 1,
	}

	// nonterminalByProduction holds the nonterminal on the left hand side of a production.
	nonterminalByProduction = [41]uint8{
		0, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 10,
		10, 11, 11, 12, 12, 13, 14, 14, 14, 14, 15, 15, 16, 17, 17, 18,
		18, 19, 19, 20, 21, 21, 22, 22, 22,
	}
)

// Parser provides the parser implementation.
type Parser struct {
	scanner ParserScanner

	stateStack []int
	nodeStack  []Node

	// arenaChunks holds every chunk of nodes the parser has allocated so far, in the order they are handed out. A
	// parse starts over at the first chunk instead of allocating new ones, so only a parse which needs more nodes
	// than every parse before it adds a chunk. Parse invalidates the tree of the parse before it in any case, so
	// handing the memory of that tree out again takes away nothing a caller could rely on.
	arenaChunks   [][]Node
	arenaChunkIdx int

	// arenaAllocator is the chunk nodes are handed out from at the moment, which aliases arenaChunks[arenaChunkIdx].
	// Keeping it here lets allocateNodes read the room left in the chunk straight off the parser.
	arenaAllocator    []Node
	arenaAllocatorTop int

	// errors collects the syntax errors of the current parse, which Parse returns joined together.
	errors []error

	// errorRecoveryShiftsRemaining counts down the tokens which still have to be shifted before syntax errors are
	// reported again. It is zero while the parser is in sync with the input and errorRecoveryShifts right after the
	// error symbol was shifted.
	errorRecoveryShiftsRemaining int
}

// NewParser creates a new parser.
func NewParser() *Parser {
	parser := Parser{
		stateStack:  make([]int, 0, 1024),
		nodeStack:   make([]Node, 0, 1024),
		arenaChunks: [][]Node{make([]Node, arenaChunkSize)},
	}
	parser.resetArena()
	return &parser
}

// errAccept is used to signal the successful end of the parse. It is filtered out by the main parse loop and not
// exposed to the user.
var errAccept = errors.New("accept")

// Parse executes a parse on the tokens provided by the scanner and returns a parse tree or an error. Parse can be
// called multiple times with different scanners to re-use the memory already allocated by the parser.
//
// When the grammar marks places to resume at with the error symbol, the parser recovers from a syntax error and carries
// on parsing, see recoverFromError. Parse then returns both a tree and an error: the tree of the input as far as the
// parser could make sense of it, with a node for the error symbol at every place it resumed at, and all syntax errors
// it found joined into one error. A tree is only returned if the parse reached its end, otherwise the recovery gave up
// somewhere in the middle and there is no tree to speak of.
//
// The errors are joined even when there is only one of them, so the shape of the returned error does not depend on how
// many errors the parse found. Use errors.Is and errors.As to get at them, both of which look into a join.
func (p *Parser) Parse(scanner ParserScanner) (Node, error) {
	p.scanner = scanner
	p.resetArena()

	// A source with no tokens at all reports false right away. That is not an error: the token is the end of input
	// either way, and whether a parse of nothing but that is legal is for the table to decide.
	p.scanner.Next()

	p.stateStack = p.stateStack[:0]
	p.stateStack = append(p.stateStack, 0)
	p.nodeStack = p.nodeStack[:0]
	p.errors = p.errors[:0]
	p.errorRecoveryShiftsRemaining = 0

	for {
		err := p.step()
		if err == nil {
			continue
		}
		if errors.Is(err, errAccept) {
			// The parse is finished. It still reports the errors it recovered from along the way.
			return p.nodeStack[0], errors.Join(p.errors...)
		}
		if !errors.Is(err, ErrSyntax) {
			// Only an error in the input can be recovered from. Anything else is a defect of the parser itself.
			p.errors = append(p.errors, err)
			return Node{}, errors.Join(p.errors...)
		}
		if p.errorRecoveryShiftsRemaining == 0 {
			// While recovering, the parser is not in sync with the input, so the errors it runs into there are most
			// likely consequences of the error which is already reported. Reporting those as well is the avalanche of
			// messages the countdown exists to prevent.
			p.errors = append(p.errors, err)
		}
		if !p.recoverFromError() {
			return Node{}, errors.Join(p.errors...)
		}
	}
}

// step performs the single action which the state on top of the stack takes for the token the scanner currently
// delivers. This is the whole automaton: everything which distinguishes one state from another is in the tables.
func (p *Parser) step() error {
	terminal := p.scanner.Token()

	// A token which is no terminal of this grammar takes the default action of the state.
	column := p.terminalColumn(terminal)

	state := p.currentState()
	cellIdx := uint32(actionBase[state]) + column
	action := uint32(defaultActionByState[state])
	if uint32(actionCheck[cellIdx]) == column {
		// The state has an entry of its own for this token, which beats its default action. That order is what keeps
		// a token the grammar rejects on purpose an error even in a state which reduces on everything else.
		action = uint32(actionNext[cellIdx])
	}

	switch action & actionKindMask {
	case actionKindShift:
		p.stateStack = append(p.stateStack, int(action>>actionKindBits))
		p.nodeStack = append(p.nodeStack, Node{
			Symbol: NewTerminal(terminal),
			Lexeme: p.scanner.Lexeme(),
		})
		p.scanner.Next()
		if p.errorRecoveryShiftsRemaining > 0 {
			// Getting tokens of the input shifted again is what makes the parser trust its position again.
			p.errorRecoveryShiftsRemaining--
		}
		return nil
	case actionKindReduce:
		p.reduce(action >> actionKindBits)
		return nil
	case actionKindAccept:
		// The parse is successfully finished.
		return errAccept
	case actionKindError:
		return p.raiseError(fmt.Errorf("%w: unexpected token %s", ErrSyntax, terminal))
	default:
		return p.raiseError(fmt.Errorf("%w: unexpected action %d in state %d", ErrInternal, action, state))
	}
}

// reduce replaces the right hand side of the given production on the stacks with the nonterminal on its left hand side,
// and continues in the state the goto of the uncovered state leads to.
func (p *Parser) reduce(productionIdx uint32) {
	popCount := int(popCountByProduction[productionIdx])
	nonterminal := uint32(nonterminalByProduction[productionIdx])

	p.stateStack = p.stateStack[:len(p.stateStack)-popCount]

	state := p.currentState()
	// A state which does not have a goto of its own on the nonterminal goes where most states go with it. The LR
	// construction creates the goto together with the production, so a state which a reduction uncovers always has
	// one, which is why the lookup needs no case for a nonterminal missing from both.
	gotoState := uint32(defaultGotoByNonterminal[nonterminal])
	cellIdx := uint32(gotoBase[state]) + nonterminal
	if uint32(gotoCheck[cellIdx]) == nonterminal {
		gotoState = uint32(gotoNext[cellIdx])
	}
	p.stateStack = append(p.stateStack, int(gotoState))

	newNode := Node{
		Symbol: NewNonterminal(Nonterminal(nonterminal)),
	}
	if popCount != 0 {
		newNode.Children = p.allocateNodes(popCount)
		copy(newNode.Children, p.nodeStack[len(p.nodeStack)-popCount:])
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-popCount]
	}
	p.nodeStack = append(p.nodeStack, newNode)
}

// recoverFromError puts the parser back into a state where it can continue on the remaining input after a syntax error.
// It reports if that succeeded. Once it did not, the parse is given up.
//
// This is the panic mode recovery of section 9 "Error Recovery" of "LR Parsing" by Aho and Johnson, in the shape which
// section 7 "Error Handling" of the yacc report describes: the parser pops its stack until it reaches a state which can
// shift the error symbol - a place the grammar marked as one to resume at - and shifts the symbol there. Everything the
// popped states had parsed is discarded with them.
//
// The token which caused the error is kept for the resumed state to look at, because that state is usually waiting for
// exactly it: in a production like "{" @error "}" it is the closing brace which ends the recovery. Only when the parse
// fails on that very same token again is the token discarded, which is what an untouched countdown of tokens to shift
// tells us. Popping and discarding in the same handler is what guarantees progress: every round of recovery either gets
// the parse going again or consumes one token of the input, so a parse cannot get stuck between the two.
func (p *Parser) recoverFromError() bool {
	if p.errorRecoveryShiftsRemaining == errorRecoveryShifts {
		// Nothing was shifted since the last error, so the parser is failing on the token it already failed on and
		// keeping it would only lead here again.
		if p.scanner.Token() == EndToken {
			// The end of input is the one token which cannot be discarded, so there is nothing left to try.
			return false
		}
		p.scanner.Next()
	}
	p.errorRecoveryShiftsRemaining = errorRecoveryShifts

	for {
		if nextState, ok := p.errorShiftState(p.currentState()); ok {
			// Shift the error symbol. Its node stands for the part of the input which was dropped and has no lexeme.
			p.stateStack = append(p.stateStack, nextState)
			p.nodeStack = append(p.nodeStack, Node{
				Symbol: NewTerminal(ErrorToken),
			})
			return true
		}
		if len(p.stateStack) == 1 {
			// Only the state the parse started in is left and it cannot shift the error symbol either, so no place the
			// grammar marked to resume at covers the position of the error.
			return false
		}
		// The state cannot resume here, so it is dropped together with what it had parsed and the state below it gets
		// to try. The two stacks hold one node per symbol which was shifted or reduced and one state on top of that,
		// so dropping one state drops one node.
		p.stateStack = p.stateStack[:len(p.stateStack)-1]
		p.nodeStack = p.nodeStack[:len(p.nodeStack)-1]
	}
}

// currentState returns the state on top of the stack, which is the one the parse is in.
func (p *Parser) currentState() int {
	return p.stateStack[len(p.stateStack)-1]
}

// terminalColumn returns the column of the action table which holds the decisions for the given token. A token the
// grammar does not have, and one outside the range the scanner promises, both get noTerminalColumn.
func (p *Parser) terminalColumn(terminal Token) uint32 {
	if uint32(terminal) < uint32(len(terminalColumnByToken)) {
		return uint32(terminalColumnByToken[terminal])
	}
	return noTerminalColumn
}

// errorShiftState returns the state to continue in when the error symbol is shifted in the given state, and reports if
// the state can shift the error symbol at all. The states which can are the places the grammar marked to resume at
// after a syntax error, which is what the error recovery pops the stack down to. For a grammar which marks no such
// place there is no such state and no parse can be recovered.
//
// The error symbol is a terminal like any other, so its shift needs no table of its own: it is the entry of the action
// table in the column of the error symbol. Nothing else can read that column, because no scanner ever delivers the
// symbol. The default action of the state is deliberately not consulted, because only an entry the state has of its own
// is a place to resume at.
func (p *Parser) errorShiftState(state int) (int, bool) {
	cellIdx := uint32(actionBase[state]) + errorTerminalColumn
	if uint32(actionCheck[cellIdx]) != errorTerminalColumn {
		return 0, false
	}
	action := uint32(actionNext[cellIdx])
	if action&actionKindMask != actionKindShift {
		return 0, false
	}
	return int(action >> actionKindBits), true
}

// raiseError is a helper function which collects the current location of the parse and wraps the given cause.
func (p *Parser) raiseError(cause error) error {
	return &Error{
		Token:      p.scanner.Token(),
		ByteOffset: p.scanner.ByteOffset(),
		Line:       p.scanner.Line(),
		Column:     p.scanner.Column(),
		Lexeme:     p.scanner.Lexeme(),
		FilePath:   p.scanner.FilePath(),
		Cause:      cause,
	}
}

// allocateNodes provides an arena allocator for slices of Node.
func (p *Parser) allocateNodes(n int) []Node {
	if p.arenaAllocatorTop+n > len(p.arenaAllocator) {
		p.nextArenaChunk(n)
	}
	nodes := p.arenaAllocator[p.arenaAllocatorTop : p.arenaAllocatorTop+n]
	p.arenaAllocatorTop += n
	return nodes
}

// nextArenaChunk moves the arena on to the chunk after the current one, to serve a request of n nodes which the
// current chunk has no room left for. Where an earlier parse left a chunk behind, that chunk is handed out again, so
// a parser settles on the number of chunks its largest parse needed and allocates none after that.
//
// A reused chunk is not cleared. Every slice allocateNodes returns is filled completely by its caller before anything
// reads it, so what an earlier parse left behind in the chunk is never observable.
func (p *Parser) nextArenaChunk(n int) {
	p.arenaChunkIdx++
	if p.arenaChunkIdx == len(p.arenaChunks) {
		p.arenaChunks = append(p.arenaChunks, make([]Node, max(n, arenaChunkSize)))
	} else if len(p.arenaChunks[p.arenaChunkIdx]) < n {
		// A single reduction which takes more nodes than a chunk holds gets a chunk sized to itself, so a chunk kept
		// from an earlier parse is not guaranteed to have room for a later request.
		p.arenaChunks[p.arenaChunkIdx] = make([]Node, n)
	}
	p.arenaAllocator = p.arenaChunks[p.arenaChunkIdx]
	p.arenaAllocatorTop = 0
}

// resetArena puts the arena back to where it starts a parse, handing out from the beginning of the first chunk again.
func (p *Parser) resetArena() {
	p.arenaChunkIdx = 0
	p.arenaAllocator = p.arenaChunks[0]
	p.arenaAllocatorTop = 0
}
