// Code generated by GoLR. DO NOT EDIT.

package parser

import (
	"errors"
	"fmt"
)

// Token is the data type representing all terminal symbols.
type Token int

const (
	// InvalidToken is a terminal which does not exist. It is used for situations where no token was found.
	InvalidToken Token = iota

	// EndToken is a terminal which does not exist. It is used for situations where the end of the source was reached.
	EndToken

	TokenWhitespace
	TokenComment
	TokenScanner
	TokenParser
	TokenPrecedence
	TokenStart
	TokenLeft
	TokenRight
	TokenNone
	TokenSkip
	TokenEmpty
	TokenFragment
	TokenLbrace
	TokenRbrace
	TokenLparen
	TokenRparen
	TokenColon
	TokenSemi
	TokenPipe
	TokenComma
	TokenName
	TokenRegex
	TokenString
)

// Token implements fmt.Stringer.
var _ fmt.Stringer = (*Token)(nil)

// String returns a string representation of the terminal.
func (t Token) String() string {
	switch t {
	case InvalidToken:
		return "invalid token"
	case EndToken:
		return "end token"
	case TokenWhitespace:
		return `WHITESPACE`
	case TokenComment:
		return `COMMENT`
	case TokenScanner:
		return `SCANNER`
	case TokenParser:
		return `PARSER`
	case TokenPrecedence:
		return `PRECEDENCE`
	case TokenStart:
		return `START`
	case TokenLeft:
		return `LEFT`
	case TokenRight:
		return `RIGHT`
	case TokenNone:
		return `NONE`
	case TokenSkip:
		return `SKIP`
	case TokenEmpty:
		return `EMPTY`
	case TokenFragment:
		return `FRAGMENT`
	case TokenLbrace:
		return `LBRACE`
	case TokenRbrace:
		return `RBRACE`
	case TokenLparen:
		return `LPAREN`
	case TokenRparen:
		return `RPAREN`
	case TokenColon:
		return `COLON`
	case TokenSemi:
		return `SEMI`
	case TokenPipe:
		return `PIPE`
	case TokenComma:
		return `COMMA`
	case TokenName:
		return `NAME`
	case TokenRegex:
		return `REGEX`
	case TokenString:
		return `STRING`
	default:
		return "unknown"
	}
}

// TokenSkipper wraps a scanner and skips all tokens which were marked for skipping. This is usually used for skipping
// whitespaces and comments.
type TokenSkipper struct {
	scanner *Scanner
}

// NewTokenSkipper creates a new TokenSkipper by wrapping the given Scanner.
func NewTokenSkipper(scanner *Scanner) *TokenSkipper {
	return &TokenSkipper{
		scanner: scanner,
	}
}

// Reset updates the scanner with the given source and starts scanning at the given offset. This can be useful for
// situations where you only want to re-tokenize parts of the source after the source has been changed.
func (s *TokenSkipper) Reset(source []byte, offset int) {
	s.scanner.Reset(source, offset)
}

// Token returns the current token.
func (s *TokenSkipper) Token() Token {
	return s.scanner.Token()
}

// ByteOffset returns the start of the token in bytes from the source start.
// When Next() returned false, it returns the location after the last byte.
func (s *TokenSkipper) ByteOffset() int {
	return s.scanner.ByteOffset()
}

// Line returns the line the token is located on.
func (s *TokenSkipper) Line() int {
	return s.scanner.Line()
}

// Column returns the column the token is located on.
func (s *TokenSkipper) Column() int {
	return s.scanner.Column()
}

// Lexeme returns the bytes which make up the token.
func (s *TokenSkipper) Lexeme() []byte {
	return s.scanner.Lexeme()
}

// FilePath returns the file path of the file being parsed. This information can be useful in error messages.
func (s *TokenSkipper) FilePath() string {
	return s.scanner.FilePath()
}

// Next consumes tokens until it found a token which should not be skipped.
func (s *TokenSkipper) Next() bool {
	for {
		if !s.scanner.Next() {
			return false
		}
		switch s.scanner.Token() {
		case TokenWhitespace:
			continue
		case TokenComment:
			continue
		default:
			return true
		}
	}
}

// Scanner reads source code and returns tokens.
type Scanner struct {
	source []byte

	lexemeStartIdx int
	lexemeEndIdx   int
	lexemePeekIdx  int

	line   int
	column int

	state int
	token Token

	filePath string
}

// NewScanner creates a new instance of the scanner with the given source. The filePath parameter is used to
// return information about which file has an error. You can provide any string you want if you don't have a file.
func NewScanner(source []byte, filePath string) *Scanner {
	scanner := Scanner{
		filePath: filePath,
	}
	scanner.Reset(source, 0)
	return &scanner
}

// Reset updates the scanner with the given source and starts scanning at the given offset. This can be useful for
// situations where you only want to re-tokenize parts of the source after the source has been changed.
func (s *Scanner) Reset(source []byte, offset int) {
	s.source = source

	s.lexemeStartIdx = 0
	s.lexemeEndIdx = offset

	s.line = 1
	s.column = 1

	s.token = InvalidToken
}

// Token returns the current token.
func (s *Scanner) Token() Token {
	return s.token
}

// ByteOffset returns the start of the token in bytes from the source start.
// When Next() returned false, it returns the location after the last byte.
func (s *Scanner) ByteOffset() int {
	return s.lexemeStartIdx
}

// Line returns the line the token is located on.
func (s *Scanner) Line() int {
	return s.line
}

// Column returns the column the token is located on.
func (s *Scanner) Column() int {
	return s.column
}

// Lexeme returns the bytes which make up the token.
func (s *Scanner) Lexeme() []byte {
	return s.source[s.lexemeStartIdx:s.lexemeEndIdx]
}

// FilePath returns the file path of the file being parsed. This information can be useful in error messages.
func (s *Scanner) FilePath() string {
	return s.filePath
}

// Next consumes characters until it found the next token.
func (s *Scanner) Next() bool {
	s.updateLineAndColumn(s.source[s.lexemeStartIdx:s.lexemeEndIdx])
	s.lexemeStartIdx = s.lexemeEndIdx
	s.state = 0

	for s.lexemePeekIdx = s.lexemeEndIdx; s.lexemePeekIdx < len(s.source); s.lexemePeekIdx++ {
		if err := s.dispatchState(); err != nil {
			break
		}
	}
	if s.lexemePeekIdx == len(s.source) {
		// We need to capture the last character of the source.
		s.dispatchEOF()
	}

	if s.lexemeStartIdx < s.lexemeEndIdx {
		// We found a token.
		return true
	}

	if len(s.source) <= s.lexemeStartIdx {
		// We have reached the end of the source.
		s.token = EndToken
		return false
	}

	// We found some characters which do not form a token. We need to emit an invalid token for them.
	s.token = InvalidToken
	s.lexemeEndIdx = s.lexemePeekIdx + 1
	return true
}

// updateLineAndColumn updates the current line and column information by scanning the given source for newlines.
func (s *Scanner) updateLineAndColumn(source []byte) {
	for _, currByte := range source {
		if currByte == '\n' {
			s.line++
			s.column = 1
		} else {
			s.column++
		}
	}
}

// dispatchState calls the code corresponding to the current scanner state.
func (s *Scanner) dispatchState() error {
	switch s.state {
	case 0:
		return s.state0Whitespace()
	case 1:
		return s.state1Whitespace()
	case 2:
		return s.state2Whitespace()
	case 3:
		return s.state3Comment()
	case 4:
		return s.state4Scanner()
	case 5:
		return s.state5Lbrace()
	case 6:
		return s.state6Rbrace()
	case 7:
		return s.state7Lparen()
	case 8:
		return s.state8Rparen()
	case 9:
		return s.state9Colon()
	case 10:
		return s.state10Semi()
	case 11:
		return s.state11Pipe()
	case 12:
		return s.state12Comma()
	case 13:
		return s.state13Name()
	case 14:
		return s.state14String()
	case 15:
		return s.state15Comment()
	case 16:
		return s.state16Comment()
	case 17:
		return s.state17Regex()
	case 18:
		return s.state18Regex()
	case 19:
		return s.state19Regex()
	case 20:
		return s.state20Regex()
	case 21:
		return s.state21Regex()
	case 22:
		return s.state22Regex()
	case 23:
		return s.state23Regex()
	case 24:
		return s.state24Regex()
	case 25:
		return s.state25Scanner()
	case 26:
		return s.state26Parser()
	case 27:
		return s.state27Left()
	case 28:
		return s.state28Right()
	case 29:
		return s.state29None()
	case 30:
		return s.state30Empty()
	case 31:
		return s.state31Fragment()
	case 32:
		return s.state32String()
	case 33:
		return s.state33String()
	case 34:
		return s.state34String()
	case 35:
		return s.state35String()
	case 36:
		return s.state36String()
	case 37:
		return s.state37String()
	case 38:
		return s.state38String()
	case 39:
		return s.state39String()
	case 40:
		return s.state40Regex()
	case 41:
		return s.state41Comment()
	case 42:
		return s.state42Comment()
	case 43:
		return s.state43Comment()
	case 44:
		return s.state44Comment()
	case 45:
		return s.state45Comment()
	case 46:
		return s.state46Comment()
	case 47:
		return s.state47Comment()
	case 48:
		return s.state48Comment()
	case 49:
		return s.state49Comment()
	case 50:
		return s.state50Comment()
	case 51:
		return s.state51Comment()
	case 52:
		return s.state52Regex()
	case 53:
		return s.state53Regex()
	case 54:
		return s.state54Scanner()
	case 55:
		return s.state55Start()
	case 56:
		return s.state56Skip()
	case 57:
		return s.state57Parser()
	case 58:
		return s.state58Precedence()
	case 59:
		return s.state59Left()
	case 60:
		return s.state60Right()
	case 61:
		return s.state61None()
	case 62:
		return s.state62Empty()
	case 63:
		return s.state63Fragment()
	case 64:
		return s.state64String()
	case 65:
		return s.state65Comment()
	case 66:
		return s.state66Comment()
	case 67:
		return s.state67Comment()
	case 68:
		return s.state68Comment()
	case 69:
		return s.state69Comment()
	case 70:
		return s.state70Comment()
	case 71:
		return s.state71Comment()
	case 72:
		return s.state72Comment()
	case 73:
		return s.state73Regex()
	case 74:
		return s.state74Comment()
	case 75:
		return s.state75Scanner()
	case 76:
		return s.state76Start()
	case 77:
		return s.state77Skip()
	case 78:
		return s.state78Parser()
	case 79:
		return s.state79Precedence()
	case 80:
		return s.state80Left()
	case 81:
		return s.state81Right()
	case 82:
		return s.state82None()
	case 83:
		return s.state83Empty()
	case 84:
		return s.state84Fragment()
	case 85:
		return s.state85Scanner()
	case 86:
		return s.state86Start()
	case 87:
		return s.state87Skip()
	case 88:
		return s.state88Parser()
	case 89:
		return s.state89Precedence()
	case 90:
		return s.state90Left()
	case 91:
		return s.state91Right()
	case 92:
		return s.state92None()
	case 93:
		return s.state93Empty()
	case 94:
		return s.state94Fragment()
	case 95:
		return s.state95Scanner()
	case 96:
		return s.state96Start()
	case 97:
		return s.state97Parser()
	case 98:
		return s.state98Precedence()
	case 99:
		return s.state99Right()
	case 100:
		return s.state100Empty()
	case 101:
		return s.state101Fragment()
	case 102:
		return s.state102Scanner()
	case 103:
		return s.state103Parser()
	case 104:
		return s.state104Precedence()
	case 105:
		return s.state105Fragment()
	case 106:
		return s.state106Scanner()
	case 107:
		return s.state107Precedence()
	case 108:
		return s.state108Fragment()
	case 109:
		return s.state109Precedence()
	case 110:
		return s.state110Fragment()
	case 111:
		return s.state111Precedence()
	case 112:
		return s.state112Precedence()
	default:
		return fmt.Errorf("unexpected scanner state %d", s.state)
	}
}

func (s *Scanner) dispatchEOF() {
	switch s.state {
	case 1:
		s.token = TokenWhitespace
		s.lexemeEndIdx = s.lexemePeekIdx
	case 5:
		s.token = TokenLbrace
		s.lexemeEndIdx = s.lexemePeekIdx
	case 6:
		s.token = TokenRbrace
		s.lexemeEndIdx = s.lexemePeekIdx
	case 7:
		s.token = TokenLparen
		s.lexemeEndIdx = s.lexemePeekIdx
	case 8:
		s.token = TokenRparen
		s.lexemeEndIdx = s.lexemePeekIdx
	case 9:
		s.token = TokenColon
		s.lexemeEndIdx = s.lexemePeekIdx
	case 10:
		s.token = TokenSemi
		s.lexemeEndIdx = s.lexemePeekIdx
	case 11:
		s.token = TokenPipe
		s.lexemeEndIdx = s.lexemePeekIdx
	case 12:
		s.token = TokenComma
		s.lexemeEndIdx = s.lexemePeekIdx
	case 13:
		s.token = TokenName
		s.lexemeEndIdx = s.lexemePeekIdx
	case 16:
		s.token = TokenComment
		s.lexemeEndIdx = s.lexemePeekIdx
	case 39:
		s.token = TokenString
		s.lexemeEndIdx = s.lexemePeekIdx
	case 40:
		s.token = TokenRegex
		s.lexemeEndIdx = s.lexemePeekIdx
	case 52:
		s.token = TokenRegex
		s.lexemeEndIdx = s.lexemePeekIdx
	case 53:
		s.token = TokenRegex
		s.lexemeEndIdx = s.lexemePeekIdx
	case 64:
		s.token = TokenString
		s.lexemeEndIdx = s.lexemePeekIdx
	case 73:
		s.token = TokenRegex
		s.lexemeEndIdx = s.lexemePeekIdx
	case 74:
		s.token = TokenComment
		s.lexemeEndIdx = s.lexemePeekIdx
	case 87:
		s.token = TokenSkip
		s.lexemeEndIdx = s.lexemePeekIdx
	case 90:
		s.token = TokenLeft
		s.lexemeEndIdx = s.lexemePeekIdx
	case 92:
		s.token = TokenNone
		s.lexemeEndIdx = s.lexemePeekIdx
	case 96:
		s.token = TokenStart
		s.lexemeEndIdx = s.lexemePeekIdx
	case 99:
		s.token = TokenRight
		s.lexemeEndIdx = s.lexemePeekIdx
	case 100:
		s.token = TokenEmpty
		s.lexemeEndIdx = s.lexemePeekIdx
	case 103:
		s.token = TokenParser
		s.lexemeEndIdx = s.lexemePeekIdx
	case 106:
		s.token = TokenScanner
		s.lexemeEndIdx = s.lexemePeekIdx
	case 110:
		s.token = TokenFragment
		s.lexemeEndIdx = s.lexemePeekIdx
	case 112:
		s.token = TokenPrecedence
		s.lexemeEndIdx = s.lexemePeekIdx
	}
}

var (
	// errInvalidByte is an error which is returned when no transition matches the current byte.
	errInvalidByte = errors.New("invalid byte")
)

func (s *Scanner) state0Whitespace() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == '\t':
		s.state = 1
	case nextByte == '\n':
		s.state = 1
	case nextByte == 0xb:
		s.state = 1
	case nextByte == 0xc:
		s.state = 1
	case nextByte == '\r':
		s.state = 2
	case nextByte == ' ':
		s.state = 1
	case nextByte == '"':
		s.state = 14
	case nextByte == '(':
		s.state = 7
	case nextByte == ')':
		s.state = 8
	case nextByte == ',':
		s.state = 12
	case nextByte == '/':
		s.state = 3
	case nextByte == ':':
		s.state = 9
	case nextByte == ';':
		s.state = 10
	case nextByte == '@':
		s.state = 4
	case 'A' <= nextByte && nextByte <= 'Z':
		s.state = 13
	case nextByte == '_':
		s.state = 13
	case 'a' <= nextByte && nextByte <= 'z':
		s.state = 13
	case nextByte == '{':
		s.state = 5
	case nextByte == '|':
		s.state = 11
	case nextByte == '}':
		s.state = 6
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state1Whitespace() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenWhitespace
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == '\t':
		s.state = 1
	case nextByte == '\n':
		s.state = 1
	case nextByte == 0xb:
		s.state = 1
	case nextByte == 0xc:
		s.state = 1
	case nextByte == '\r':
		s.state = 2
	case nextByte == ' ':
		s.state = 1
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state2Whitespace() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == '\n':
		s.state = 1
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state3Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 17
	case nextByte == '*':
		s.state = 15
	case '+' <= nextByte && nextByte <= '.':
		s.state = 17
	case nextByte == '/':
		s.state = 16
	case '0' <= nextByte && nextByte <= '[':
		s.state = 17
	case nextByte == '\\':
		s.state = 18
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 17
	case nextByte == 0xc2:
		s.state = 19
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 19
	case nextByte == 0xdf:
		s.state = 19
	case nextByte == 0xe0:
		s.state = 20
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 21
	case nextByte == 0xef:
		s.state = 21
	case nextByte == 0xf0:
		s.state = 22
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 23
	case nextByte == 0xf4:
		s.state = 24
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state4Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 30
	case nextByte == 'f':
		s.state = 31
	case nextByte == 'l':
		s.state = 27
	case nextByte == 'n':
		s.state = 29
	case nextByte == 'p':
		s.state = 26
	case nextByte == 'r':
		s.state = 28
	case nextByte == 's':
		s.state = 25
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state5Lbrace() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenLbrace
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state6Rbrace() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRbrace
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state7Lparen() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenLparen
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state8Rparen() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRparen
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state9Colon() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenColon
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state10Semi() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenSemi
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state11Pipe() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenPipe
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state12Comma() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenComma
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state13Name() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenName
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case '0' <= nextByte && nextByte <= '9':
		s.state = 13
	case 'A' <= nextByte && nextByte <= 'Z':
		s.state = 13
	case nextByte == '_':
		s.state = 13
	case 'a' <= nextByte && nextByte <= 'z':
		s.state = 13
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state14String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '!':
		s.state = 14
	case nextByte == '"':
		s.state = 39
	case '#' <= nextByte && nextByte <= '[':
		s.state = 14
	case nextByte == '\\':
		s.state = 32
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 14
	case nextByte == 0xc2:
		s.state = 33
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 33
	case nextByte == 0xdf:
		s.state = 33
	case nextByte == 0xe0:
		s.state = 34
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 35
	case nextByte == 0xef:
		s.state = 35
	case nextByte == 0xf0:
		s.state = 36
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 37
	case nextByte == 0xf4:
		s.state = 38
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state15Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 15
	case nextByte == '*':
		s.state = 48
	case '+' <= nextByte && nextByte <= '.':
		s.state = 15
	case nextByte == '/':
		s.state = 40
	case '0' <= nextByte && nextByte <= '[':
		s.state = 15
	case nextByte == '\\':
		s.state = 41
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 15
	case nextByte == 0xc2:
		s.state = 42
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 42
	case nextByte == 0xdf:
		s.state = 42
	case nextByte == 0xe0:
		s.state = 43
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 44
	case nextByte == 0xef:
		s.state = 44
	case nextByte == 0xf0:
		s.state = 45
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 46
	case nextByte == 0xf4:
		s.state = 47
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state16Comment() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenComment
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '\t':
		s.state = 16
	case 0xb <= nextByte && nextByte <= 0x7f:
		s.state = 16
	case 0xc2 <= nextByte && nextByte <= 0xdf:
		s.state = 49
	case 0xe0 <= nextByte && nextByte <= 0xef:
		s.state = 50
	case 0xf0 <= nextByte && nextByte <= 0xf4:
		s.state = 51
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state17Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '.':
		s.state = 17
	case nextByte == '/':
		s.state = 52
	case '0' <= nextByte && nextByte <= '[':
		s.state = 17
	case nextByte == '\\':
		s.state = 18
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 17
	case nextByte == 0xc2:
		s.state = 19
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 19
	case nextByte == 0xdf:
		s.state = 19
	case nextByte == 0xe0:
		s.state = 20
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 21
	case nextByte == 0xef:
		s.state = 21
	case nextByte == 0xf0:
		s.state = 22
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 23
	case nextByte == 0xf4:
		s.state = 24
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state18Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '.':
		s.state = 17
	case nextByte == '/':
		s.state = 53
	case '0' <= nextByte && nextByte <= '[':
		s.state = 17
	case nextByte == '\\':
		s.state = 18
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 17
	case nextByte == 0xc2:
		s.state = 19
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 19
	case nextByte == 0xdf:
		s.state = 19
	case nextByte == 0xe0:
		s.state = 20
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 21
	case nextByte == 0xef:
		s.state = 21
	case nextByte == 0xf0:
		s.state = 22
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 23
	case nextByte == 0xf4:
		s.state = 24
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state19Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 17
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state20Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0xa0:
		s.state = 19
	case 0xa1 <= nextByte && nextByte <= 0xbe:
		s.state = 19
	case nextByte == 0xbf:
		s.state = 19
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state21Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 19
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 19
	case nextByte == 0xbf:
		s.state = 19
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state22Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x90:
		s.state = 21
	case 0x91 <= nextByte && nextByte <= 0xbe:
		s.state = 21
	case nextByte == 0xbf:
		s.state = 21
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state23Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 21
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 21
	case nextByte == 0xbf:
		s.state = 21
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state24Regex() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 21
	case 0x81 <= nextByte && nextByte <= 0x8e:
		s.state = 21
	case nextByte == 0x8f:
		s.state = 21
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state25Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'c':
		s.state = 54
	case nextByte == 'k':
		s.state = 56
	case nextByte == 't':
		s.state = 55
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state26Parser() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'a':
		s.state = 57
	case nextByte == 'r':
		s.state = 58
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state27Left() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 59
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state28Right() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'i':
		s.state = 60
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state29None() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'o':
		s.state = 61
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state30Empty() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'm':
		s.state = 62
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state31Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'r':
		s.state = 63
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state32String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '!':
		s.state = 14
	case nextByte == '"':
		s.state = 64
	case '#' <= nextByte && nextByte <= '[':
		s.state = 14
	case nextByte == '\\':
		s.state = 32
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 14
	case nextByte == 0xc2:
		s.state = 33
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 33
	case nextByte == 0xdf:
		s.state = 33
	case nextByte == 0xe0:
		s.state = 34
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 35
	case nextByte == 0xef:
		s.state = 35
	case nextByte == 0xf0:
		s.state = 36
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 37
	case nextByte == 0xf4:
		s.state = 38
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state33String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 14
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state34String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0xa0:
		s.state = 33
	case 0xa1 <= nextByte && nextByte <= 0xbe:
		s.state = 33
	case nextByte == 0xbf:
		s.state = 33
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state35String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 33
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 33
	case nextByte == 0xbf:
		s.state = 33
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state36String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x90:
		s.state = 35
	case 0x91 <= nextByte && nextByte <= 0xbe:
		s.state = 35
	case nextByte == 0xbf:
		s.state = 35
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state37String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 35
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 35
	case nextByte == 0xbf:
		s.state = 35
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state38String() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 35
	case 0x81 <= nextByte && nextByte <= 0x8e:
		s.state = 35
	case nextByte == 0x8f:
		s.state = 35
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state39String() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenString
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state40Regex() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRegex
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 65
	case nextByte == '*':
		s.state = 72
	case '+' <= nextByte && nextByte <= 0x7f:
		s.state = 65
	case nextByte == 0xc2:
		s.state = 66
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 66
	case nextByte == 0xdf:
		s.state = 66
	case nextByte == 0xe0:
		s.state = 67
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 68
	case nextByte == 0xef:
		s.state = 68
	case nextByte == 0xf0:
		s.state = 69
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 70
	case nextByte == 0xf4:
		s.state = 71
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state41Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 15
	case nextByte == '*':
		s.state = 48
	case '+' <= nextByte && nextByte <= '.':
		s.state = 15
	case nextByte == '/':
		s.state = 73
	case '0' <= nextByte && nextByte <= '[':
		s.state = 15
	case nextByte == '\\':
		s.state = 41
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 15
	case nextByte == 0xc2:
		s.state = 42
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 42
	case nextByte == 0xdf:
		s.state = 42
	case nextByte == 0xe0:
		s.state = 43
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 44
	case nextByte == 0xef:
		s.state = 44
	case nextByte == 0xf0:
		s.state = 45
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 46
	case nextByte == 0xf4:
		s.state = 47
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state42Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 15
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state43Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0xa0:
		s.state = 42
	case 0xa1 <= nextByte && nextByte <= 0xbe:
		s.state = 42
	case nextByte == 0xbf:
		s.state = 42
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state44Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 42
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 42
	case nextByte == 0xbf:
		s.state = 42
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state45Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x90:
		s.state = 44
	case 0x91 <= nextByte && nextByte <= 0xbe:
		s.state = 44
	case nextByte == 0xbf:
		s.state = 44
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state46Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 44
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 44
	case nextByte == 0xbf:
		s.state = 44
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state47Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 44
	case 0x81 <= nextByte && nextByte <= 0x8e:
		s.state = 44
	case nextByte == 0x8f:
		s.state = 44
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state48Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 15
	case nextByte == '*':
		s.state = 48
	case '+' <= nextByte && nextByte <= '.':
		s.state = 15
	case nextByte == '/':
		s.state = 74
	case '0' <= nextByte && nextByte <= '[':
		s.state = 15
	case nextByte == '\\':
		s.state = 41
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 15
	case nextByte == 0xc2:
		s.state = 42
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 42
	case nextByte == 0xdf:
		s.state = 42
	case nextByte == 0xe0:
		s.state = 43
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 44
	case nextByte == 0xef:
		s.state = 44
	case nextByte == 0xf0:
		s.state = 45
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 46
	case nextByte == 0xf4:
		s.state = 47
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state49Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 16
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state50Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 49
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state51Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 50
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state52Regex() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRegex
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state53Regex() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRegex
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '.':
		s.state = 17
	case nextByte == '/':
		s.state = 52
	case '0' <= nextByte && nextByte <= '[':
		s.state = 17
	case nextByte == '\\':
		s.state = 18
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 17
	case nextByte == 0xc2:
		s.state = 19
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 19
	case nextByte == 0xdf:
		s.state = 19
	case nextByte == 0xe0:
		s.state = 20
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 21
	case nextByte == 0xef:
		s.state = 21
	case nextByte == 0xf0:
		s.state = 22
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 23
	case nextByte == 0xf4:
		s.state = 24
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state54Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'a':
		s.state = 75
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state55Start() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'a':
		s.state = 76
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state56Skip() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'i':
		s.state = 77
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state57Parser() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'r':
		s.state = 78
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state58Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 79
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state59Left() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'f':
		s.state = 80
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state60Right() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'g':
		s.state = 81
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state61None() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'n':
		s.state = 82
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state62Empty() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'p':
		s.state = 83
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state63Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'a':
		s.state = 84
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state64String() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenString
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= '!':
		s.state = 14
	case nextByte == '"':
		s.state = 39
	case '#' <= nextByte && nextByte <= '[':
		s.state = 14
	case nextByte == '\\':
		s.state = 32
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 14
	case nextByte == 0xc2:
		s.state = 33
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 33
	case nextByte == 0xdf:
		s.state = 33
	case nextByte == 0xe0:
		s.state = 34
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 35
	case nextByte == 0xef:
		s.state = 35
	case nextByte == 0xf0:
		s.state = 36
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 37
	case nextByte == 0xf4:
		s.state = 38
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state65Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 65
	case nextByte == '*':
		s.state = 72
	case '+' <= nextByte && nextByte <= 0x7f:
		s.state = 65
	case nextByte == 0xc2:
		s.state = 66
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 66
	case nextByte == 0xdf:
		s.state = 66
	case nextByte == 0xe0:
		s.state = 67
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 68
	case nextByte == 0xef:
		s.state = 68
	case nextByte == 0xf0:
		s.state = 69
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 70
	case nextByte == 0xf4:
		s.state = 71
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state66Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x80 <= nextByte && nextByte <= 0xbf:
		s.state = 65
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state67Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0xa0:
		s.state = 66
	case 0xa1 <= nextByte && nextByte <= 0xbe:
		s.state = 66
	case nextByte == 0xbf:
		s.state = 66
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state68Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 66
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 66
	case nextByte == 0xbf:
		s.state = 66
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state69Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x90:
		s.state = 68
	case 0x91 <= nextByte && nextByte <= 0xbe:
		s.state = 68
	case nextByte == 0xbf:
		s.state = 68
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state70Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 68
	case 0x81 <= nextByte && nextByte <= 0xbe:
		s.state = 68
	case nextByte == 0xbf:
		s.state = 68
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state71Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 0x80:
		s.state = 68
	case 0x81 <= nextByte && nextByte <= 0x8e:
		s.state = 68
	case nextByte == 0x8f:
		s.state = 68
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state72Comment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 65
	case nextByte == '*':
		s.state = 72
	case '+' <= nextByte && nextByte <= '.':
		s.state = 65
	case nextByte == '/':
		s.state = 74
	case '0' <= nextByte && nextByte <= 0x7f:
		s.state = 65
	case nextByte == 0xc2:
		s.state = 66
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 66
	case nextByte == 0xdf:
		s.state = 66
	case nextByte == 0xe0:
		s.state = 67
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 68
	case nextByte == 0xef:
		s.state = 68
	case nextByte == 0xf0:
		s.state = 69
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 70
	case nextByte == 0xf4:
		s.state = 71
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state73Regex() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRegex
	s.lexemeEndIdx = s.lexemePeekIdx

	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case 0x0 <= nextByte && nextByte <= ')':
		s.state = 15
	case nextByte == '*':
		s.state = 48
	case '+' <= nextByte && nextByte <= '.':
		s.state = 15
	case nextByte == '/':
		s.state = 40
	case '0' <= nextByte && nextByte <= '[':
		s.state = 15
	case nextByte == '\\':
		s.state = 41
	case ']' <= nextByte && nextByte <= 0x7f:
		s.state = 15
	case nextByte == 0xc2:
		s.state = 42
	case 0xc3 <= nextByte && nextByte <= 0xde:
		s.state = 42
	case nextByte == 0xdf:
		s.state = 42
	case nextByte == 0xe0:
		s.state = 43
	case 0xe1 <= nextByte && nextByte <= 0xee:
		s.state = 44
	case nextByte == 0xef:
		s.state = 44
	case nextByte == 0xf0:
		s.state = 45
	case 0xf1 <= nextByte && nextByte <= 0xf3:
		s.state = 46
	case nextByte == 0xf4:
		s.state = 47
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state74Comment() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenComment
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state75Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'n':
		s.state = 85
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state76Start() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'r':
		s.state = 86
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state77Skip() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'p':
		s.state = 87
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state78Parser() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 's':
		s.state = 88
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state79Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'c':
		s.state = 89
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state80Left() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 't':
		s.state = 90
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state81Right() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'h':
		s.state = 91
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state82None() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 92
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state83Empty() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 't':
		s.state = 93
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state84Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'g':
		s.state = 94
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state85Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'n':
		s.state = 95
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state86Start() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 't':
		s.state = 96
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state87Skip() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenSkip
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state88Parser() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 97
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state89Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 98
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state90Left() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenLeft
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state91Right() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 't':
		s.state = 99
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state92None() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenNone
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state93Empty() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'y':
		s.state = 100
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state94Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'm':
		s.state = 101
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state95Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 102
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state96Start() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenStart
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state97Parser() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'r':
		s.state = 103
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state98Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'd':
		s.state = 104
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state99Right() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenRight
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state100Empty() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenEmpty
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state101Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 105
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state102Scanner() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'r':
		s.state = 106
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state103Parser() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenParser
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state104Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 107
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state105Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'n':
		s.state = 108
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state106Scanner() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenScanner
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state107Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'n':
		s.state = 109
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state108Fragment() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 't':
		s.state = 110
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state109Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'c':
		s.state = 111
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state110Fragment() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenFragment
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}

func (s *Scanner) state111Precedence() error {
	nextByte := s.source[s.lexemePeekIdx]
	switch {
	case nextByte == 'e':
		s.state = 112
	default:
		return errInvalidByte
	}
	return nil
}

func (s *Scanner) state112Precedence() error {
	// We have an accepting state, update our bookkeeping.
	s.token = TokenPrecedence
	s.lexemeEndIdx = s.lexemePeekIdx

	return errInvalidByte
}
