// Code generated by GoLR. DO NOT EDIT.
//
// This file is output of GoLR. It is exempt from the conditions of GoLR's
// Apache-2.0 license and may be licensed under terms of your choosing.
// See https://github.com/backbone81/golr/blob/main/LICENSE.OUTPUT

package parser

import (
	"fmt"
)

// Token is every terminal symbol this scanner knows.
type Token int

const (
	// InvalidToken means no token was found.
	InvalidToken Token = iota

	// EndToken means the end of the source was reached.
	EndToken

	// ErrorToken is the symbol a grammar marks its error recovery points with. No input ever produces it.
	ErrorToken

	TokenWhitespace
	TokenComment
	TokenScanner
	TokenParser
	TokenPrecedence
	TokenName
	TokenStart
	TokenLeft
	TokenRight
	TokenNone
	TokenSkip
	TokenEmpty
	TokenError
	TokenFragment
	TokenLbrace
	TokenRbrace
	TokenLparen
	TokenRparen
	TokenColon
	TokenSemi
	TokenPipe
	TokenComma
	TokenIdentifier
	TokenRegex
	TokenString
)

// Token implements fmt.Stringer.
var _ fmt.Stringer = (*Token)(nil)

// String returns the name of the token, as the grammar spells it.
func (t Token) String() string {
	switch t {
	case InvalidToken:
		return "invalid token"
	case EndToken:
		return "end token"
	case ErrorToken:
		return "error token"
	case TokenWhitespace:
		return `WHITESPACE`
	case TokenComment:
		return `COMMENT`
	case TokenScanner:
		return `SCANNER`
	case TokenParser:
		return `PARSER`
	case TokenPrecedence:
		return `PRECEDENCE`
	case TokenName:
		return `NAME`
	case TokenStart:
		return `START`
	case TokenLeft:
		return `LEFT`
	case TokenRight:
		return `RIGHT`
	case TokenNone:
		return `NONE`
	case TokenSkip:
		return `SKIP`
	case TokenEmpty:
		return `EMPTY`
	case TokenError:
		return `ERROR`
	case TokenFragment:
		return `FRAGMENT`
	case TokenLbrace:
		return `LBRACE`
	case TokenRbrace:
		return `RBRACE`
	case TokenLparen:
		return `LPAREN`
	case TokenRparen:
		return `RPAREN`
	case TokenColon:
		return `COLON`
	case TokenSemi:
		return `SEMI`
	case TokenPipe:
		return `PIPE`
	case TokenComma:
		return `COMMA`
	case TokenIdentifier:
		return `IDENTIFIER`
	case TokenRegex:
		return `REGEX`
	case TokenString:
		return `STRING`
	default:
		return "unknown"
	}
}

// IsSkipped reports whether the grammar marked the token for skipping, which is what the token skipper drops.
func (t Token) IsSkipped() bool {
	switch t {
	case TokenWhitespace:
		return true
	case TokenComment:
		return true
	default:
		return false
	}
}

// TokenSource is what a scanner offers. Both Scanner and TokenSkipper implement it.
type TokenSource interface {
	// Token returns the current token.
	Token() Token

	// ByteOffset returns the start of the token in bytes from the start of the source. After Next returned false it
	// is the offset one past the last byte.
	ByteOffset() int

	// Line returns the line the token starts on, counted from one.
	Line() int

	// Column returns the column the token starts on, counted from one.
	Column() int

	// Lexeme returns the bytes of the token, as a view into the source rather than a copy of it.
	Lexeme() []byte

	// FilePath returns the file path the scanner was given.
	FilePath() string

	// Reset scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
	// changed.
	Reset(source []byte, offset int)

	// Next advances to the next token. Returns false when the source holds no such token any more.
	Next() bool
}

// TokenSkipper wraps a scanner and skips the tokens marked for skipping, which are usually whitespace and comments. It
// offers the same members as Scanner.
type TokenSkipper struct {
	// scanner is the wrapped scanner.
	scanner TokenSource
}

// NewTokenSkipper creates a skipper which hands on the tokens of the given scanner.
func NewTokenSkipper(scanner TokenSource) *TokenSkipper {
	return &TokenSkipper{
		scanner: scanner,
	}
}

// Token returns the current token.
func (s *TokenSkipper) Token() Token {
	return s.scanner.Token()
}

// ByteOffset returns the start of the token in bytes from the start of the source. After Next returned false it is the
// offset one past the last byte.
func (s *TokenSkipper) ByteOffset() int {
	return s.scanner.ByteOffset()
}

// Line returns the line the token starts on, counted from one.
func (s *TokenSkipper) Line() int {
	return s.scanner.Line()
}

// Column returns the column the token starts on, counted from one.
func (s *TokenSkipper) Column() int {
	return s.scanner.Column()
}

// Lexeme returns the bytes of the token, as a view into the source rather than a copy of it.
func (s *TokenSkipper) Lexeme() []byte {
	return s.scanner.Lexeme()
}

// FilePath returns the file path the scanner was given.
func (s *TokenSkipper) FilePath() string {
	return s.scanner.FilePath()
}

// Reset scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
// changed.
func (s *TokenSkipper) Reset(source []byte, offset int) {
	s.scanner.Reset(source, offset)
}

// Next advances to the next token which is not marked for skipping. Returns false when the source holds no such token
// any more.
func (s *TokenSkipper) Next() bool {
	for s.scanner.Next() {
		if !s.scanner.Token().IsSkipped() {
			return true
		}
	}
	return false
}

// The automaton is held in lookup tables. An input byte is mapped to its byte class, which is the column of the
// transition table, and the rows of that table are displaced into a single array so that the entries of one row fall
// into the holes of another. This is the row displacement method of "Storing a Sparse Table" by Tarjan and Yao.
//
// The displaced arrays are padded so that every state and byte class lands inside them, which is why a lookup needs no
// range check of its own.
var (
	// byteClassByByte maps an input byte to its byte class. Bytes which every state treats alike share a class.
	byteClassByByte = [256]uint8{
		0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 3, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		1, 0, 4, 0, 0, 0, 0, 0, 5, 6, 7, 0, 8, 0, 0, 9,
		10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 0, 0, 0, 0,
		13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
		14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 15, 0, 0, 14,
		0, 16, 14, 17, 18, 19, 20, 21, 22, 23, 14, 24, 25, 26, 27, 28,
		29, 14, 30, 31, 32, 14, 14, 14, 14, 33, 14, 34, 35, 36, 0, 0,
		37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
		38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
		39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
		39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
		40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
		41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
		42, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
		44, 45, 45, 45, 46, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
	}

	// transitionBase maps a state to the displacement of its row within transitionNext.
	transitionBase = [120]uint16{
		516, 36, 38, 235, 558, 1, 1, 1, 1, 1, 1, 1, 1, 543, 282, 0,
		329, 376, 423, 48, 45, 95, 542, 142, 247, 562, 577, 209, 112, 155, 569, 242,
		470, 189, 280, 236, 570, 283, 294, 1, 47, 47, 94, 330, 327, 377, 572, 424,
		341, 141, 471, 517, 553, 1, 376, 397, 409, 437, 442, 488, 497, 499, 511, 537,
		555, 552, 590, 282, 559, 575, 563, 574, 566, 578, 188, 0, 1, 589, 587, 591,
		588, 601, 602, 603, 592, 604, 593, 595, 606, 605, 596, 1, 610, 611, 1, 1,
		1, 599, 600, 607, 608, 616, 1, 609, 618, 1, 1, 1, 619, 612, 1, 621,
		614, 1, 617, 613, 626, 1, 627, 1,
	}

	// transitionNext holds the target state of every transition. The transition a state has on a byte class lives at
	// transitionBase[state] + class, but only if transitionCheck confirms the cell belongs to that class.
	transitionNext = [674]uint8{
		15, 15, 40, 15, 15, 15, 15, 49, 15, 41, 15, 15, 15, 15, 15, 42,
		15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
		15, 15, 15, 15, 15, 1, 1, 2, 1, 43, 44, 45, 46, 47, 48, 40,
		40, 40, 40, 40, 40, 40, 74, 40, 40, 40, 40, 40, 40, 40, 40, 40,
		40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
		40, 40, 40, 40, 19, 17, 17, 17, 68, 69, 70, 71, 72, 73, 15, 15,
		40, 15, 15, 15, 15, 49, 15, 75, 15, 15, 15, 15, 15, 42, 15, 15,
		15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
		15, 15, 15, 62, 19, 19, 19, 43, 44, 45, 46, 47, 48, 15, 15, 40,
		15, 15, 15, 15, 49, 15, 76, 15, 15, 15, 15, 15, 42, 15, 15, 15,
		15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
		15, 15, 63, 21, 21, 21, 43, 44, 45, 46, 47, 48, 40, 40, 40, 40,
		40, 40, 40, 74, 40, 76, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
		40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
		40, 60, 14, 14, 14, 68, 69, 70, 71, 72, 73, 17, 17, 61, 17, 17,
		17, 17, 15, 17, 16, 17, 17, 17, 17, 17, 18, 17, 17, 17, 17, 17,
		17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
		66, 33, 33, 33, 19, 20, 21, 22, 23, 24, 14, 14, 21, 14, 39, 14,
		14, 14, 14, 14, 14, 14, 14, 14, 14, 32, 14, 14, 14, 14, 14, 14,
		14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 33,
		35, 35, 35, 33, 34, 35, 36, 37, 38, 16, 16, 35, 16, 16, 16, 16,
		16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
		16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 43, 15,
		15, 15, 50, 51, 51, 52, 52, 52, 17, 17, 45, 17, 17, 17, 17, 17,
		17, 53, 17, 17, 17, 17, 17, 18, 17, 17, 17, 17, 17, 17, 17, 17,
		17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 77, 43, 43,
		43, 19, 20, 21, 22, 23, 24, 17, 17, 78, 17, 17, 17, 17, 17, 17,
		54, 17, 17, 17, 17, 17, 18, 17, 17, 17, 17, 17, 17, 17, 17, 17,
		17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 79, 45, 45, 45,
		19, 20, 21, 22, 23, 24, 14, 14, 80, 14, 67, 14, 14, 14, 14, 14,
		14, 14, 14, 14, 14, 32, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
		14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 81, 16, 16, 16, 33,
		34, 35, 36, 37, 38, 1, 1, 2, 14, 7, 8, 82, 12, 3, 83, 9,
		10, 4, 13, 84, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
		13, 13, 13, 13, 13, 13, 5, 11, 6, 13, 50, 50, 50, 13, 85, 13,
		13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
		13, 30, 31, 55, 21, 21, 87, 28, 86, 27, 57, 26, 29, 25, 51, 51,
		51, 58, 56, 64, 40, 40, 40, 65, 68, 68, 68, 70, 70, 70, 88, 59,
		35, 35, 45, 45, 70, 70, 68, 70, 89, 90, 93, 92, 91, 94, 95, 99,
		96, 98, 97, 100, 102, 103, 104, 105, 101, 106, 108, 109, 111, 107, 112, 110,
		114, 115, 113, 118, 116, 117, 119, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		0, 0,
	}

	// transitionCheck holds the byte class every cell of transitionNext belongs to. A cell no state occupies holds
	// 47, which is one past the highest byte class in use and can never be asked for.
	transitionCheck = [674]uint8{
		0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
		16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
		32, 33, 34, 35, 36, 1, 2, 3, 2, 41, 42, 43, 44, 45, 46, 0,
		1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
		17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
		33, 34, 35, 36, 39, 37, 38, 39, 41, 42, 43, 44, 45, 46, 0, 1,
		2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
		18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
		34, 35, 36, 19, 37, 38, 39, 41, 42, 43, 44, 45, 46, 0, 1, 2,
		3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
		19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
		35, 36, 23, 37, 38, 39, 41, 42, 43, 44, 45, 46, 0, 1, 2, 3,
		4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
		20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
		36, 16, 37, 38, 39, 41, 42, 43, 44, 45, 46, 0, 1, 28, 3, 4,
		5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
		21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
		30, 37, 38, 39, 41, 42, 43, 44, 45, 46, 0, 1, 37, 3, 4, 5,
		6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
		22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39,
		37, 38, 39, 41, 42, 43, 44, 45, 46, 0, 1, 37, 3, 4, 5, 6,
		7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
		23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 37,
		38, 39, 41, 42, 43, 44, 45, 46, 0, 1, 37, 3, 4, 5, 6, 7,
		8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
		24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 16, 37, 38,
		39, 41, 42, 43, 44, 45, 46, 0, 1, 16, 3, 4, 5, 6, 7, 8,
		9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
		25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 23, 37, 38, 39,
		41, 42, 43, 44, 45, 46, 0, 1, 30, 3, 4, 5, 6, 7, 8, 9,
		10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
		26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 19, 37, 38, 39, 41,
		42, 43, 44, 45, 46, 1, 2, 3, 4, 5, 6, 26, 8, 9, 27, 11,
		12, 13, 14, 20, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
		28, 29, 30, 31, 32, 33, 34, 35, 36, 10, 37, 38, 39, 14, 21, 16,
		17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
		33, 19, 20, 17, 38, 39, 30, 25, 29, 27, 24, 29, 30, 31, 37, 38,
		39, 16, 32, 26, 37, 38, 39, 30, 37, 38, 39, 37, 38, 39, 16, 30,
		38, 39, 38, 39, 38, 39, 39, 37, 27, 30, 17, 31, 29, 19, 19, 28,
		32, 32, 22, 21, 32, 19, 19, 32, 27, 33, 26, 19, 18, 30, 19, 30,
		19, 27, 30, 17, 27, 32, 19, 47, 47, 47, 47, 47, 47, 47, 47, 47,
		47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
		47, 47,
	}

	// acceptTokenByState holds the token a state accepts, or InvalidToken for a state which does not accept.
	acceptTokenByState = [120]Token{
		InvalidToken,
		TokenWhitespace,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenLbrace,
		TokenRbrace,
		TokenLparen,
		TokenRparen,
		TokenColon,
		TokenSemi,
		TokenPipe,
		TokenComma,
		TokenIdentifier,
		InvalidToken,
		InvalidToken,
		TokenComment,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenString,
		InvalidToken,
		TokenRegex,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenRegex,
		TokenRegex,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenString,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenRegex,
		TokenComment,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenSkip,
		InvalidToken,
		InvalidToken,
		TokenName,
		TokenNone,
		TokenLeft,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenStart,
		InvalidToken,
		InvalidToken,
		TokenRight,
		TokenEmpty,
		TokenError,
		InvalidToken,
		InvalidToken,
		TokenParser,
		InvalidToken,
		InvalidToken,
		TokenScanner,
		InvalidToken,
		InvalidToken,
		InvalidToken,
		TokenFragment,
		InvalidToken,
		TokenPrecedence,
	}
)

// Scanner turns the bytes of a source into tokens.
type Scanner struct {
	// source is the bytes being scanned.
	source []byte

	// filePath is the file path the scanner was given.
	filePath string

	// token is the current token.
	token Token

	// lexemeStartIdx is the index of the first byte of the current token.
	lexemeStartIdx int

	// lexemeEndIdx is the index one past the last byte of the current token.
	lexemeEndIdx int

	// line is the line the current token starts on, counted from one.
	line int

	// column is the column the current token starts on, counted from one.
	column int
}

// NewScanner creates a scanner which turns the given bytes into tokens, starting at the first of them. The file path is
// used in error messages, so any string will do when the source is not a file.
func NewScanner(source []byte, filePath string) *Scanner {
	scanner := Scanner{
		filePath: filePath,
	}
	scanner.Reset(source, 0)
	return &scanner
}

// Token returns the current token.
func (s *Scanner) Token() Token {
	return s.token
}

// ByteOffset returns the start of the token in bytes from the start of the source. After Next returned false it is the
// offset one past the last byte.
func (s *Scanner) ByteOffset() int {
	return s.lexemeStartIdx
}

// Line returns the line the token starts on, counted from one.
func (s *Scanner) Line() int {
	return s.line
}

// Column returns the column the token starts on, counted from one.
func (s *Scanner) Column() int {
	return s.column
}

// Lexeme returns the bytes of the token, as a view into the source rather than a copy of it.
func (s *Scanner) Lexeme() []byte {
	return s.source[s.lexemeStartIdx:s.lexemeEndIdx]
}

// FilePath returns the file path the scanner was given.
func (s *Scanner) FilePath() string {
	return s.filePath
}

// Reset scans the given source from the given byte offset on. Useful for re-tokenizing the part of a source which
// changed.
func (s *Scanner) Reset(source []byte, offset int) {
	s.source = source

	s.lexemeStartIdx = 0
	// An offset past the end of the source would walk the line and column counters over bytes which are not
	// there. Clamping it leaves the scanner at the end of the source, where it reports the end token.
	s.lexemeEndIdx = min(offset, len(source))

	s.line = 1
	s.column = 1

	s.token = InvalidToken
}

// Next advances to the next token. Bytes which form no token become an invalid token. Returns false once the end of the
// source is reached, which sets the token to the end token.
func (s *Scanner) Next() bool {
	s.updateLineAndColumn(s.lexemeStartIdx, s.lexemeEndIdx)
	s.lexemeStartIdx = s.lexemeEndIdx

	var state uint32
	lexemePeekIdx := s.lexemeEndIdx
	for {
		// Remember every accepting state passed through, so the longest match wins over the first one.
		if token := acceptTokenByState[state]; token != InvalidToken {
			s.token = token
			s.lexemeEndIdx = lexemePeekIdx
		}
		if lexemePeekIdx == len(s.source) {
			// The end of the source is reached, so the state it stopped in was the last one to test.
			break
		}

		byteClass := byteClassByByte[s.source[lexemePeekIdx]]
		cellIdx := uint32(transitionBase[state]) + uint32(byteClass)
		if transitionCheck[cellIdx] != byteClass {
			// The state has no transition on this byte, so the token ends here.
			break
		}
		state = uint32(transitionNext[cellIdx])
		lexemePeekIdx++
	}

	if s.lexemeStartIdx < s.lexemeEndIdx {
		// A token was found.
		return true
	}

	if len(s.source) <= s.lexemeStartIdx {
		// The end of the source was reached.
		s.token = EndToken
		return false
	}

	// The bytes here form no token. The invalid token ends where the automaton stopped, because the byte it could not
	// consume is where the next attempt starts. Only when the automaton consumed nothing does it cover that byte,
	// which is what keeps the scan moving forward.
	s.token = InvalidToken
	s.lexemeEndIdx = max(s.lexemeStartIdx+1, lexemePeekIdx)
	return true
}

// updateLineAndColumn advances the line and column counters over the bytes between the two indexes.
func (s *Scanner) updateLineAndColumn(startIdx int, endIdx int) {
	for _, currByte := range s.source[startIdx:endIdx] {
		if currByte == '\n' {
			s.line++
			s.column = 1
		} else {
			s.column++
		}
	}
}
